# Generated by Django 5.1.6 on 2025-03-28 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('prazo', models.IntegerField(blank=True, null=True, verbose_name='Prazo')),
                ('final', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Final')),
                ('criado_por', models.CharField(max_length=40, verbose_name='Criado por')),
                ('responsavel', models.CharField(max_length=40, null=True, verbose_name='Responsável')),
                ('participantes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Participantes')),
                ('observadores', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observadores')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status')),
                ('projeto', models.CharField(max_length=40, verbose_name='Projeto')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inícil')),
                ('modificada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modificado em')),
                ('fechado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fechado em')),
                ('duracao_prevista', models.IntegerField(blank=True, null=True, verbose_name='Duração')),
                ('controlar_tempo_gasto', models.CharField(blank=True, max_length=1, null=True, verbose_name='Controlar tempo')),
                ('contato_empresa_fornecedor', models.CharField(blank=True, max_length=40, null=True, verbose_name='Contato Empresa/Empresa')),
                ('observador', models.TextField(blank=True, null=True, verbose_name='Observador')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do cadastro')),
            ],
            options={
                'verbose_name': 'Tarefas',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
