# Generated by Django 5.2 on 2025-07-05 20:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('anexo', models.FileField(blank=True, help_text="<span style='color:red;font-weight:bold;'>ATENÇÃO:</span> Arquivos podem conter vírus. Tipos permitidos: pdf, doc, docx, jpg, jpeg, png, gif (Max 5MB)", null=True, upload_to='comentarios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20, verbose_name='Status Anterior')),
                ('novo_status', models.CharField(max_length=20, verbose_name='Novo Status')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('prazo', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Final')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], default='pendente', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='baixo', max_length=10, verbose_name='Prioridade')),
                ('projeto', models.CharField(blank=True, max_length=40, null=True, verbose_name='Projeto')),
                ('duracao_prevista', models.DurationField(blank=True, null=True, verbose_name='Duração Prevista')),
                ('tempo_gasto', models.DurationField(blank=True, null=True, verbose_name='Tempo Gasto')),
                ('dias_lembrete', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Lembrete')),
                ('data_lembrete', models.DateTimeField(blank=True, null=True, verbose_name='Data de Lembrete')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prioridade', 'prazo'],
            },
        ),
    ]
