# Generated by Django 5.2.7 on 2025-10-02 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ata_reuniao', '0004_initial'),
        ('tarefas', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='alterado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_status', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='ata_reuniao',
            field=models.ForeignKey(blank=True, help_text='Vincule esta tarefa a uma atividade de uma ata de reunião, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_vinculadas', to='ata_reuniao.atareuniao', verbose_name='Atividade da Ata de Reunião'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='tarefa_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tarefas.tarefas', verbose_name='Tarefa Principal'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='tarefa_recorrencia_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_filhas', to='tarefas.tarefas', verbose_name='Tarefa Original da Recorrência'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='tarefas.tarefas', verbose_name='Tarefa'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefas', verbose_name='Tarefa'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['status'], name='tarefas_tar_status_726bce_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['prioridade'], name='tarefas_tar_priorid_2199d7_idx'),
        ),
    ]
