# Generated by Django 5.2 on 2025-07-30 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='data_fim_recorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Repetir até'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='frequencia_recorrencia',
            field=models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, null=True, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='recorrente',
            field=models.BooleanField(default=False, verbose_name='É uma tarefa recorrente?'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='tarefa_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_filhas', to='tarefas.tarefas', verbose_name='Tarefa Original da Recorrência'),
        ),
    ]
