# Generated by Django 5.2 on 2025-06-20 13:25
from django.db import migrations
from datetime import timedelta

def corrigir_duracoes(apps, schema_editor):
    Tarefas = apps.get_model('tarefas', 'Tarefas')
    for tarefa in Tarefas.objects.all():
        if tarefa.duracao_prevista and tarefa.duracao_prevista > timedelta(days=30):
            tarefa.duracao_prevista = timedelta(days=30)
            tarefa.save()
        if tarefa.tempo_gasto and tarefa.tempo_gasto > timedelta(days=30):
            tarefa.tempo_gasto = timedelta(days=30)
            tarefa.save()

class Migration(migrations.Migration):
    dependencies = [
        ('tarefas', '0001_initial'),  # Substitua pela sua migração inicial
    ]

    operations = [
        migrations.RunPython(corrigir_duracoes),
    ]

    