# Generated by Django 5.2 on 2025-09-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_reuniao', '0004_comentario'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='ata_reuniao',
            field=models.ForeignKey(blank=True, help_text='Vincule esta tarefa a uma atividade de uma ata de reunião, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_vinculadas', to='ata_reuniao.atareuniao', verbose_name='Atividade da Ata de Reunião'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='tarefa_recorrencia_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_filhas', to='tarefas.tarefas', verbose_name='Tarefa Original da Recorrência'),
        ),
    ]
