# Generated by Django 5.2 on 2025-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='prazo',
            field=models.DateTimeField(blank=True, help_text='Data limite para conclusão', null=True, verbose_name='Prazo Final'),
        ),
    ]
