# Generated by Django 5.2 on 2025-05-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefas_data_atualizacao_tarefas_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
