# Generated by Django 5.2 on 2025-06-27 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tarefas',
            name='tarefas_tar_usuario_a48ae0_idx',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dias_lembrete',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Lembrete'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='duracao_prevista',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração Prevista'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('pausada', 'Em Pausa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='tempo_gasto',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo Gasto'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
