# Generated by Django 5.2 on 2025-11-14 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='tarefas_participando', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
