# Generated by Django 5.2 on 2025-08-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefas_data_fim_recorrencia_and_more'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_status', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
