# Generated by Django 4.2.16 on 2026-02-27 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        ('ata_reuniao', '0004_initial'),
        ('tarefas', '0003_tarefas_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, help_text="<span style='color:red;font-weight:bold;'>ATENÇÃO:</span> Tipos permitidos: pdf, doc, docx, jpg, jpeg, png, gif (Max 5MB)", null=True, upload_to='comentarios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_tarefas', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_status_tarefas', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='ata_reuniao',
            field=models.ForeignKey(blank=True, help_text='Vincule esta tarefa a uma atividade de uma ata de reunião.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_vinculadas', to='ata_reuniao.atareuniao', verbose_name='Atividade da Ata de Reunião'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='baixa', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['prazo'], name='tarefas_tar_prazo_4fe1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['responsavel', 'status'], name='tarefas_tar_respons_6c43b8_idx'),
        ),
    ]
