# Generated by Django 5.2 on 2025-06-17 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefas_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='data_lembrete',
            field=models.DateTimeField(blank=True, help_text='Data para envio de lembrete antes do prazo', null=True, verbose_name='Data de Lembrete'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='dias_lembrete',
            field=models.PositiveSmallIntegerField(default=1, help_text='Dias antes do prazo para enviar lembrete', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Dias para Lembrete'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_inicio',
            field=models.DateTimeField(blank=True, help_text='Data inícil da atividade', null=True, verbose_name='Data de Início'),
        ),
    ]
