# Generated by Django 5.2 on 2025-06-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_remove_tarefas_tarefas_tar_usuario_a48ae0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
    ]
