# Generated by Django 5.2 on 2025-08-10 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_comentario_filial_historicostatus_filial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_lembrete',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Lembrete'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dias_lembrete',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Deixe em branco se não desejar um lembrete automático.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lembrar-me quantos dias antes do prazo?'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tarefas.tarefas', verbose_name='Tarefa Principal'),
        ),
    ]
