# Generated by Django 5.2 on 2025-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefas_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='baixo', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
