# Generated by Django 4.2.16 on 2026-03-13 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0004_alter_comentario_anexo_alter_comentario_filial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alteracao', models.CharField(choices=[('criacao', 'Criação'), ('status', 'Mudança de Status'), ('participante_add', 'Participante Adicionado'), ('participante_remove', 'Participante Removido'), ('responsavel', 'Mudança de Responsável'), ('prioridade', 'Mudança de Prioridade'), ('prazo', 'Mudança de Prazo'), ('titulo', 'Mudança de Título'), ('descricao', 'Mudança de Descrição'), ('projeto', 'Mudança de Projeto'), ('recorrencia', 'Mudança de Recorrência'), ('geral', 'Alteração Geral')], db_index=True, default='status', max_length=25, verbose_name='Tipo de Alteração')),
                ('campo_alterado', models.CharField(blank=True, default='', max_length=50, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, default='', verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, default='', verbose_name='Valor Novo')),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição legível da alteração', verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data da Alteração')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_tarefas_v2', to='usuario.filial', verbose_name='Filial')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_v2', to='tarefas.tarefas', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Histórico da Tarefa',
                'verbose_name_plural': 'Históricos das Tarefas',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.DeleteModel(
            name='HistoricoStatus',
        ),
        migrations.AddIndex(
            model_name='historicotarefa',
            index=models.Index(fields=['tarefa', '-data_alteracao'], name='tarefas_his_tarefa__fe82ed_idx'),
        ),
        migrations.AddIndex(
            model_name='historicotarefa',
            index=models.Index(fields=['tipo_alteracao'], name='tarefas_his_tipo_al_27e78c_idx'),
        ),
    ]
