# Generated by Django 4.2.28 on 2026-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_historicotarefa_delete_historicostatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluída'), ('andamento', 'Andamento'), ('pendente', 'Pendente'), ('pausada', 'Pausada'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
