# Generated by Django 4.2.28 on 2026-04-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_tarefas_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-prioridade', 'prazo'], 'permissions': [('view_dashboard', 'Pode ver o dashboard de tarefas'), ('view_relatorio', 'Pode ver relatórios de tarefas'), ('view_kanban', 'Pode ver o quadro Kanban'), ('view_calendario', 'Pode ver o calendário de tarefas')], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
