# Generated by Django 5.2.13 on 2026-04-14 14:24

import core.upload
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, help_text='PDF, imagens ou documentos Office. Máximo: 15MB.', null=True, upload_to=core.upload.UploadPath('tarefas'), validators=[core.validators.SecureFileValidator(app_name='tarefas')], verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
    ]
