# Generated by Django 5.2.13 on 2026-04-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_comentario_anexo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-prioridade', 'prazo'], 'permissions': [('view_dashboard', 'Pode ver o dashboard de tarefas'), ('view_relatorio', 'Pode ver relatórios de tarefas'), ('view_kanban', 'Pode ver o quadro Kanban'), ('view_calendario', 'Pode ver o calendário de tarefas'), ('view_all_tarefas', 'Pode visualizar todas as tarefas')], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
