# Generated by Django 4.2.28 on 2026-04-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-prioridade', 'prazo'], 'permissions': [('view_dashboard', 'Pode ver o dashboard de tarefas'), ('view_relatorio', 'Pode ver relatórios de tarefas'), ('view_kamban', 'Pode ver o quadro Kamban'), ('view_calendario', 'Pode ver o calendário de tarefas'), ('view_all_tarefas', 'Pode visualizar todas as tarefas')], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
