# Generated by Django 4.2.28 on 2026-05-02 15:48

import core.upload
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_alter_tarefas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, help_text='PDF, imagens ou documentos Office. Máximo: 5MB.', null=True, upload_to=core.upload.UploadPath('tarefas'), validators=[core.validators.SecureFileValidator(app_name='tarefas')], verbose_name='Anexo'),
        ),
    ]
