# Generated by Django 4.2.28 on 2026-05-06 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_alter_filial_options'),
        ('tarefas', '0011_alter_comentario_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20)),
                ('novo_status', models.CharField(max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='historicotarefa',
            options={'ordering': ['-data_alteracao']},
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-data_criacao'], 'permissions': [('view_all_tarefas', 'Pode ver todas as tarefas (sem filtro)')], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveIndex(
            model_name='historicotarefa',
            name='tarefas_his_tarefa__fe82ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicotarefa',
            name='tarefas_his_tipo_al_27e78c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefas',
            name='tarefas_tar_status_726bce_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefas',
            name='tarefas_tar_priorid_2199d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefas',
            name='tarefas_tar_prazo_4fe1b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefas',
            name='tarefas_tar_respons_6c43b8_idx',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='historicotarefa',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='historicotarefa',
            name='tipo_alteracao',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='data_lembrete',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='tarefa_pai',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='aviso_fim_enviado_em',
            field=models.DateTimeField(blank=True, help_text='Controla envio único do aviso de fim de recorrência.', null=True, verbose_name='Aviso de fim enviado em'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='dias_aviso_fim_recorrencia',
            field=models.PositiveIntegerField(default=30, help_text='Quantos dias antes do fim da recorrência avisar (padrão: 30).', verbose_name='Dias para aviso de fim'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='lembrete_enviado_em',
            field=models.DateTimeField(blank=True, help_text='Controla envio único de lembrete.', null=True, verbose_name='Lembrete enviado em'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='recorrencia_encerrada',
            field=models.BooleanField(default=False, help_text='Marca True quando a recorrência atingiu data_fim ou limite máximo.', verbose_name='Recorrência encerrada'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='tarefas/comentarios/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_tarefas', to='usuario.filial'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefas'),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='alterado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='campo_alterado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_v2', to='tarefas.tarefas'),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='valor_anterior',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='valor_novo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='ata_reuniao',
            field=models.TextField(blank=True, default=1, help_text='Vincule a tarefa a uma ata ou reunião específica.', verbose_name='Atividade da Ata de Reunião'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizada em'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_fim_recorrencia',
            field=models.DateField(blank=True, help_text='Após esta data, novas ocorrências não serão geradas.', null=True, verbose_name='Fim da Recorrência'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(blank=True, default=2, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dias_lembrete',
            field=models.PositiveIntegerField(default=0, help_text='Quantos dias antes do prazo enviar lembrete (0 = desativado).', verbose_name='Dias para Lembrete'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='duracao_prevista',
            field=models.DurationField(blank=True, help_text='Formato: HH:MM:SS ou dias HH:MM:SS', null=True, verbose_name='Duração Prevista'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='usuario.filial', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='frequencia_recorrencia',
            field=models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default=30, max_length=20, verbose_name='Frequência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='tarefas_participante', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('media', 'Média'), ('alta', 'Alta')], default='normal', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='projeto',
            field=models.CharField(blank=True, default=2, max_length=100, verbose_name='Projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Se marcada, novas ocorrências serão geradas automaticamente.', verbose_name='Tarefa Recorrente'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa_recorrencia_pai',
            field=models.ForeignKey(blank=True, help_text='Aponta para a tarefa original que gerou esta ocorrência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_filhas', to='tarefas.tarefas', verbose_name='Tarefa-Raiz da Recorrência'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='tempo_gasto',
            field=models.DurationField(blank=True, help_text='Tempo total trabalhado na tarefa.', null=True, verbose_name='Tempo Gasto'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['status', 'prazo'], name='tarefas_tar_status_00de63_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['filial', 'status'], name='tarefas_tar_filial__cd60ea_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['recorrente', 'recorrencia_encerrada'], name='tarefas_tar_recorre_5ba62a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['tarefa_recorrencia_pai'], name='tarefas_tar_tarefa__1b1cc0_idx'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='alterado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='tarefas.tarefas'),
        ),
    ]
