# Generated by Django 4.2.28 on 2026-05-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0012_historicostatus_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicotarefa',
            options={'ordering': ['-data_alteracao'], 'permissions': [('view_historico_tarefa', 'Pode ver histórico de tarefas')], 'verbose_name': 'Histórico de Tarefa', 'verbose_name_plural': 'Históricos de Tarefas'},
        ),
        migrations.AddField(
            model_name='historicotarefa',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_tarefa', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='historicotarefa',
            name='tipo_alteracao',
            field=models.CharField(choices=[('status', 'Mudança de Status'), ('participantes', 'Alteração de Participantes'), ('campo', 'Alteração de Campo'), ('comentario', 'Novo Comentário'), ('criacao', 'Criação'), ('exclusao', 'Exclusão')], db_index=True, default='campo', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='campo_alterado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
