# Generated by Django 5.2.17 on 2026-10-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0013_alter_historicotarefa_options_historicotarefa_filial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-data_criacao'], 'permissions': [('view_all_tarefas', 'Pode ver todas as tarefas (sem filtro)'), ('export_tarefas', 'Pode exportar relatórios de tarefas (LGPD)'), ('view_desempenho_equipe', 'Pode ver desempenho/ranking da equipe')], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
