# Generated by Django 5.2.17 on 2026-10-03 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0014_alter_tarefas_options'),
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-data_criacao'], 'permissions': [('view_all_tarefas', 'Pode ver todas as tarefas da filial (sem filtro)'), ('export_tarefas', 'Pode exportar relatórios de tarefas (LGPD)'), ('view_desempenho_equipe', 'Pode ver desempenho/ranking da equipe')], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['responsavel', 'status'], name='tarefas_tar_respons_6c43b8_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefas',
            index=models.Index(fields=['usuario'], name='tarefas_tar_usuario_a48ae0_idx'),
        ),
    ]
