# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia / Nome do Fabricante')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('eh_fabricante', models.BooleanField(default=False, verbose_name='É Fabricante?')),
                ('eh_fornecedor', models.BooleanField(default=False, verbose_name='É Fornecedor?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parceiros', to='logradouro.logradouro', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
