# Generated by Django 4.2.16 on 2026-03-06 01:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.CharField(max_length=20, unique=True, verbose_name='CM (Código)')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='usuario.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['cm'],
            },
        ),
        migrations.AlterModelManagers(
            name='parceiro',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Nº Pedido')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('ENTREGUE', 'Entregue'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data Entrega')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data Recebimento')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('motivo_reprovacao', models.TextField(blank=True, default='', verbose_name='Motivo Reprovação')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='suprimentos.contrato', verbose_name='Contrato')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.filial', verbose_name='Filial')),
                ('recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Pedido de Material',
                'verbose_name_plural': 'Pedidos de Material',
                'ordering': ['-data_pedido'],
                'permissions': [('pode_aprovar_pedido', 'Pode aprovar pedidos de material')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente se deixado em branco.', max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('classificacao', models.CharField(choices=[('CONSUMO', 'Consumo'), ('EPI', 'EPI'), ('FERRAMENTA', 'Ferramenta')], max_length=20, verbose_name='Classificação')),
                ('tipo', models.CharField(choices=[('CIVIL', 'Civil'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('LIMPEZA', 'Limpeza'), ('ESCRITORIO', 'Escritório'), ('CREME', 'Creme'), ('EPI', 'EPI'), ('PRODUTO_QUIMICO', 'Produto Químico'), ('AR_CONDICIONADO', 'Ar Condicionado'), ('PISCINA', 'Piscina')], max_length=30, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('unidade', models.CharField(choices=[('PC', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade')], default='PC', max_length=20, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Unitário (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['classificacao', 'tipo', 'descricao'],
                'indexes': [models.Index(fields=['classificacao', 'tipo'], name='suprimentos_classif_416426_idx'), models.Index(fields=['descricao'], name='suprimentos_descric_cc6679_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Valor Total (R$)')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='suprimentos.material', verbose_name='Material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['material__classificacao', 'material__tipo'],
            },
        ),
        migrations.CreateModel(
            name='VerbaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('verba_epi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Verba EPI (R$)')),
                ('verba_consumo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Verba Consumo (R$)')),
                ('verba_ferramenta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Verba Ferramenta (R$)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbas', to='suprimentos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Verba Mensal',
                'verbose_name_plural': 'Verbas Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('contrato', 'ano', 'mes')},
            },
        ),
    ]
