# Generated by Django 4.2.16 on 2026-03-06 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        ('ferramentas', '0003_alter_termoderesponsabilidade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguranca_trabalho', '0007_adicionar_estoque_atual_equipamento'),
        ('suprimentos', '0002_contrato_alter_parceiro_managers_pedido_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='equipamento_epi',
            field=models.ForeignKey(blank=True, help_text='Vincule ao equipamento de SST para entrada automática no estoque ao receber pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_vinculados', to='seguranca_trabalho.equipamento', verbose_name='Equipamento EPI vinculado'),
        ),
        migrations.AddField(
            model_name='material',
            name='ferramenta_ref',
            field=models.ForeignKey(blank=True, help_text='Vincule à ferramenta para atualizar quantidade ao receber pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_vinculados', to='ferramentas.ferramenta', verbose_name='Ferramenta vinculada'),
        ),
        migrations.CreateModel(
            name='EstoqueConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('justificativa', models.CharField(blank=True, default='', max_length=255, verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_consumo', to='suprimentos.contrato', verbose_name='Contrato')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.filial', verbose_name='Filial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_consumo', to='suprimentos.material', verbose_name='Material')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='suprimentos.pedido', verbose_name='Pedido Origem')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque (Consumo)',
                'verbose_name_plural': 'Movimentações de Estoque (Consumo)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
