# Generated by Django 4.2.16 on 2026-03-22 00:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tributacao', '0001_initial'),
        ('suprimentos', '0004_pedido_estoque_processado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Valor total menos créditos fiscais recuperáveis', max_digits=14, verbose_name='Custo Real (R$)'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='total_creditos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Créditos Fiscais (R$)'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='total_impostos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Total Impostos (R$)'),
        ),
        migrations.AddField(
            model_name='material',
            name='grupo_tributario',
            field=models.ForeignKey(blank=True, help_text='Perfil fiscal para cálculo automático de impostos na compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='tributacao.grupotributario', verbose_name='Grupo Tributário'),
        ),
        migrations.AddField(
            model_name='material',
            name='ncm',
            field=models.ForeignKey(blank=True, help_text='Classificação fiscal do material (Nomenclatura Comum do Mercosul)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='tributacao.ncm', verbose_name='NCM'),
        ),
    ]
