# Generated by Django 4.2.16 on 2026-03-27 22:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import suprimentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0005_itempedido_custo_real_itempedido_total_creditos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_necessaria',
            field=models.DateField(blank=True, help_text='Data em que o material deve estar disponível no contrato.', null=True, verbose_name='Data Necessária para Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descricao_material',
            field=models.TextField(blank=True, default='', help_text='Informe uma descrição DETALHADA e PRECISA do material. Isso garante maior agilidade, assertividade e redução de retrabalhos no processo de cotação e compra.', verbose_name='Descrição do Material'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_revisao',
            field=models.TextField(blank=True, default='', help_text='Preenchido pelo Gerente ao devolver para revisão.', verbose_name='Motivo da Revisão/Devolução'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_insumo',
            field=models.CharField(blank=True, choices=[('CIVIL', 'Civil'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('LIMPEZA', 'Limpeza'), ('ESCRITORIO', 'Escritório'), ('CREME', 'Creme'), ('EPI', 'EPI'), ('PRODUTO_QUIMICO', 'Produto Químico'), ('AR_CONDICIONADO', 'Ar Condicionado'), ('PISCINA', 'Piscina')], default='', max_length=30, verbose_name='Tipo de Insumo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_obra',
            field=models.CharField(choices=[('CM', 'CM - Contrato de Manutenção'), ('CR', 'CR - Contrato de Reforma'), ('VE', 'VE - Venda')], default='CM', max_length=2, verbose_name='Tipo de Obra'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='unidade_medida',
            field=models.CharField(choices=[('PC', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade')], default='UNID', max_length=20, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Custo Real (R$)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='aprovador',
            field=models.ForeignKey(blank=True, help_text='Gerente responsável pela aprovação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estoque_processado',
            field=models.BooleanField(default=False, editable=False, help_text='Indica se a entrada no estoque já foi gerada.', verbose_name='Estoque Processado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Aprovação'), ('REVISAO', 'Em Revisão pelo Solicitante'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('ENTREGUE', 'Entregue'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Nº Solicitação')),
                ('status', models.CharField(choices=[('FAZER_COTACAO', 'Fazer Cotação'), ('COTACAO_ENVIADA', 'Cotação Enviada'), ('CRIAR_PEDIDO_CT', 'Criar Pedido/CT'), ('EM_APROVACAO', 'Em Aprovação'), ('ENVIAR_PEDIDO', 'Enviar Pedido'), ('ENTREGA_PENDENTE', 'Entrega Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='FAZER_COTACAO', max_length=25, verbose_name='Status')),
                ('tipo_obra', models.CharField(choices=[('CM', 'CM - Contrato de Manutenção'), ('CR', 'CR - Contrato de Reforma'), ('VE', 'VE - Venda')], max_length=2, verbose_name='Tipo de Obra')),
                ('descricao_material', models.TextField(verbose_name='Descrição do Material')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantidade')),
                ('unidade_medida', models.CharField(choices=[('PC', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade')], default='UNID', max_length=20, verbose_name='Unidade de Medida')),
                ('tipo_insumo', models.CharField(blank=True, choices=[('CIVIL', 'Civil'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('LIMPEZA', 'Limpeza'), ('ESCRITORIO', 'Escritório'), ('CREME', 'Creme'), ('EPI', 'EPI'), ('PRODUTO_QUIMICO', 'Produto Químico'), ('AR_CONDICIONADO', 'Ar Condicionado'), ('PISCINA', 'Piscina')], default='', max_length=30, verbose_name='Tipo de Insumo')),
                ('data_necessaria', models.DateField(blank=True, null=True, verbose_name='Data Necessária para Entrega')),
                ('data_aprovacao_inicial', models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação Inicial')),
                ('data_cotacao', models.DateField(blank=True, null=True, verbose_name='Data da Cotação')),
                ('numero_cotacao', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da Cotação')),
                ('cnpj_compra', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ para Compra')),
                ('tipo_nota_fiscal', models.CharField(blank=True, choices=[('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('MATERIAL_SERVICO', 'Material/Serviço')], default='', max_length=20, verbose_name='Tipo de Nota Fiscal')),
                ('data_validacao_cotacao', models.DateField(blank=True, null=True, verbose_name='Data da Validação')),
                ('data_criacao_pedido', models.DateField(blank=True, null=True, verbose_name='Data Criação do Pedido')),
                ('numero_pedido_sienge', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº do Pedido (Sienge)')),
                ('valor_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor do Pedido (R$)')),
                ('data_aprovacao_pedido', models.DateField(blank=True, null=True, verbose_name='Data Aprovação do Pedido')),
                ('data_envio_fornecedor', models.DateField(blank=True, null=True, verbose_name='Data Envio ao Fornecedor')),
                ('data_prevista_entrega', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Entrega')),
                ('data_entrega_efetiva', models.DateField(blank=True, help_text='Obtida via planilha de rotas do motorista.', null=True, verbose_name='Data de Entrega Efetiva')),
                ('numero_nota_fiscal', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da Nota Fiscal')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Registro de informações relevantes sobre o processo.', verbose_name='Observações')),
                ('motivo_cancelamento', models.TextField(blank=True, default='', verbose_name='Motivo do Cancelamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovador_cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovador_cotacao', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador da Cotação')),
                ('aprovador_inicial', models.ForeignKey(blank=True, help_text='Gerente que aprovou o pedido original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovador_inicial', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador (Gerente)')),
                ('aprovador_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovador_pedido', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador do Pedido')),
                ('comprador', models.ForeignKey(blank=True, help_text='Profissional de Suprimentos responsável pela cotação e compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_comprador', to=settings.AUTH_USER_MODEL, verbose_name='Comprador Responsável')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra', to='suprimentos.contrato', verbose_name='Obra (CM / CR / VE)')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.filial', verbose_name='Filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_fornecidas', to='suprimentos.parceiro', verbose_name='Fornecedor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Compra',
                'verbose_name_plural': 'Solicitações de Compra',
                'ordering': ['-criado_em'],
                'permissions': [('pode_executar_cotacao', 'Pode executar cotações (Comprador)')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='Versão')),
                ('descricao', models.TextField(verbose_name='Descrição das Alterações')),
                ('status_anterior', models.CharField(blank=True, default='', max_length=25, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, default='', max_length=25, verbose_name='Status Novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='suprimentos.solicitacaocompra', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Histórico da Solicitação',
                'verbose_name_plural': 'Histórico das Solicitações',
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='Versão')),
                ('descricao', models.TextField(verbose_name='Descrição das Alterações')),
                ('status_anterior', models.CharField(blank=True, default='', max_length=25, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, default='', max_length=25, verbose_name='Status Novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='suprimentos.pedido', verbose_name='Pedido')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico do Pedido',
                'verbose_name_plural': 'Histórico dos Pedidos',
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=suprimentos.models.solicitacao_upload_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='suprimentos.solicitacaocompra', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Anexo da Solicitação',
                'verbose_name_plural': 'Anexos da Solicitação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=suprimentos.models.anexo_pedido_upload_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='suprimentos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Anexo do Pedido',
                'verbose_name_plural': 'Anexos do Pedido',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitacao_gerada',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origem', to='suprimentos.solicitacaocompra', verbose_name='Solicitação de Compra Gerada'),
        ),
    ]
