# Generated by Django 4.2.28 on 2026-04-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        ('suprimentos', '0006_pedido_data_necessaria_pedido_descricao_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
