# Generated by Django 5.2.13 on 2026-04-13 23:25

import core.upload
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0007_material_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexopedido',
            name='arquivo',
            field=models.FileField(help_text='PDF ou imagem (máx. 10 MB).', upload_to=core.upload.UploadPath('suprimentos_pedido'), validators=[core.validators.SecureFileValidator(app_name='suprimentos_pedido')], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='arquivo',
            field=models.FileField(help_text='PDF ou imagem (máx. 10 MB).', upload_to=core.upload.UploadPath('suprimentos_solicitacao'), validators=[core.validators.SecureFileValidator(app_name='suprimentos_solicitacao')], verbose_name='Arquivo'),
        ),
    ]
