# Generated by Django 5.2.13 on 2026-04-19 21:51

import core.upload
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0008_alter_anexopedido_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexopedido',
            name='arquivo',
            field=models.FileField(upload_to=core.upload.UploadPath('suprimentos_anexos_pedido'), validators=[core.validators.SecureFileValidator(app_name='suprimentos_anexos_pedido')], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexopedido',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_pedido_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='arquivo',
            field=models.FileField(upload_to=core.upload.UploadPath('suprimentos_anexos_solicitacao'), validators=[core.validators.SecureFileValidator(app_name='suprimentos_anexos_solicitacao')], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_solicitacao_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
    ]
