# Generated by Django 4.2.28 on 2026-05-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0009_alter_anexopedido_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexopedido',
            options={'ordering': ['-criado_em'], 'permissions': [('view_anexopedido_outros', 'Pode ver anexos de pedidos de outros usuários'), ('download_anexopedido', 'Pode baixar anexos de pedidos')], 'verbose_name': 'Anexo do Pedido', 'verbose_name_plural': 'Anexos dos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='anexosolicitacao',
            options={'ordering': ['-criado_em'], 'permissions': [('view_anexosolicitacao_confidencial', 'Pode ver anexos confidenciais'), ('download_anexosolicitacao', 'Pode baixar anexos de solicitações')], 'verbose_name': 'Anexo da Solicitação', 'verbose_name_plural': 'Anexos das Solicitações'},
        ),
        migrations.AddField(
            model_name='anexopedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anexosolicitacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anexosolicitacao',
            name='confidencial',
            field=models.BooleanField(default=False, help_text='Se marcado, apenas Gerência pode visualizar.'),
        ),
        migrations.AddField(
            model_name='anexosolicitacao',
            name='tipo_documento',
            field=models.CharField(choices=[('COTACAO', 'Cotação'), ('PEDIDO_SIENGE', 'Pedido Sienge'), ('NOTA_FISCAL', 'Nota Fiscal'), ('COMPROVANTE', 'Comprovante de Entrega'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='acao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='dados_anteriores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='dados_novos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='acao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='dados_anteriores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='dados_novos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_solicitacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao', to='suprimentos.pedido'),
        ),
        migrations.AlterField(
            model_name='anexopedido',
            name='descricao',
            field=models.CharField(blank=True, default='', help_text='Descrição opcional do anexo', max_length=255),
        ),
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='suprimentos.pedido'),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_pedido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=25, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='status_novo',
            field=models.CharField(blank=True, max_length=25, verbose_name='Status Novo'),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_solic_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
