# Generated by Django 4.2.28 on 2026-05-20 20:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_alter_filial_options'),
        ('suprimentos', '0010_alter_anexopedido_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Unitário (R$)')),
                ('prazo_entrega_dias', models.PositiveIntegerField(blank=True, help_text='Prazo prometido pelo fornecedor em dias corridos.', null=True, verbose_name='Prazo de Entrega (dias)')),
                ('condicoes_pagamento', models.CharField(blank=True, default='', help_text='Ex.: 28/35/42 dias, à vista, boleto 30d...', max_length=100, verbose_name='Condições de Pagamento')),
                ('validade_cotacao', models.DateField(blank=True, null=True, verbose_name='Validade da Cotação')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('anexo_cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_vinculadas', to='suprimentos.anexosolicitacao', verbose_name='Anexo (PDF da cotação)')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'ativo': True, 'eh_fornecedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_realizadas', to='suprimentos.parceiro', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['item_solicitacao', 'valor_unitario'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, help_text='Numeração interna automática (PC-AAAAMM-NNNN).', max_length=30, unique=True, verbose_name='Nº Interno')),
                ('numero_pedido', models.CharField(blank=True, default='', help_text='Nº do PC no sistema externo (ex-Sienge), preenchido pelo comprador.', max_length=50, verbose_name='Nº do Pedido (Externo)')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDO', 'Emitido'), ('ENVIADO_FORNECEDOR', 'Enviado ao Fornecedor'), ('ENTREGUE', 'Entregue'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de Envio ao Fornecedor')),
                ('data_entrega_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Entrega')),
                ('data_entrega_efetiva', models.DateField(blank=True, null=True, verbose_name='Data Efetiva de Entrega')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automaticamente a partir dos itens.', max_digits=14, verbose_name='Valor Total (R$)')),
                ('numero_nota_fiscal', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da Nota Fiscal')),
                ('data_nota_fiscal', models.DateField(blank=True, null=True, verbose_name='Data da Nota Fiscal')),
                ('tipo_nota_fiscal', models.CharField(blank=True, choices=[('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('MATERIAL_SERVICO', 'Material/Serviço')], default='', max_length=20, verbose_name='Tipo de NF')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('motivo_cancelamento', models.TextField(blank=True, default='', verbose_name='Motivo do Cancelamento')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='usuario.filial', verbose_name='Filial')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'eh_fornecedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_recebidos', to='suprimentos.parceiro', verbose_name='Fornecedor')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_recebidos_por', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='suprimentos.solicitacaocompra', verbose_name='Solicitação de Compra')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-criado_em'],
                'permissions': [('pode_emitir_pedido_compra', 'Pode emitir Pedido de Compra'), ('pode_receber_pedido_compra', 'Pode dar entrada em Pedido de Compra')],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('valor_unitario_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de referência herdado do ItemPedido.', max_digits=12, verbose_name='Valor Unitário Estimado (R$)')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação')),
                ('status', models.CharField(choices=[('PENDENTE_COTACAO', 'Pendente de Cotação'), ('COTADO', 'Cotado (aguardando aprovação)'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_COTACAO', max_length=20, verbose_name='Status')),
                ('motivo_reprovacao', models.TextField(blank=True, default='', verbose_name='Motivo Reprovação')),
                ('cotacao_escolhida', models.ForeignKey(blank=True, help_text='Cotação aprovada pelo gerente para este item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_que_escolheram', to='suprimentos.cotacao', verbose_name='Cotação Escolhida')),
                ('item_pedido_origem', models.ForeignKey(blank=True, help_text='Rastreabilidade: ItemPedido que originou esta linha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_solicitacao_gerados', to='suprimentos.itempedido', verbose_name='Item do Pedido (Origem)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao', to='suprimentos.material', verbose_name='Material')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.solicitacaocompra', verbose_name='Solicitação de Compra')),
            ],
            options={
                'verbose_name': 'Item da Solicitação',
                'verbose_name_plural': 'Itens da Solicitação',
                'ordering': ['material__classificacao', 'material__descricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Snapshot da cotação no momento da emissão.', max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Valor Total (R$)')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Atualizada no recebimento do PC.', max_digits=12, verbose_name='Quantidade Recebida')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação')),
                ('cotacao', models.ForeignKey(help_text='Cotação aprovada que originou este item.', on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra_gerados', to='suprimentos.cotacao', verbose_name='Cotação Origem')),
                ('item_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='suprimentos.itemsolicitacao', verbose_name='Item da Solicitação')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='suprimentos.material', verbose_name='Material')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.pedidocompra', verbose_name='Pedido de Compra')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens do Pedido de Compra',
                'ordering': ['material__classificacao', 'material__descricao'],
            },
        ),
        migrations.AddField(
            model_name='cotacao',
            name='item_solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='suprimentos.itemsolicitacao', verbose_name='Item da Solicitação'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['solicitacao', 'fornecedor'], name='suprimentos_solicit_9f8532_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['status'], name='suprimentos_status_257367_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['numero_pedido'], name='suprimentos_numero__ac197a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitacao',
            index=models.Index(fields=['solicitacao', 'status'], name='suprimentos_solicit_b874aa_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitacao',
            index=models.Index(fields=['material'], name='suprimentos_materia_0383be_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedidocompra',
            index=models.Index(fields=['pedido_compra'], name='suprimentos_pedido__77334f_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedidocompra',
            index=models.Index(fields=['cotacao'], name='suprimentos_cotacao_0b4e80_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['item_solicitacao', 'valor_unitario'], name='suprimentos_item_so_68272a_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['fornecedor'], name='suprimentos_fornece_91b6cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotacao',
            constraint=models.UniqueConstraint(fields=('item_solicitacao', 'fornecedor'), name='unique_cotacao_item_fornecedor', violation_error_message='Já existe uma cotação deste fornecedor para este item.'),
        ),
    ]
