# Generated by Django 4.2.28 on 2026-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0011_fase1_novos_modelos_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocompra',
            name='numero_pedido',
            field=models.CharField(blank=True, default='', help_text='Nº do pedido no sistema externo. DEPRECATED na SolicitacaoCompra — usar PedidoCompra.numero_pedido.', max_length=50, verbose_name='Nº do Pedido (Externo)'),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='usa_novo_fluxo',
            field=models.BooleanField(default=False, help_text='Marca se esta solicitação usa o fluxo com ItemSolicitacao+Cotacao+PedidoCompra.', verbose_name='Usa novo fluxo (v2)'),
        ),
    ]
