# Generated by Django 4.2.28 on 2026-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0012_fase2_campos_deprecated_e_novo_fluxo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Aprovação'), ('REVISAO', 'Em Revisão pelo Solicitante'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('ENTREGUE', 'Entregue'), ('RECEBIDO', 'Recebido'), ('SOLICITACAO_GERADA', 'Solicitação Gerada'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
