# Generated by Django 4.2.28 on 2026-05-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0013_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descricao_material',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_insumo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='unidade_medida',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='unidade_medida',
            field=models.CharField(choices=[('PC', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade')], default='UNID', max_length=20, verbose_name='Unidade de Medida'),
        ),
    ]
