# Generated by Django 4.2.28 on 2026-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0014_remove_pedido_descricao_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='tipo_documento',
            field=models.CharField(choices=[('COTACAO', 'Cotação'), ('PEDIDO', 'Pedido'), ('NOTA_FISCAL', 'Nota Fiscal'), ('COMPROVANTE', 'Comprovante de Entrega'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='numero_pedido',
            field=models.CharField(blank=True, default='', help_text='Nº do PC no sistema externo, preenchido pelo comprador.', max_length=50, verbose_name='Nº do Pedido (Externo)'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='numero_pedido_sienge',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nº do Pedido'),
        ),
    ]
