
# Generated by Django 4.2.28 on 2026-05-27 17:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0015_alter_anexosolicitacao_tipo_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaocompra',
            name='numero_pedido_sienge',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='unidade_medida',
            field=models.CharField(choices=[('PÇ', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('METRO', 'Metro'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade'), ('TON', 'Tonelada')], default='UNID', max_length=20, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('LIMPEZA', 'Limpeza'), ('ESCRITORIO', 'Escritório'), ('CREME', 'Creme'), ('EPI', 'EPI'), ('PRODUTO QUIMICO', 'Produto Químico'), ('AR CONDICIONADO', 'Ar Condicionado'), ('PISCINA', 'Piscina'), ('INFORMATICA', 'Informática')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade',
            field=models.CharField(choices=[('PÇ', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('METRO', 'Metro'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade'), ('TON', 'Tonelada')], default='PÇ', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='numero_pedido',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nº do Pedido'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='tipo_insumo',
            field=models.CharField(blank=True, choices=[('CIVIL', 'Civil'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('LIMPEZA', 'Limpeza'), ('ESCRITORIO', 'Escritório'), ('CREME', 'Creme'), ('EPI', 'EPI'), ('PRODUTO QUIMICO', 'Produto Químico'), ('AR CONDICIONADO', 'Ar Condicionado'), ('PISCINA', 'Piscina'), ('INFORMATICA', 'Informática')], default='', max_length=30, verbose_name='Tipo de Insumo'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='unidade_medida',
            field=models.CharField(choices=[('PÇ', 'Peça'), ('PAR', 'Par'), ('LATA', 'Lata'), ('ROLO', 'Rolo'), ('GALAO', 'Galão'), ('PACOTE', 'Pacote'), ('JOGO', 'Jogo'), ('KIT', 'Kit'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('POTE', 'Pote'), ('KG', 'Kg'), ('METRO', 'Metro'), ('LITRO', 'Litro'), ('CARTELA', 'Cartela'), ('UNID', 'Unidade'), ('TON', 'Tonelada')], default='UNID', max_length=20, verbose_name='Unidade de Medida'),
        ),
    ]
