# Generated by Django 4.2.28 on 2026-05-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0016_remove_solicitacaocompra_numero_pedido_sienge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['item_solicitacao', 'valor_unitario'], 'permissions': [('pode_validar_cotacao', 'Pode validar cotações')], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
    ]
