# Generated by Django 4.2.28 on 2026-06-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0017_alter_cotacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolicitacao',
            name='cotacao_escolhida',
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('FAZER_COTACAO', 'Fazer Cotação'), ('COTACAO_ENVIADA', 'Cotação Enviada'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADO', 'Aprovado (montar pedidos)'), ('SOLICITACAO_GERADA', 'Solicitação Gerada'), ('ENVIAR_PEDIDO', 'Enviar Pedido'), ('ENTREGA_PENDENTE', 'Entrega Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='FAZER_COTACAO', max_length=25, verbose_name='Status'),
        ),
    ]
