# Generated by Django 4.2.28 on 2026-06-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0018_remove_itemsolicitacao_cotacao_escolhida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacao',
            name='cotacao_escolhida',
            field=models.ForeignKey(blank=True, help_text='Cotação aprovada pelo gerente para este item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_que_escolheram', to='suprimentos.cotacao', verbose_name='Cotação Escolhida'),
        ),
    ]
