# Generated by Django 4.2.28 on 2026-06-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0019_itemsolicitacao_cotacao_escolhida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['item_solicitacao', 'valor_unitario'], 'permissions': [('pode_cotar', 'Pode lançar cotações'), ('pode_aprovar_cotacao', 'Pode aprovar cotações'), ('pode_montar_pc', 'Pode montar pedido de compra'), ('pode_visualizar_pc', 'Pode visualizar pedido de compra'), ('pode_receber_pc', 'Pode dar entrada em pedido de compra')], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_emitir_pedido_compra', 'Pode emitir Pedido de Compra'), ('pode_receber_pedido_compra', 'Pode dar entrada em Pedido de Compra'), ('pode_cancelar_pedido_compra', 'Pode cancelar Pedido de Compra'), ('pode_visualizar_pedido_compra', 'Pode visualizar Pedido de Compra')], 'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
    ]
