# Generated by Django 4.2.28 on 2026-06-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0020_alter_cotacao_options_alter_pedidocompra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='anexo_cotacao',
            field=models.FileField(blank=True, null=True, upload_to='cotacoes/%Y/%m/', verbose_name='Anexo (PDF da cotação)'),
        ),
    ]
