# Generated by Django 4.2.28 on 2026-06-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0021_alter_cotacao_anexo_cotacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaocompra',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_executar_cotacao', 'Pode executar cotações de compra'), ('pode_montar_pc', 'Pode montar pedido de compra'), ('pode_enviar_pc', 'Pode enviar pedido de compra'), ('pode_aprovar_pc', 'Pode aprovar pedido de compra'), ('pode_entregar_pc', 'Pode entregar pedido de compra'), ('pode_concluir_pc', 'Pode concluir pedido de compra'), ('pode_cancelar_pc', 'Pode cancelar pedido de compra')], 'verbose_name': 'Solicitação de Compra', 'verbose_name_plural': 'Solicitações de Compra'},
        ),
    ]
