# Generated by Django 4.2.28 on 2026-06-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0022_alter_solicitacaocompra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['item_solicitacao', 'valor_unitario'], 'permissions': [('pode_cotar', 'Pode lançar cotações'), ('pode_aprovar_cotacao', 'Pode aprovar cotações'), ('pode_visualizar_pc', 'pode_visualizar_pedido_compra'), ('pode_receber_pc', 'pode_receber_pedido_compra')], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
    ]
