# Generated by Django 4.2.28 on 2026-06-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0023_alter_cotacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['item_solicitacao', 'valor_unitario'], 'permissions': [('pode_cotar', 'Pode lançar cotações'), ('pode_aprovar_cotacao', 'Pode aprovar cotações')], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
    ]
