# Generated by Django 4.2.28 on 2026-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0024_alter_cotacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('FAZER_COTACAO', 'Fazer Cotação'), ('COTACAO_ENVIADA', 'Cotação Enviada'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADO', 'Aprovado'), ('ENVIAR_PEDIDO', 'Pronto p/ Pedido de Compra'), ('PEDIDO_GERADO', 'Pedido de Compra Gerado'), ('EM_ENTREGA', 'Acompanhar Entrega'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='FAZER_COTACAO', max_length=25, verbose_name='Status'),
        ),
    ]
