# Generated by Django 4.2.28 on 2026-06-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0025_alter_solicitacaocompra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDO', 'Emitido'), ('ENVIADO_FORNECEDOR', 'Enviado ao Fornecedor'), ('ENTREGA_PARCIAL', 'Entrega Parcial'), ('ENTREGUE', 'Entregue'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='EntregaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='entregas/%Y/%m/')),
                ('nota_fiscal', models.CharField(blank=True, max_length=60, verbose_name='Nota Fiscal')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_entrega_enviados', to=settings.AUTH_USER_MODEL)),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_entrega', to='suprimentos.pedidocompra')),
            ],
            options={
                'verbose_name': 'Anexo de Entrega',
                'verbose_name_plural': 'Anexos de Entrega',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
