# Generated by Django 4.2.28 on 2026-06-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0026_alter_pedidocompra_status_entregaanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexopedido',
            name='observacao',
            field=models.CharField(blank=True, default='', help_text='Descrição opcional do anexo.', max_length=255, verbose_name='Observação'),
        ),
    ]
