# Generated by Django 4.2.30 on 2026-08-01 20:46

import core.upload
import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0027_anexopedido_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='anexo_cotacao',
            field=models.FileField(blank=True, null=True, upload_to='cotacoes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'], message='Formato de arquivo inválido. Permitidos: PDF, DOC, DOCX, XLS, XLSX.')], verbose_name='Anexo da Cotação'),
        ),
        migrations.AlterField(
            model_name='entregaanexo',
            name='arquivo',
            field=models.FileField(upload_to=core.upload.UploadPath('suprimentos_entregas'), validators=[core.validators.SecureFileValidator(app_name='suprimentos_entregas')]),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_solic_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
