# Generated by Django 4.2.30 on 2026-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0028_alter_cotacao_anexo_cotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_obra',
            field=models.CharField(choices=[('CM', 'Contrato de Manutenção'), ('CR', 'Contrato de Reforma'), ('VE', 'Venda')], default='CM', max_length=2, verbose_name='Tipo de Obra'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='tipo_obra',
            field=models.CharField(choices=[('CM', 'Contrato de Manutenção'), ('CR', 'Contrato de Reforma'), ('VE', 'Venda')], max_length=2, verbose_name='Tipo de Obra'),
        ),
    ]
