# Generated by Django 5.2.16 on 2026-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0029_alter_pedido_tipo_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
