# Generated by Django 5.2.16 on 2026-09-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0030_alter_parceiro_inscricao_estadual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
