# Generated by Django 5.2.7 on 2025-10-02 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('lote', models.CharField(blank=True, max_length=100, verbose_name='Lote de Fabricação')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('data_entrega', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Recebimento')),
                ('assinatura_recebimento', models.TextField(blank=True, null=True, verbose_name='Assinatura de Recebimento (Base64)')),
                ('assinatura_imagem', models.ImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura (Arquivo)')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
            ],
            options={
                'verbose_name': 'Entrega de EPI',
                'verbose_name_plural': 'Entregas de EPI',
                'ordering': ['-criado_em'],
                'permissions': [('assinar_entregaepi', 'Pode assinar entrega de EPI')],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Descrição EPI')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('certificado_aprovacao', models.CharField(blank=True, help_text='Deixe em branco se não aplicável.', max_length=50, verbose_name='Certificado de Aprovação (CA)')),
                ('data_cadastro', models.DateField(auto_now_add=True, help_text='Data em que o equipamento foi cadastrado.', null=True, verbose_name='Data de Cadastro')),
                ('data_validade_ca', models.DateField(blank=True, null=True, verbose_name='Data de Validade do CA')),
                ('vida_util_dias', models.PositiveIntegerField(help_text='Vida útil em dias após a entrega, conforme fabricante.', verbose_name='Vida Útil (dias)')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('requer_numero_serie', models.BooleanField(default=False, help_text='Marque se cada item individual precisa ser rastreado.', verbose_name='Requer Rastreamento por Nº de Série?')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='epi_fotos/', verbose_name='Foto do Equipamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Equipamento (EPI)',
                'verbose_name_plural': 'Equipamentos (EPIs)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha de EPI',
                'verbose_name_plural': 'Fichas de EPI',
                'ordering': ['funcionario__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição das Atividades')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MatrizEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_padrao', models.PositiveIntegerField(default=1, verbose_name='Quantidade Padrão')),
                ('frequencia_troca_meses', models.PositiveIntegerField(blank=True, help_text="Deixe em branco para 'Quando Necessário' (QN).", null=True, verbose_name='Frequência de Troca (Meses)')),
            ],
            options={
                'verbose_name': 'Matriz de EPI por Função',
                'verbose_name_plural': 'Matrizes de EPI por Função',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=7)),
                ('quantidade', models.IntegerField()),
                ('lote', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('data_validade_fabricante', models.DateField(blank=True, null=True, verbose_name='Validade do Produto (Fabricante)')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Unitário')),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('justificativa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
    ]
