# Generated by Django 5.2.16 on 2026-09-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '00XX_add_estoque_atual'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipamento',
            name='equipamento_unico_constraint',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='estoque_atual',
            field=models.PositiveIntegerField(default=0, help_text='Saldo atual em estoque, atualizado automaticamente pelas movimentações.'),
        ),
    ]
