# Generated by Django 5.2 on 2025-07-02 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Equipamento')),
                ('certificado_aprovacao', models.CharField(max_length=50, unique=True, verbose_name='Certificado de Aprovação (CA)')),
                ('vida_util_dias', models.PositiveIntegerField(help_text='Vida útil em dias após a entrega, conforme fabricante.', verbose_name='Vida Útil (dias)')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Equipamento (EPI)',
                'verbose_name_plural': 'Equipamentos (EPIs)',
                'db_table': 'equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição das Atividades')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'db_table': 'funcao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_epi', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.funcao', verbose_name='Função na Ficha')),
            ],
            options={
                'verbose_name': 'Ficha de EPI',
                'verbose_name_plural': 'Fichas de EPI',
                'db_table': 'fichaepi',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrega')),
                ('assinatura_recebimento', models.TextField(blank=True, verbose_name='Assinatura de Recebimento (Base64)')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('assinatura_devolucao', models.TextField(blank=True, verbose_name='Assinatura de Devolução (Base64)')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.equipamento')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='seguranca_trabalho.fichaepi')),
            ],
            options={
                'verbose_name': 'Entrega de EPI',
                'verbose_name_plural': 'Entregas de EPI',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('justificativa', models.CharField(max_length=255)),
                ('entrega_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.entregaepi')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='seguranca_trabalho.equipamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'movimentacaoestoque',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MatrizEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_padrao', models.PositiveIntegerField(default=1, verbose_name='Quantidade Padrão')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_funcoes', to='seguranca_trabalho.equipamento')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_epis', to='seguranca_trabalho.funcao')),
            ],
            options={
                'verbose_name': 'Matriz de EPI por Função',
                'verbose_name_plural': 'Matrizes de EPI por Função',
                'db_table': 'matrizepi',
                'unique_together': {('funcao', 'equipamento')},
            },
        ),
    ]
