# Generated by Django 5.2.16 on 2026-09-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_add_estoque_atual'),
        ('suprimentos', '0031_alter_parceiro_contato_alter_parceiro_telefone'),
        ('usuario', '0003_padroniza_nomes_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='estoque_atual',
            field=models.IntegerField(
                default=0,
                editable=False,
                help_text='Atualizado automaticamente pelas movimentações.',
                verbose_name='Estoque Atual',
            ),
        ),
        # ── Constraint JÁ EXISTE fisicamente no banco (confirmado via
        #    SHOW CREATE TABLE). Sincroniza apenas o state do Django. ──
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='equipamento',
                    constraint=models.UniqueConstraint(
                        fields=('fabricante', 'modelo', 'certificado_aprovacao'),
                        name='equipamento_unico_constraint',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]

