# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0002_initial'),
        ('seguranca_trabalho', '0001_initial'),
        ('suprimentos', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epis_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebedor'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.ForeignKey(limit_choices_to={'eh_fabricante': True}, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_fabricados', to='suprimentos.parceiro'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.equipamento', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_epi', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='seguranca_trabalho.fichaepi'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcoes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='cargofuncao',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_cargo', to='seguranca_trabalho.funcao', verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='matrizepi',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_funcoes', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AddField(
            model_name='matrizepi',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrizepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='matrizepi',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_epis', to='seguranca_trabalho.funcao'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='entrega_associada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.entregaepi'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacaoestoques', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'eh_fornecedor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_por_fornecedor', to='suprimentos.parceiro'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('fabricante', 'modelo', 'certificado_aprovacao'), name='equipamento_unico_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='cargofuncao',
            unique_together={('cargo', 'funcao')},
        ),
        migrations.AlterUniqueTogether(
            name='matrizepi',
            unique_together={('funcao', 'equipamento')},
        ),
    ]
