# Generated by Django 5.2 on 2025-09-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0001_initial'),
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='contato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabricantes', to='logradouro.logradouro', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='logradouro.logradouro', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site'),
        ),
    ]
