# Generated by Django 5.2 on 2025-07-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Fabricante')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'db_table': 'fabricante',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedor',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='lote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lote de Fabricação'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Preencher se o equipamento exigir rastreamento individual.', max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_validade_ca',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade do CA'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='epi_fotos/', verbose_name='Foto do Equipamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='requer_numero_serie',
            field=models.BooleanField(default=False, help_text='Marque se cada item individual precisa ser rastreado (ex: cinto de segurança).', verbose_name='Requer Rastreamento por Nº de Série?'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Unitário'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='data_validade_fabricante',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Produto (Fabricante)'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='lote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='certificado_aprovacao',
            field=models.CharField(help_text='Deixe em branco se não aplicável.', max_length=50, verbose_name='Certificado de Aprovação (CA)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='entrega_associada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.entregaepi'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=7),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='seguranca_trabalho.fabricante'),
        ),
        migrations.AlterUniqueTogether(
            name='equipamento',
            unique_together={('fabricante', 'modelo', 'certificado_aprovacao')},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fornecedor_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_fornecidos', to='seguranca_trabalho.fornecedor', verbose_name='Fornecedor Padrão'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.fornecedor'),
        ),
    ]
