# Generated by Django 5.2 on 2025-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='assinatura_final_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas_finais/', verbose_name='Imagem da Assinatura Final'),
        ),
    ]
