# Generated by Django 5.2 on 2025-06-02 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIEquipamentoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(error_messages={'max_length': 'O nome não pode exceder 100 caracteres', 'required': 'Este campo é obrigatório'}, help_text='Nome completo do equipamento', max_length=100, verbose_name='Nome do Equipamento')),
                ('tipo', models.CharField(choices=[('EPI', 'Equipamento de Proteção Individual'), ('EPC', 'Equipamento de Proteção Coletiva'), ('INC', 'Incêndio'), ('SOC', 'Socorro'), ('OUT', 'Outros')], default='EPI', max_length=3, verbose_name='Tipo de Equipamento')),
                ('codigo_ca', models.CharField(db_column='codigo_CA', error_messages={'invalid': 'Formato inválido para código CA', 'unique': 'Já existe um equipamento com este código CA'}, help_text='Código de aprovação no formato AA-1234', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato do CA deve ser AA-1234 (ex: AB-1234)', regex='^[A-Z]{2}-\\d{4}$')], verbose_name='Código CA')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do equipamento', null=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, error_messages={'invalid': 'Digite um número válido', 'min_value': 'O valor não pode ser negativo'}, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, help_text='Quantidade mínima para alerta de reposição', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Estoque Mínimo')),
                ('data_validade', models.DateField(blank=True, help_text='Validade do certificado de aprovação', null=True, verbose_name='Data de Validade')),
                ('ativo', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Equipamento de Segurança',
                'verbose_name_plural': 'Equipamentos de Segurança',
                'db_table': 'epi_equipamentoseguranca',
                'ordering': ['tipo', 'nome_equipamento'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='itemequipamentoseguranca',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguranca_trabalho.epiequipamentoseguranca', verbose_name='Equipamento'),
        ),
        migrations.DeleteModel(
            name='EquipamentosSeguranca',
        ),
    ]
