# Generated by Django 5.2 on 2025-07-05 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0002_initial'),
        ('seguranca_trabalho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaepi',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_epi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_epi', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='seguranca_trabalho.fichaepi'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fornecedor_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.fornecedor', verbose_name='Fornecedor Padrão'),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.funcao'),
        ),
        migrations.AddField(
            model_name='matrizepi',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_funcoes', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AddField(
            model_name='matrizepi',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_epis', to='seguranca_trabalho.funcao'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='entrega_associada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.entregaepi'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('fabricante', 'modelo', 'certificado_aprovacao'), name='equipamento_unico_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='matrizepi',
            unique_together={('funcao', 'equipamento')},
        ),
    ]
