# Generated by Django 5.2 on 2025-08-06 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabricantes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcoes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='matrizepi',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrizepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacaoestoques', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
