# Generated by Django 5.1.6 on 2025-03-16 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaepi',
            name='assinatura_colaborador',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assinaturas/'),
            preserve_default=False,
        ),
    ]
