# Generated by Django 5.2 on 2025-10-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0002_initial'),
        ('seguranca_trabalho', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_funcoes', to='departamento_pessoal.cargo', verbose_name='Cargo')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_cargo', to='seguranca_trabalho.funcao', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo e Função Associados',
                'verbose_name_plural': 'Cargos e Funções Associados',
                'unique_together': {('cargo', 'funcao')},
            },
        ),
    ]
