# Generated by Django 5.2 on 2025-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0002_fabricante_contato_fabricante_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
    ]
