# Generated by Django 5.2 on 2026-02-24 20:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0003_alter_documento_funcionario_alter_funcionario_funcao'),
        ('seguranca_trabalho', '0002_initial'),
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargofuncao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargofuncao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_funcoes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_entrega',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcoes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Função'),
        ),
        migrations.AlterField(
            model_name='matrizepi',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrizepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacaoestoques', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterUniqueTogether(
            name='cargofuncao',
            unique_together={('cargo', 'funcao', 'filial')},
        ),
        migrations.AddConstraint(
            model_name='funcao',
            constraint=models.UniqueConstraint(fields=('nome', 'filial'), name='unique_funcao_por_filial'),
        ),
    ]
