# Generated by Django 5.2 on 2025-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0002_entregaepi_filial_equipamento_filial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
    ]
