# Generated by Django 5.2.16 on 2026-09-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0002_alter_equipamento_estoque_atual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaepi',
            options={'ordering': ['-criado_em'], 'permissions': [('assinar_entregaepi', 'Pode assinar entrega de EPI'), ('registrar_devolucao_entregaepi', 'Pode registrar devolução de EPI')], 'verbose_name': 'Entrega de EPI', 'verbose_name_plural': 'Entregas de EPI'},
        ),
    ]
