# Generated by Django 5.2 on 2025-07-10 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaepi',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Entrega de EPI', 'verbose_name_plural': 'Entregas de EPI'},
        ),
        migrations.RemoveField(
            model_name='fichaepi',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='assinatura_recebimento',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura (Base64)'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrega Efetiva'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.equipamento', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='data_admissao',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.funcao', verbose_name='Função na Admissão'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterModelTable(
            name='equipamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fichaepi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='funcao',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matrizepi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movimentacaoestoque',
            table=None,
        ),
    ]
