# Generated by Django 5.2.16 on 2026-09-24 16:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0003_alter_entregaepi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaepi',
            name='assinatura_recebimento',
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='assinatura_imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_assinatura),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='ip_assinatura',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
