# Generated by Django 5.2 on 2025-07-10 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0003_alter_entregaepi_options_remove_fichaepi_colaborador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recebedor'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='assinatura_recebimento',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura de Recebimento'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Descrição EPI'),
        ),
    ]
