# Generated by Django 5.2 on 2026-02-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0004_entregaepi_assinatura_funcionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaepi',
            name='assinatura_funcionario',
        ),
        migrations.RemoveField(
            model_name='entregaepi',
            name='data_assinatura_termo',
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='assinatura_funcionario',
            field=models.TextField(blank=True, help_text='Assinatura digital (base64) do funcionário no termo', null=True, verbose_name='Assinatura do Funcionário'),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='data_assinatura_termo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura do Termo'),
        ),
    ]
