# Generated by Django 5.2.16 on 2026-09-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0004_remove_entregaepi_assinatura_recebimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['nome'], 'permissions': [('view_dashboard', 'Pode visualizar o Dashboard de SST'), ('download_relatorio', 'Pode baixar relatórios de SST'), ('view_all_seguranca_trabalho', 'Pode ver todos os dados de SST (todas as filiais/técnicos)')], 'verbose_name': 'Equipamento (EPI)', 'verbose_name_plural': 'Equipamentos (EPIs)'},
        ),
    ]
