# Generated by Django 5.2 on 2025-09-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0004_alter_fabricante_filial_alter_fornecedor_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricante',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='filial',
        ),
    ]
