# Generated by Django 5.2 on 2025-09-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0005_remove_fabricante_filial_remove_fornecedor_filial'),
        ('usuario', '0004_groupcardpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabricantes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
