# Generated by Django 5.2 on 2025-09-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0006_fabricante_filial_fornecedor_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricante',
            name='endereco',
        ),
    ]
