# Generated by Django 4.2.16 on 2026-03-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0006_alterar_entrega_associada_para_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='estoque_atual',
            field=models.IntegerField(default=0, editable=False, help_text='Atualizado automaticamente pelas movimentações.', verbose_name='Estoque Atual'),
        ),
    ]
