# Generated by Django 5.2 on 2025-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0007_remove_fabricante_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, help_text='Data em que o equipamento foi cadastrado no sistema.', null=True, verbose_name='Data de Cadastro'),
        ),
    ]
