# Generated by Django 4.2.16 on 2026-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0007_adicionar_estoque_atual_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='registro',
            field=models.PositiveIntegerField(default=0, verbose_name='Registro da Função'),
        ),
    ]
