# Generated by Django 5.2 on 2025-09-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0008_equipamento_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaepi',
            options={'ordering': ['-criado_em'], 'permissions': [('assinar_entregaepi', 'Pode assinar entrega de EPI')], 'verbose_name': 'Entrega de EPI', 'verbose_name_plural': 'Entregas de EPI'},
        ),
    ]
