# Generated by Django 4.2.28 on 2026-05-09 15:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0009_alter_anexopedido_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguranca_trabalho', '0008_funcao_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.ForeignKey(limit_choices_to={'eh_fabricante': True}, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_fabricados', to='suprimentos.parceiro', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='assinatura_funcionario',
            field=models.TextField(blank=True, help_text='Assinatura digital (base64) do funcionário no termo.', null=True, verbose_name='Assinatura do Funcionário'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='entrega_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='seguranca_trabalho.entregaepi', verbose_name='Entrega Associada'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='seguranca_trabalho.equipamento', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'eh_fornecedor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_por_fornecedor', to='suprimentos.parceiro', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='justificativa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=7, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['ficha', '-criado_em'], name='seguranca_t_ficha_i_6fa17c_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['equipamento', '-data_entrega'], name='seguranca_t_equipam_b3fcb3_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['filial', '-criado_em'], name='seguranca_t_filial__6f23fa_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['filial', 'ativo'], name='seguranca_t_filial__5030bf_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['nome'], name='seguranca_t_nome_3072b2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['equipamento', '-data'], name='seguranca_t_equipam_eb39e5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['filial', '-data'], name='seguranca_t_filial__7fca81_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', '-data'], name='seguranca_t_tipo_475e49_idx'),
        ),
    ]
