# Generated by Django 5.2 on 2025-09-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0009_alter_entregaepi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='fornecedor_padrao',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
