# Generated by Django 5.2.16 on 2026-09-21 15:02

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0010_movimentacaoestoque_pedido_compra_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaepi',
            name='assinatura_imagem',
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='assinatura_recebimento',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Assinatura de Recebimento')),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='assinatura_funcionario',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Assinatura do Funcionário')),
        ),
    ]
