# Generated by Django 5.2 on 2025-09-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0010_remove_equipamento_fornecedor_padrao_and_more'),
        ('usuario', '0004_groupcardpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaepi',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichaepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcoes', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='matrizepi',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrizepis', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacaoestoques', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
