# Generated by Django 5.2.16 on 2026-09-21 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0011_remove_entregaepi_assinatura_imagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaepi',
            options={'ordering': ['funcionario__nome_completo'], 'permissions': [('view_dados_sensiveis_ficha', 'Pode visualizar assinaturas e dados sensíveis')], 'verbose_name': 'Ficha de EPI', 'verbose_name_plural': 'Fichas de EPI'},
        ),
        migrations.CreateModel(
            name='LogAcessoDadosSensiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguranca_trabalho.fichaepi')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
