# Generated by Django 5.2 on 2025-09-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0011_alter_entregaepi_filial_alter_fichaepi_filial_and_more'),
        ('usuario', '0004_groupcardpermissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaepi',
            options={'ordering': ['funcionario__nome_completo'], 'verbose_name': 'Ficha de EPI', 'verbose_name_plural': 'Fichas de EPI'},
        ),
        migrations.RemoveField(
            model_name='fichaepi',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='fichaepi',
            name='funcao',
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='assinatura_recebimento',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura de Recebimento (Base64)'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epis_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebedor'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, help_text='Data em que o equipamento foi cadastrado.', null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
