# Generated by Django 5.2.16 on 2026-09-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0012_alter_fichaepi_options_logacessodadossensiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='consentimento_lgpd_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimento registrado em'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='consentimento_lgpd_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do consentimento'),
        ),
    ]
