# Generated by Django 5.2.16 on 2026-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0013_entregaepi_consentimento_lgpd_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaepi',
            name='consentimento_lgpd_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimento registrado em'),
        ),
        migrations.AddField(
            model_name='fichaepi',
            name='consentimento_lgpd_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do consentimento'),
        ),
    ]
