# Generated by Django 5.2 on 2025-10-14 23:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('data_hora_agenda', models.DateTimeField()),
                ('data_hora_devolucao', models.DateTimeField()),
                ('cm', models.CharField(max_length=4, verbose_name='CM/Contrato')),
                ('descricao', models.TextField()),
                ('pedagio', models.BooleanField(default=False)),
                ('abastecimento', models.BooleanField(default=False)),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='agendamentos/')),
                ('assinatura', models.TextField(blank=True, null=True, verbose_name='Assinatura Digital')),
                ('responsavel', models.CharField(max_length=100)),
                ('ocorrencia', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('cancelar_agenda', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agendamento',
                'ordering': ['-data_hora_agenda'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('ano', models.PositiveIntegerField()),
                ('renavan', models.CharField(max_length=20, unique=True)),
                ('quilometragem', models.PositiveIntegerField(default=0, verbose_name='Quilometragem')),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('data_proxima_manutencao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carros/fotos/', verbose_name='Foto do Carro')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'db_table': 'carro',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('saida', 'Saída'), ('retorno', 'Retorno'), ('vistoria', 'Vistoria')], max_length=20)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('revisao_frontal_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_frontal', models.ImageField(upload_to='checklist/frontal/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('revisao_trazeira_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_trazeira', models.ImageField(upload_to='checklist/trazeira/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('revisao_lado_motorista_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_lado_motorista', models.ImageField(upload_to='checklist/lado_motorista/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('revisao_lado_passageiro_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_lado_passageiro', models.ImageField(upload_to='checklist/lado_passageiro/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('anexo_ocorrencia', models.TextField(blank=True, null=True)),
                ('assinatura', models.TextField(blank=True, null=True, verbose_name='Assinatura Digital')),
                ('confirmacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'db_table': 'checklist',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'foto',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
