# Generated by Django 5.2 on 2025-07-16 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_hora_agenda'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['marca', 'modelo'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('agendamento', 'tipo')},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='automovel.carro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cm',
            field=models.CharField(max_length=20, verbose_name='Centro de Custo/Motorista'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='data_criacao',
        ),
    ]
