# Generated by Django 5.2 on 2025-10-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foto',
            unique_together={('agendamento', 'imagem')},
        ),
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamento',
        ),
        migrations.AlterModelTable(
            name='carro',
            table='carro',
        ),
        migrations.AlterModelTable(
            name='checklist',
            table='checklist',
        ),
        migrations.AlterModelTable(
            name='foto',
            table='foto',
        ),
    ]
