# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carro',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='automovel.carro'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='automovel.agendamento'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_agendamento', to='automovel.agendamento'),
        ),
        migrations.AddField(
            model_name='foto',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='usuario.filial'),
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('agendamento', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='foto',
            unique_together={('agendamento', 'imagem')},
        ),
    ]
