# Generated by Django 5.1.6 on 2025-04-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0001_initial'),
    ]

    operations = [
    ]
