# Generated by Django 5.2 on 2025-10-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='anexo_ocorrencia',
        ),
    ]
