# Generated by Django 5.2 on 2025-08-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_alter_agendamento_options'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_hora_agenda'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='carro',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='foto',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='usuario.filial'),
        ),
    ]
