# Generated by Django 5.1.6 on 2025-04-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0003_auto_20250405_1801'),
    ]

    operations = [
    ]
