# Generated by Django 5.2 on 2025-11-21 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0003_remove_checklist_anexo_ocorrencia'),
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Carro_agendamento',
        ),
        migrations.RenameModel(
            old_name='Checklist',
            new_name='Carro_checklist',
        ),
        migrations.RenameModel(
            old_name='Foto',
            new_name='Carro_foto',
        ),
        migrations.AlterModelTable(
            name='carro_checklist',
            table='Carro_checklist',
        ),
        migrations.AlterModelTable(
            name='carro_foto',
            table='Carro_foto',
        ),
    ]
