# Generated by Django 5.2 on 2025-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0003_alter_agendamento_options_alter_foto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='carros/fotos/', verbose_name='Foto do Carro'),
        ),
    ]
