# Generated by Django 5.2 on 2025-11-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0004_rename_agendamento_carro_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carro_agendamento',
            table='carro_agendamento',
        ),
        migrations.AlterModelTable(
            name='carro_checklist',
            table='carro_checklist',
        ),
        migrations.AlterModelTable(
            name='carro_foto',
            table='carro_foto',
        ),
    ]
