# Generated by Django 5.1.6 on 2025-04-07 00:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0004_auto_20250405_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa', models.CharField(blank=True, default='', max_length=10)),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('cor', models.CharField(blank=True, default='', max_length=30)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('renavan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_ultima_manutencao', models.DateField()),
                ('data_proxima_manutencao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('data_hora_agenda', models.DateTimeField()),
                ('data_hora_devolucao', models.DateTimeField()),
                ('cm', models.CharField(max_length=20, verbose_name='CM')),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='agendamentos/')),
                ('assinatura', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('cancelar_agenda', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='automovel.carro')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'automovel_agendamento',
                'ordering': ['-data_hora_agenda'],
                'indexes': [models.Index(fields=['data_hora_agenda'], name='idx_data_agenda'), models.Index(fields=['carro'], name='idx_agendamento_carro')],
            },
        ),
    ]
