# Generated by Django 5.2 on 2025-05-09 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('saida', 'Saída'), ('retorno', 'Retorno')], max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                #('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('revisao_frontal_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_frontal', models.ImageField(upload_to='checklists/')),
                ('revisao_trazeira_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_trazeira', models.ImageField(upload_to='checklists/')),
                ('revisao_lado_motorista_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_lado_motorista', models.ImageField(upload_to='checklists/')),
                ('revisao_lado_passageiro_status', models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado'), ('nao_aplicavel', 'Não Aplicável')], max_length=15)),
                ('foto_lado_passageiro', models.ImageField(upload_to='checklists/')),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('anexo_ocorrencia', models.TextField(blank=True, null=True)),
                ('assinatura', models.TextField(blank=True, null=True, verbose_name='Assinatura Digital')),
                ('confirmacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
            },
        ),
        migrations.RemoveField(
            model_name='checklist_form',
            name='agendamento',
        ),
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='carro',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='idx_data_agenda',
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='idx_agendamento_carro',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='fotos',
            new_name='foto_principal',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='abastecimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='ocorrencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pedagio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='carro',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cancelar_agenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automovel.carro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carro',
            name='data_proxima_manutencao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='data_ultima_manutencao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='renavan',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='automovel.agendamento'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='agendamento',
            table=None,
        ),
        migrations.AddField(
            model_name='checklist',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='automovel.agendamento'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Checklist_form',
        ),
    ]
