# Generated by Django 5.2 on 2025-11-21 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0005_alter_carro_agendamento_table_and_more'),
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro_agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('manutencao', 'Em Manutenção'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
        migrations.CreateModel(
            name='Carro_rastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('endereco_aproximado', models.TextField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rastreamentos', to='automovel.carro_agendamento')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='usuario.filial')),
            ],
            options={
                'verbose_name': 'Rastreamento',
                'verbose_name_plural': 'Rastreamentos',
                'db_table': 'carro_rastreamento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
