# Generated by Django 5.2 on 2025-11-21 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0006_alter_carro_agendamento_status_carro_rastreamento'),
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro_manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField()),
                ('data_agendamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('pneu', 'Troca de Pneus'), ('oleo', 'Troca de Óleo'), ('freio', 'Sistema de Freio'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='automovel.carro')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='usuario.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'db_table': 'carro_manutencao',
                'ordering': ['-data_manutencao'],
            },
        ),
    ]
