# Generated by Django 5.2 on 2025-05-11 16:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0006_checklist_remove_checklist_form_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='assinatura',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura Digital'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_devolucao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='foto_frontal',
            field=models.ImageField(upload_to='checklist/frontal/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='foto_lado_motorista',
            field=models.ImageField(upload_to='checklist/lado_motorista/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='foto_lado_passageiro',
            field=models.ImageField(upload_to='checklist/lado_passageiro/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='foto_trazeira',
            field=models.ImageField(upload_to='checklist/trazeira/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='tipo',
            field=models.CharField(choices=[('saida', 'Saída'), ('retorno', 'Retorno'), ('vistoria', 'Vistoria')], max_length=20),
        ),
    ]
