# Generated by Django 5.2.13 on 2026-04-13 14:08

import core.upload
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0007_carro_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagem JPG, PNG ou WebP (máx. 4 MB).', null=True, upload_to=core.upload.UploadPath('automovel_foto'), validators=[core.validators.SecureImageValidator(app_name='automovel_foto')], verbose_name='Foto do Carro'),
        ),
        migrations.AlterField(
            model_name='carro_agendamento',
            name='foto_principal',
            field=models.ImageField(blank=True, help_text='Imagem JPG, PNG ou WebP (máx. 5 MB).', null=True, upload_to=core.upload.UploadPath('automovel_agendamento'), validators=[core.validators.SecureImageValidator(app_name='automovel_agendamento')], verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='carro_checklist',
            name='foto_frontal',
            field=models.ImageField(help_text='Imagem JPG, PNG ou WebP (máx. 5 MB).', upload_to=core.upload.UploadPath('automovel_checklist'), validators=[core.validators.SecureImageValidator(app_name='automovel_checklist')], verbose_name='Foto Frontal'),
        ),
        migrations.AlterField(
            model_name='carro_checklist',
            name='foto_lado_motorista',
            field=models.ImageField(help_text='Imagem JPG, PNG ou WebP (máx. 5 MB).', upload_to=core.upload.UploadPath('automovel_checklist'), validators=[core.validators.SecureImageValidator(app_name='automovel_checklist')], verbose_name='Foto Lado Motorista'),
        ),
        migrations.AlterField(
            model_name='carro_checklist',
            name='foto_lado_passageiro',
            field=models.ImageField(help_text='Imagem JPG, PNG ou WebP (máx. 5 MB).', upload_to=core.upload.UploadPath('automovel_checklist'), validators=[core.validators.SecureImageValidator(app_name='automovel_checklist')], verbose_name='Foto Lado Passageiro'),
        ),
        migrations.AlterField(
            model_name='carro_checklist',
            name='foto_trazeira',
            field=models.ImageField(help_text='Imagem JPG, PNG ou WebP (máx. 5 MB).', upload_to=core.upload.UploadPath('automovel_checklist'), validators=[core.validators.SecureImageValidator(app_name='automovel_checklist')], verbose_name='Foto Traseira'),
        ),
        migrations.AlterField(
            model_name='carro_foto',
            name='imagem',
            field=models.ImageField(help_text='Imagem JPG, PNG ou WebP (máx. 5 MB).', upload_to=core.upload.UploadPath('automovel_foto_agendamento'), validators=[core.validators.SecureImageValidator(app_name='automovel_foto_agendamento')], verbose_name='Foto'),
        ),
    ]
