# Generated by Django 5.2.13 on 2026-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0008_alter_carro_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['marca', 'modelo'], 'permissions': [('view_all_automovel', 'Pode ver todos os registros de automóveis da filial')], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
