# Generated by Django 5.2.13 on 2026-04-27 19:04

# automovel/migrations/0010_carro_agendamento_tracking_token.py
"""
Migration em 3 passos para adicionar tracking_token único:

1. AddField nullable, sem unique  → coluna é criada vazia
2. RunPython gera UUID único por linha existente
3. AlterField aplica unique=True + not null + default=uuid.uuid4

Funciona com banco vazio OU populado, idempotente, reversível.
"""

import uuid
from django.db import migrations, models


def populate_tracking_tokens(apps, schema_editor):
    """Gera UUID único para cada agendamento existente."""
    Carro_agendamento = apps.get_model("automovel", "Carro_agendamento")
    for ag in Carro_agendamento.objects.filter(tracking_token__isnull=True):
        ag.tracking_token = uuid.uuid4()
        ag.save(update_fields=["tracking_token"])


def reverse_noop(apps, schema_editor):
    """Reverso: não há nada para fazer (o AlterField reverso cuida da coluna)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("automovel", "0009_alter_carro_options"),
    ]

    operations = [
        # ── Passo 1: adiciona coluna nullable, sem unique ──
        migrations.AddField(
            model_name="carro_agendamento",
            name="tracking_token",
            field=models.UUIDField(
                null=True,
                editable=False,
                verbose_name="Token de Rastreamento",
            ),
        ),
        # ── Passo 2: preenche UUIDs únicos para linhas existentes ──
        migrations.RunPython(populate_tracking_tokens, reverse_noop),
        # ── Passo 3: aplica constraints finais (unique + not null + default) ──
        migrations.AlterField(
            model_name="carro_agendamento",
            name="tracking_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                db_index=True,
                help_text=(
                    "Token secreto entregue ao rastreador físico. "
                    "Enviado em cada POST via header Authorization: Bearer <token>."
                ),
                verbose_name="Token de Rastreamento",
            ),
        ),
    ]
