[pytest]
DJANGO_SETTINGS_MODULE = gerenciandoTarefas.settings_test
python_files = tests.py test_*.py
addopts = --reuse-db --ignore=usuario/tests/test_email.py
testpaths = core ferramentas notifications suprimentos usuario


