# Generated by Django 5.2 on 2025-10-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('suprimentos', '0002_alter_parceiro_filial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
