# Generated by Django 5.2.16 on 2026-09-24 23:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenassinaturaremota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.AlterField(
            model_name='tokenassinaturaremota',
            name='expira_em',
            field=models.DateTimeField(default=core.models.default_expira_em),
        ),
    ]
