# Generated by Django 5.2 on 2025-08-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filial_delete_ferramenta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filial',
            table='core_filial',
        ),
    ]
