# Generated by Django 5.2.16 on 2026-09-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_basemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenassinaturaremota',
            name='ip_utilizacao',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
