# Generated by Django 5.2 on 2025-11-17 01:59

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to=documentos.models.private_document_path)),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('A_VENCER', 'A Vencer'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado/Inativo')], default='VIGENTE', max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_responsaveis', to=settings.AUTH_USER_MODEL)),
                ('substitui', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituto', to='documentos.documento')),
            ],
        ),
    ]
