# Generated by Django 5.2 on 2025-11-19 16:21

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documentos', '0001_initial'),
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['data_vencimento'], 'permissions': [('pode_gerenciar_todos_documentos', 'Pode gerenciar documentos de todas as filiais'), ('pode_validar_documento', 'Pode validar um documento enviado')], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='documento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_filial', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='O ficheiro será armazenado em local seguro.', upload_to=documentos.models.private_document_path, verbose_name='Ficheiro'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Objeto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Deixe em branco se o documento não tiver vencimento.', null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID do Objeto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('A_VENCER', 'A Vencer'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado/Inativo')], default='VIGENTE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='substitui',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituto', to='documentos.documento', verbose_name='Substitui o Documento'),
        ),
    ]
