# Generated by Django 4.2.16 on 2026-03-05 17:58

import django.core.files.storage
from django.db import migrations, models
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_options_documento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='O arquivo será armazenado em local seguro.', storage=django.core.files.storage.FileSystemStorage(base_url='/private/', location='C:\\Users\\esgce\\Documents\\GitHub\\ControleTarefas\\private_media'), upload_to=documentos.models.private_document_path, verbose_name='Arquivo'),
        ),
    ]
