# Generated by Django 4.2.16 on 2026-03-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_filial_alter_cliente_logradouro_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0003_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cliente', to='cliente.cliente', verbose_name='Cliente Relacionado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição/Observações'),
        ),
        migrations.AddField(
            model_name='documento',
            name='dias_aviso',
            field=models.PositiveIntegerField(default=30, help_text='Dias de antecedência para notificar vencimento.', verbose_name='Avisar dias antes'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato'), ('ALVARA', 'Alvará'), ('CERTIDAO', 'Certidão'), ('FATURA', 'Fatura/Nota Fiscal'), ('RELATORIO', 'Relatório'), ('ART', 'ART'), ('PGR', 'PGR'), ('LAUDO', 'Laudo'), ('CERTIFICADO', 'Certificado'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Objeto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('A_VENCER', 'A Vencer'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado/Inativo'), ('ARQUIVADO', 'Arquivado')], default='VIGENTE', max_length=10, verbose_name='Status'),
        ),
    ]
