# Generated by Django 4.2.28 on 2026-04-07 23:34

from django.db import migrations, models
import documentos.models
import documentos.storage


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_migrate_arquivos_to_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='O arquivo será armazenado em local seguro.', storage=documentos.storage.PrivateMediaStorage(), upload_to=documentos.models.private_document_path, verbose_name='Arquivo'),
        ),
    ]
