# Generated by Django 5.2.13 on 2026-04-14 16:20

import core.validators
import documentos.models
import documentos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='O arquivo será armazenado em local seguro.', storage=documentos.storage.PrivateMediaStorage(), upload_to=documentos.models.private_document_path, validators=[core.validators.SecureFileValidator(app_name='documentos')], verbose_name='Arquivo'),
        ),
    ]
