# Generated by Django 5.2.13 on 2026-04-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['data_vencimento'], 'permissions': [('pode_validar_documento', 'Pode validar um documento enviado')], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
