# Generated by Django 5.2.13 on 2026-04-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_alter_documento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['data_vencimento'], 'permissions': [('pode_validar_documento', 'Pode validar um documento enviado'), ('pode_gerenciar_todos_documentos', 'Pode gerenciar documentos de todas as filiais')], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
