# Generated by Django 4.2.16 on 2026-03-21 21:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código CFOP')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1, verbose_name='Tipo')),
                ('aplicacao', models.TextField(blank=True, default='', help_text='Quando usar este CFOP', verbose_name='Aplicação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOPs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ICMS', 'CST ICMS — Regime Normal'), ('IPI_E', 'CST IPI — Entrada'), ('IPI_S', 'CST IPI — Saída'), ('PIS', 'CST PIS'), ('COFINS', 'CST COFINS')], max_length=6, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'CST',
                'verbose_name_plural': 'CSTs',
                'ordering': ['tipo', 'codigo'],
                'unique_together': {('tipo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='GrupoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Material Elétrico — Entrada SP', max_length=200, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('natureza', models.CharField(choices=[('E', 'Entrada (Compra)'), ('S', 'Saída (Venda/Remessa)')], default='E', max_length=1, verbose_name='Natureza')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cfop', models.ForeignKey(help_text='CFOP padrão para este grupo', on_delete=django.db.models.deletion.PROTECT, to='tributacao.cfop', verbose_name='CFOP padrão')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_tributarios', to='usuario.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Grupo Tributário',
                'verbose_name_plural': 'Grupos Tributários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Formato: 0000.00.00 — Ex: 8544.49.00', max_length=10, unique=True, verbose_name='Código NCM')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('ex_tipi', models.CharField(blank=True, default='', help_text='Exceção da TIPI, se houver', max_length=3, verbose_name='Exceção TIPI')),
                ('aliquota_ipi_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota IPI da TIPI — pode ser sobrescrita no Grupo Tributário', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota IPI padrão (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCMs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TributacaoFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota IPI (%)')),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=1.65, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota PIS (%)')),
                ('gera_credito_pis', models.BooleanField(default=True, help_text='Lucro Real não-cumulativo: insumos para serviço geram crédito', verbose_name='Gera crédito de PIS?')),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=7.6, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota COFINS (%)')),
                ('gera_credito_cofins', models.BooleanField(default=True, help_text='Lucro Real não-cumulativo: insumos para serviço geram crédito', verbose_name='Gera crédito de COFINS?')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('cst_cofins', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'COFINS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tributacao.cst', verbose_name='CST COFINS')),
                ('cst_ipi', models.ForeignKey(blank=True, limit_choices_to={'tipo__startswith': 'IPI'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tributacao.cst', verbose_name='CST IPI')),
                ('cst_pis', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PIS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tributacao.cst', verbose_name='CST PIS')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tributacao_federal', to='tributacao.grupotributario', verbose_name='Grupo Tributário')),
            ],
            options={
                'verbose_name': 'Tributação Federal',
                'verbose_name_plural': 'Tributações Federais',
            },
        ),
        migrations.AddField(
            model_name='grupotributario',
            name='ncm',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio se o grupo for genérico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tributacao.ncm', verbose_name='NCM padrão'),
        ),
        migrations.CreateModel(
            name='TributacaoEstadual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_origem', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], help_text='Estado do fornecedor', max_length=2, verbose_name='UF Origem')),
                ('uf_destino', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], help_text='Estado da filial (destino da compra)', max_length=2, verbose_name='UF Destino')),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=0, help_text='Interna: 18% (SP), 17% (maioria). Interestadual: 7% ou 12%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota ICMS (%)')),
                ('reducao_base_icms', models.DecimalField(decimal_places=2, default=0, help_text='Alguns produtos têm base de cálculo reduzida', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Redução de Base ICMS (%)')),
                ('permite_credito', models.BooleanField(default=False, help_text='Material para uso/consumo em serviço: geralmente NÃO permite crédito. Verifique a legislação do estado.', verbose_name='Permite crédito de ICMS?')),
                ('tem_st', models.BooleanField(default=False, verbose_name='Tem ICMS-ST?')),
                ('mva', models.DecimalField(decimal_places=2, default=0, help_text='Margem de Valor Agregado para ST', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MVA (%)')),
                ('aliquota_icms_st', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota ICMS-ST (%)')),
                ('aliquota_fcp', models.DecimalField(decimal_places=2, default=0, help_text='Fundo de Combate à Pobreza — varia por UF (0% a 4%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota FCP (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('cst_icms', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'ICMS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tributacao.cst', verbose_name='CST ICMS')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributacoes_estaduais', to='tributacao.grupotributario', verbose_name='Grupo Tributário')),
            ],
            options={
                'verbose_name': 'Tributação Estadual',
                'verbose_name_plural': 'Tributações Estaduais',
                'ordering': ['uf_origem', 'uf_destino'],
                'unique_together': {('grupo', 'uf_origem', 'uf_destino')},
            },
        ),
    ]
