# Generated by Django 5.2.13 on 2026-04-14 14:14

import core.upload
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncm',
            name='arquivo_xml',
            field=models.FileField(blank=True, help_text='XML da Receita Federal com a tabela NCM, se importado manualmente.', null=True, upload_to=core.upload.UploadPath('tributacao'), validators=[core.validators.SecureFileValidator(app_name='tributacao')], verbose_name='Arquivo XML (RFB)'),
        ),
        migrations.AddField(
            model_name='tributacaofederal',
            name='documento_fiscal',
            field=models.FileField(blank=True, help_text='Laudo, parecer ou memorando fiscal em PDF ou XML.', null=True, upload_to=core.upload.UploadPath('tributacao'), validators=[core.validators.SecureFileValidator(app_name='tributacao')], verbose_name='Documento Fiscal (PDF)'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='aplicacao',
            field=models.TextField(blank=True, default='', verbose_name='Aplicação'),
        ),
        migrations.AlterField(
            model_name='grupotributario',
            name='cfop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tributacao.cfop', verbose_name='CFOP padrão'),
        ),
        migrations.AlterField(
            model_name='grupotributario',
            name='ncm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tributacao.ncm', verbose_name='NCM padrão'),
        ),
        migrations.AlterField(
            model_name='grupotributario',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='aliquota_ipi_padrao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alíquota IPI da TIPI', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota IPI padrão (%)'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='ex_tipi',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Exceção TIPI'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='aliquota_fcp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota FCP (%)'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota ICMS (%)'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='mva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MVA (%)'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='permite_credito',
            field=models.BooleanField(default=False, verbose_name='Permite crédito de ICMS?'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='reducao_base_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Redução de Base ICMS (%)'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='uf_destino',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF Destino'),
        ),
        migrations.AlterField(
            model_name='tributacaoestadual',
            name='uf_origem',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF Origem'),
        ),
        migrations.AlterField(
            model_name='tributacaofederal',
            name='gera_credito_cofins',
            field=models.BooleanField(default=True, verbose_name='Gera crédito de COFINS?'),
        ),
        migrations.AlterField(
            model_name='tributacaofederal',
            name='gera_credito_pis',
            field=models.BooleanField(default=True, verbose_name='Gera crédito de PIS?'),
        ),
    ]
