# Generated by Django 5.2.13 on 2026-04-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributacao', '0002_ncm_arquivo_xml_tributacaofederal_documento_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupotributario',
            options={'ordering': ['nome'], 'permissions': [('pode_gerenciar_todas_filiais', 'Pode gerenciar grupos tributários de todas as filiais')], 'verbose_name': 'Grupo Tributário', 'verbose_name_plural': 'Grupos Tributários'},
        ),
        migrations.AlterModelOptions(
            name='ncm',
            options={'ordering': ['codigo'], 'permissions': [('pode_gerenciar_tabelas_fiscais', 'Pode gerenciar tabelas fiscais (NCM/CFOP/CST)')], 'verbose_name': 'NCM', 'verbose_name_plural': 'NCMs'},
        ),
    ]
