# Generated by Django 4.2.28 on 2026-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributacao', '0003_alter_grupotributario_options_alter_ncm_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupotributario',
            options={'ordering': ['nome'], 'permissions': [('pode_gerenciar_todas_filiais', 'Pode gerenciar grupos tributários de todas as filiais'), ('pode_gerenciar_filial_ativa', 'Pode gerenciar grupos tributários da filial ativa')], 'verbose_name': 'Grupo Tributário', 'verbose_name_plural': 'Grupos Tributários'},
        ),
        migrations.AddField(
            model_name='grupotributario',
            name='codigo',
            field=models.CharField(blank=True, default='', help_text='Identificador único do grupo na filial. Ex: GT-CONSUMO, GT-EPI, GT-SERVIÇOS', max_length=50, unique=True, verbose_name='Código do Grupo'),
        ),
        migrations.AddConstraint(
            model_name='grupotributario',
            constraint=models.UniqueConstraint(fields=('codigo', 'filial'), name='unique_codigo_grupo_por_filial'),
        ),
    ]
