# Generated by Django 4.2.28 on 2026-06-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributacao', '0004_alter_grupotributario_options_grupotributario_codigo_and_more'),
    ]

    operations = [
    ]
