# Generated by Django 4.2.28 on 2026-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributacao', '0005_popular_codigo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupotributario',
            name='codigo',
            field=models.CharField(blank=True, default='', help_text='Identificador único do grupo na filial. Ex: GT-CONSUMO, GT-EPI, GT-SERVIÇOS', max_length=50, verbose_name='Código do Grupo'),
        ),
    ]
