# Generated by Django 5.2 on 2025-09-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('Administrativa', 'Administrativa'), ('Comercial', 'Comercial'), ('Técnica', 'Técnica'), ('Outro', 'Outro')], default='Técnica', max_length=20, null=True, verbose_name='Natureza')),
                ('titulo', models.CharField(help_text='Descreva o nome da proposta.', max_length=50, null=True, verbose_name='Titulo')),
                ('acao', models.TextField(help_text='Descreva a ação a ser tomada ou a proposta discutida.', null=True, verbose_name='Ação/Proposta')),
                ('entrada', models.DateField(null=True, verbose_name='Data de Entrada')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo Final')),
                ('status', models.CharField(choices=[('Concluído', 'Concluído'), ('Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, null=True, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ata de Reunião',
                'verbose_name_plural': 'Atas de Reunião',
                'db_table': 'ata_reuniao',
                'ordering': ['-entrada', '-id'],
                'get_latest_by': 'entrada',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('comentario', models.TextField(verbose_name='Comentário')),
            ],
            options={
                'verbose_name': 'Histórico da Ata',
                'verbose_name_plural': 'Históricos da Ata',
                'db_table': 'historico_ata',
                'ordering': ['-timestamp'],
            },
        ),
    ]
