# Generated by Django 5.2 on 2025-07-21 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('departamento_pessoal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('Administrativa', 'Administrativa'), ('Comercial', 'Comercial'), ('Técnica', 'Técnica'), ('Outro', 'Outro')], default='Técnica', max_length=20, verbose_name='Natureza')),
                ('acao', models.TextField(help_text='Descreva a ação a ser tomada ou a proposta discutida.', verbose_name='Ação/Proposta')),
                ('entrada', models.DateField(verbose_name='Data de Entrada')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo Final')),
                ('status', models.CharField(choices=[('Concluído', 'Concluído'), ('Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas', to='cliente.cliente', verbose_name='Contrato')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_coordenadas', to='departamento_pessoal.funcionario', verbose_name='Coordenador')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_responsaveis', to='departamento_pessoal.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ata de Reunião',
                'verbose_name_plural': 'Atas de Reunião',
                'db_table': 'ata_reuniao',
                'ordering': ['-entrada', '-id'],
                'get_latest_by': 'entrada',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ata_reuniao.atareuniao', verbose_name='Ata de Reunião')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico da Ata',
                'verbose_name_plural': 'Históricos da Ata',
                'db_table': 'historico_ata',
                'ordering': ['-timestamp'],
            },
        ),
    ]
