# Generated by Django 5.2 on 2025-06-14 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cargo', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AtaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('Administrativa', 'Administrativa'), ('Comercial', 'Comercial'), ('Técnica', 'Técnica'), ('Outro', 'Outro')], max_length=20, verbose_name='Natureza')),
                ('acao', models.TextField(verbose_name='Ação/Proposta')),
                ('entrada', models.DateField(verbose_name='Data de Entrada')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('status', models.CharField(choices=[('Concluído', 'Concluído'), ('Andamento', 'Andamento'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata_reuniao.cliente')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_coordenadas', to='ata_reuniao.funcionario', verbose_name='Coordenador')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_responsaveis', to='ata_reuniao.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ata de Reunião',
                'verbose_name_plural': 'Atas de Reunião',
                'db_table': 'ata_reuniao',
                'ordering': ['-entrada'],
                'get_latest_by': 'entrada',
            },
        ),
    ]
