# Generated by Django 5.2 on 2025-09-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ata_reuniao', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atareuniao',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas', to='cliente.cliente', verbose_name='Contrato'),
        ),
    ]
