# Generated by Django 5.2 on 2025-08-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_reuniao', '0001_initial'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atareuniao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atareuniao', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='historicoata',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hitoricoata', to='usuario.filial'),
        ),
    ]
