# Generated by Django 5.2 on 2025-05-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_reuniao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atareuniao',
            options={'get_latest_by': 'entrada', 'ordering': ['-entrada'], 'verbose_name': 'Ata de Reunião', 'verbose_name_plural': 'Atas de Reunião'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata_reuniao.cliente'),
        ),
    ]
