# Generated by Django 5.2 on 2025-09-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ata_reuniao', '0002_initial'),
        ('departamento_pessoal', '0001_initial'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atareuniao',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_coordenadas', to='departamento_pessoal.funcionario', verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='atareuniao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atareuniao', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='atareuniao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_responsaveis', to='departamento_pessoal.funcionario', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='historicoata',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ata_reuniao.atareuniao', verbose_name='Ata de Reunião'),
        ),
        migrations.AddField(
            model_name='historicoata',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hitoricoata', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='historicoata',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
