# Generated by Django 5.2.7 on 2025-10-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ata_reuniao', '0002_initial'),
        ('departamento_pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atareuniao',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_coordenadas', to='departamento_pessoal.funcionario', verbose_name='Coordenador'),
        ),
    ]
