# Generated by Django 5.2 on 2025-08-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_reuniao', '0002_atareuniao_filial_historicoata_filial'),
        ('cliente', '0002_cliente_filial'),
        ('departamento_pessoal', '0004_funcionario_foto_3x4'),
    ]

    operations = [
        migrations.AddField(
            model_name='atareuniao',
            name='titulo',
            field=models.CharField(help_text='Descreva o nome da proposta.', max_length=50, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='acao',
            field=models.TextField(help_text='Descreva a ação a ser tomada ou a proposta discutida.', null=True, verbose_name='Ação/Proposta'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas', to='cliente.cliente', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_coordenadas', to='departamento_pessoal.funcionario', verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='entrada',
            field=models.DateField(null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='natureza',
            field=models.CharField(choices=[('Administrativa', 'Administrativa'), ('Comercial', 'Comercial'), ('Técnica', 'Técnica'), ('Outro', 'Outro')], default='Técnica', max_length=20, null=True, verbose_name='Natureza'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_responsaveis', to='departamento_pessoal.funcionario', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='atareuniao',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
