# Generated by Django 5.2 on 2025-09-18 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_reuniao', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ata_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ata_reuniao.atareuniao')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
