# Generated by Django 5.2.13 on 2026-04-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ata_reuniao', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atareuniao',
            options={'get_latest_by': 'entrada', 'ordering': ['-entrada', '-id'], 'permissions': [('view_all_ata_reuniao', 'Pode visualizar todas as atas de reunião')], 'verbose_name': 'Ata de Reunião', 'verbose_name_plural': 'Atas de Reunião'},
        ),
    ]
