# Generated by Django 5.1.6 on 2025-03-28 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('certificado', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FichaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('registro', models.CharField(max_length=50)),
                ('admissao', models.DateField()),
                ('demissao', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(max_length=100)),
                ('local_data', models.CharField(max_length=100)),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_recebimento', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('recebedor', models.CharField(blank=True, max_length=100, null=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.epi')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='epi.fichaepi')),
            ],
        ),
    ]
