# Generated by Django 5.2 on 2025-05-24 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do equipamento', max_length=100, verbose_name='Nome do EPI')),
                ('descricao', models.TextField(help_text='Descrição detalhada do EPI e sua finalidade', verbose_name='Descrição')),
                ('certificado', models.CharField(help_text='Número do CA (Certificado de Aprovação)', max_length=50, verbose_name='Certificado de Aprovação')),
                ('unidade', models.CharField(default='UN', help_text='Unidade de medida (UN, PAR, M, etc)', max_length=20, verbose_name='Unidade de Medida')),
                ('tipo', models.CharField(choices=[('PROT', 'Proteção'), ('SEG', 'Segurança'), ('HIG', 'Higiene'), ('OUT', 'Outros')], default='PROT', max_length=4, verbose_name='Tipo de EPI')),
                ('vida_util', models.PositiveIntegerField(default=12, help_text='Tempo de vida útil em meses', verbose_name='Vida Útil (meses)')),
                ('estoque_minimo', models.PositiveIntegerField(default=10, help_text='Quantidade mínima em estoque', verbose_name='Estoque Mínimo')),
                ('estoque_atual', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'db_table': 'epi',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='idx_epi_nome'), models.Index(fields=['certificado'], name='idx_epi_ca')],
                'constraints': [models.UniqueConstraint(fields=('nome', 'certificado'), name='unique_epi_nome_certificado')],
            },
        ),
        migrations.CreateModel(
            name='FichaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Cargo/função do empregado', max_length=100, verbose_name='Cargo')),
                ('registro', models.CharField(help_text='Matrícula ou registro funcional', max_length=50, verbose_name='Registro')),
                ('admissao', models.DateField(verbose_name='Data de Admissão')),
                ('demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('contrato', models.CharField(help_text='Tipo de contrato de trabalho', max_length=100, verbose_name='Contrato')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('local_data', models.CharField(help_text='Local e data de emissão da ficha', max_length=100, verbose_name='Local e Data')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura Digital')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_epi', to=settings.AUTH_USER_MODEL, verbose_name='Empregado')),
            ],
            options={
                'verbose_name': 'Ficha de EPI',
                'verbose_name_plural': 'Fichas de EPI',
                'db_table': 'ficha_epi',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('data_validade', models.DateField(blank=True, help_text='Data de validade do EPI (se aplicável)', null=True, verbose_name='Data de Validade')),
                ('recebedor', models.CharField(blank=True, help_text='Nome do funcionário que recebeu o EPI', max_length=100, null=True, verbose_name='Recebedor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epi.epi', verbose_name='EPI')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='epi.fichaepi', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Item de EPI',
                'verbose_name_plural': 'Itens de EPI',
                'db_table': 'item_epi',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.AddIndex(
            model_name='fichaepi',
            index=models.Index(fields=['empregado'], name='idx_ficha_empregado'),
        ),
        migrations.AddIndex(
            model_name='fichaepi',
            index=models.Index(fields=['registro'], name='idx_ficha_registro'),
        ),
        migrations.AddIndex(
            model_name='fichaepi',
            index=models.Index(fields=['status'], name='idx_ficha_status'),
        ),
        migrations.AddIndex(
            model_name='itemepi',
            index=models.Index(fields=['ficha'], name='idx_item_ficha'),
        ),
        migrations.AddIndex(
            model_name='itemepi',
            index=models.Index(fields=['epi'], name='idx_item_epi'),
        ),
    ]
