# Generated by Django 5.2 on 2025-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('tipo', models.CharField(choices=[('CAP', 'Capacete'), ('LUV', 'Luva'), ('OCU', 'Óculos'), ('PRO', 'Protetor Auditivo'), ('CAL', 'Calçado'), ('VES', 'Vestuário'), ('OUT', 'Outros')], default='OUT', max_length=3, verbose_name='Tipo de Equipamento')),
                ('codigo_CA', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código CA')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Equipamento de Segurança',
                'verbose_name_plural': 'Equipamentos de Segurança',
                'ordering': ['nome_equipamento'],
            },
        ),
    ]
