# Generated by Django 5.2 on 2025-06-20 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaepi',
            name='empregado',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_epi', to=settings.AUTH_USER_MODEL, verbose_name='Empregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemepi',
            name='epi',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='epi.epi', verbose_name='EPI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemepi',
            name='ficha',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='epi.fichaepi', verbose_name='Ficha'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='fichaepi',
            index=models.Index(fields=['empregado'], name='idx_ficha_empregado'),
        ),
        migrations.AddIndex(
            model_name='fichaepi',
            index=models.Index(fields=['registro'], name='idx_ficha_registro'),
        ),
        migrations.AddIndex(
            model_name='fichaepi',
            index=models.Index(fields=['status'], name='idx_ficha_status'),
        ),
        migrations.AddIndex(
            model_name='itemepi',
            index=models.Index(fields=['ficha'], name='idx_item_ficha'),
        ),
        migrations.AddIndex(
            model_name='itemepi',
            index=models.Index(fields=['epi'], name='idx_item_epi'),
        ),
    ]
