# Generated by Django 5.1.6 on 2025-03-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epi',
            options={'ordering': ['nome'], 'verbose_name': 'EPI', 'verbose_name_plural': 'EPIs'},
        ),
        migrations.AlterModelOptions(
            name='fichaepi',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Ficha de EPI', 'verbose_name_plural': 'Fichas de EPI'},
        ),
        migrations.AlterModelOptions(
            name='itemepi',
            options={'ordering': ['data_recebimento'], 'verbose_name': 'Item de EPI', 'verbose_name_plural': 'Itens de EPI'},
        ),
        migrations.AlterField(
            model_name='epi',
            name='certificado',
            field=models.CharField(max_length=50, verbose_name='Certificado de Aprovação'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do EPI'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='unidade',
            field=models.CharField(max_length=20, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='admissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/', verbose_name='Assinatura Digital'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='contrato',
            field=models.CharField(max_length=100, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='empregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empregado'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='local_data',
            field=models.CharField(max_length=100, verbose_name='Local e Data'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='registro',
            field=models.CharField(max_length=50, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='data_recebimento',
            field=models.DateField(verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.epi', verbose_name='EPI'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='epi.fichaepi', verbose_name='Ficha'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='recebedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recebedor'),
        ),
        migrations.AlterModelTable(
            name='epi',
            table='epi',
        ),
        migrations.AlterModelTable(
            name='fichaepi',
            table='ficha_epi',
        ),
    ]
