# Generated by Django 5.2 on 2025-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_equipamentoseguranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoseguranca',
            name='vida_util',
            field=models.PositiveIntegerField(default=12, help_text='Tempo de vida útil do equipamento em meses', verbose_name='Vida Útil (meses)'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Assinatura em base64', null=True, verbose_name='Data de Validade'),
        ),
    ]
