# Generated by Django 5.1.6 on 2025-04-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_alter_epi_options_alter_fichaepi_options_and_more'),
    ]

    operations = [
    ]
