# Generated by Django 5.1.6 on 2025-04-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0003_auto_20250405_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaepi',
            name='empregado',
            field=models.CharField(help_text='Nome completo do empregado', max_length=100, verbose_name='Nome do Empregado'),
        ),
    ]
