# Generated by Django 5.2 on 2025-05-11 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0004_alter_fichaepi_empregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemepi',
            options={'ordering': ['-data_recebimento'], 'verbose_name': 'Item de EPI', 'verbose_name_plural': 'Itens de EPI'},
        ),
        migrations.AlterField(
            model_name='epi',
            name='certificado',
            field=models.CharField(help_text='Número do CA (Certificado de Aprovação)', max_length=50, verbose_name='Certificado de Aprovação'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='descricao',
            field=models.TextField(help_text='Descrição detalhada do EPI e sua finalidade', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='nome',
            field=models.CharField(help_text='Nome completo do equipamento', max_length=100, verbose_name='Nome do EPI'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='unidade',
            field=models.CharField(default='UN', help_text='Unidade de medida (UN, PAR, M, etc)', max_length=20, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura Digital'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='cargo',
            field=models.CharField(help_text='Cargo/função do empregado', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='contrato',
            field=models.CharField(help_text='Tipo de contrato de trabalho', max_length=100, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='empregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_epi', to=settings.AUTH_USER_MODEL, verbose_name='Empregado'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='local_data',
            field=models.CharField(help_text='Local e data de emissão da ficha', max_length=100, verbose_name='Local e Data'),
        ),
        migrations.AlterField(
            model_name='fichaepi',
            name='registro',
            field=models.CharField(help_text='Matrícula ou registro funcional', max_length=50, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epi.epi', verbose_name='EPI'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemepi',
            name='recebedor',
            field=models.CharField(blank=True, help_text='Nome do funcionário que recebeu o EPI', max_length=100, null=True, verbose_name='Recebedor'),
        ),
    ]
