# Generated by Django 4.2.28 on 2026-07-18 14:52

import core.mixins
import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFotografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Assunto')),
                ('obra_codigo', models.CharField(max_length=150, verbose_name='Obra/Código')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_fotograficos_criados', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_fotograficos', to='usuario.filial', verbose_name='Filial')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_fotograficos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Relatório Fotográfico',
                'verbose_name_plural': 'Relatórios Fotográficos',
                'ordering': ['-data', '-created_at'],
                'permissions': [('view_all_relatorios_filial', 'Pode visualizar todos os relatórios fotográficos da filial')],
            },
        ),
        migrations.CreateModel(
            name='FotoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=core.mixins.UploadPath('relatorio_fotografico'), validators=[core.validators.SecureFileValidator(app_name='relatorio_fotografico')])),
                ('legenda', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='relatorio_fotografico.relatoriofotografico')),
            ],
            options={
                'verbose_name': 'Foto do Relatório',
                'verbose_name_plural': 'Fotos do Relatório',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
