# Generated by Django 4.2.28 on 2026-07-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_fotografico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofotografico',
            name='assunto',
            field=models.CharField(blank=True, default='', max_length=455),
        ),
    ]
