# Generated by Django 4.2.28 on 2026-07-22 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_fotografico', '0002_relatoriofotografico_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriofotografico',
            name='obra_codigo',
        ),
        migrations.AddField(
            model_name='relatoriofotografico',
            name='obra_contrato',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Obra/Contrato'),
            preserve_default=False,
        ),
    ]
