# Generated by Django 4.2.28 on 2026-07-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_fotografico', '0003_remove_relatoriofotografico_obra_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotorelatorio',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='fotorelatorio',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fotorelatorio',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
