# Generated by Django 4.2.28 on 2026-07-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_fotografico', '0004_fotorelatorio_endereco_fotorelatorio_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofotografico',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
