# Generated by Django 4.2.28 on 2026-07-29 17:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_fotografico', '0005_relatoriofotografico_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotorelatorio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='relatoriofotografico',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20),
        ),
    ]
