# Generated by Django 4.2.30 on 2026-08-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_fotografico', '0006_alter_fotorelatorio_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofotografico',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='relatoriofotografico',
            name='empresa',
            field=models.CharField(blank=True, default='Cetest', max_length=60, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='relatoriofotografico',
            name='telefone',
            field=models.CharField(blank=True, default='11 3045-9400', max_length=20, verbose_name='Telefone'),
        ),
    ]
