# Generated by Django 5.2 on 2025-12-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('tarefas', '0003_tarefas_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='tarefas.tarefas'),
        ),
    ]
