# Generated by Django 5.2.13 on 2026-04-14 16:59

import chat.models
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('tarefas', '0008_alter_comentario_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='tarefas.tarefas', verbose_name='Tarefa Relacionada'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.chat_file_path, validators=[core.validators.SecureFileValidator(app_name='chat_arquivos')], verbose_name='Arquivo Anexado'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.chat_image_path, validators=[core.validators.SecureFileValidator(app_name='chat_imagens')], verbose_name='Imagem'),
        ),
    ]
