# Generated by Django 5.2 on 2025-11-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='chat',
        ),
    ]
