# Generated by Django 5.2 on 2025-11-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_table'),
        ('tarefas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ChatRoom',
            new_name='room',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('DM', 'Direct Message'), ('GROUP', 'Group Chat'), ('TASK', 'Task Chat')], default='DM', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='tarefas.tarefas', verbose_name='Tarefa Relacionada'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
