# Generated by Django 5.2 on 2025-09-05 08:27

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Operadora')),
            ],
            options={
                'verbose_name': 'Operadora',
                'verbose_name_plural': 'Operadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='controle_de_telefone.marca')),
            ],
            options={
                'verbose_name': 'Modelo de Aparelho',
                'verbose_name_plural': 'Modelos de Aparelhos',
                'ordering': ['marca__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('encrypted_imei', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='IMEI Criptografado')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Aquisição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aparelhos', to='usuario.filial')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aparelhos', to='controle_de_telefone.modelo')),
            ],
            options={
                'verbose_name': 'Aparelho Telefônico',
                'verbose_name_plural': 'Aparelhos Telefônicos',
                'ordering': ['modelo__marca__nome', 'modelo__nome'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Plano')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('franquia_dados_gb', models.PositiveIntegerField(verbose_name='Franquia de Dados (GB)')),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='controle_de_telefone.operadora')),
            ],
            options={
                'verbose_name': 'Plano de Telefonia',
                'verbose_name_plural': 'Planos de Telefonia',
                'ordering': ['operadora__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LinhaTelefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Número da Linha')),
                ('data_ativacao', models.DateField(verbose_name='Data de Ativação')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ativa', 'Ativa (Em Uso)'), ('bloqueada', 'Bloqueada'), ('cancelada', 'Cancelada')], default='disponivel', max_length=20)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='usuario.filial')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='controle_de_telefone.plano')),
            ],
            options={
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado')], default='ativo', max_length=20)),
                ('termo_gerado', models.FileField(blank=True, help_text='PDF gerado automaticamente ao criar o vínculo.', null=True, upload_to='termos_gerados/', verbose_name='Termo de Responsabilidade Gerado')),
                ('assinatura_digital', models.TextField(blank=True, help_text='Armazena os dados da assinatura digital.', null=True, verbose_name='Assinatura Digital')),
                ('termo_assinado', models.FileField(blank=True, help_text='Faça o upload do termo assinado aqui.', null=True, upload_to='termos_assinados/', verbose_name='Termo Assinado (Upload)')),
                ('aparelho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='controle_de_telefone.aparelho', verbose_name='Aparelho')),
            ],
            options={
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
    ]
