# Generated by Django 5.2 on 2025-10-14 23:06

import encrypted_model_fields.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_de_aparelho', models.CharField(choices=[('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('radio_ht', 'Rádio HT'), ('notebook', 'Notebook'), ('outro', 'Outro')], default='smartphone', max_length=30, verbose_name='Tipo de Aparelho')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Aquisição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('acessorios', models.TextField(blank=True, null=True, verbose_name='Acessórios Incluídos')),
                ('imei', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='IMEI')),
            ],
            options={
                'verbose_name': 'Aparelho Telefônico',
                'verbose_name_plural': 'Aparelhos Telefônicos',
                'ordering': ['modelo__marca__nome', 'modelo__nome'],
            },
        ),
        migrations.CreateModel(
            name='LinhaTelefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Número da Linha')),
                ('data_ativacao', models.DateField(verbose_name='Data de Ativação')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ativa', 'Ativa (Em Uso)'), ('bloqueada', 'Bloqueada'), ('cancelada', 'Cancelada')], default='disponivel', max_length=20)),
            ],
            options={
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Modelo')),
            ],
            options={
                'verbose_name': 'Modelo de Aparelho',
                'verbose_name_plural': 'Modelos de Aparelhos',
                'ordering': ['marca__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Operadora')),
            ],
            options={
                'verbose_name': 'Operadora',
                'verbose_name_plural': 'Operadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Plano')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('franquia_dados_gb', models.PositiveIntegerField(verbose_name='Franquia de Dados (GB)')),
            ],
            options={
                'verbose_name': 'Plano de Telefonia',
                'verbose_name_plural': 'Planos de Telefonia',
                'ordering': ['operadora__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_entrega', models.DateField(blank=True, verbose_name='Data de Entrega')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado')], default='ativo', max_length=20)),
                ('termo_gerado', models.FileField(blank=True, null=True, upload_to='termos_gerados/', verbose_name='Termo de Responsabilidade Gerado')),
                ('assinatura_digital', models.FileField(blank=True, null=True, upload_to='assinaturas/')),
                ('termo_assinado_upload', models.FileField(blank=True, null=True, upload_to='termos_assinados/', verbose_name='Upload do Termo Assinado')),
                ('foi_assinado', models.BooleanField(default=False, verbose_name='Termo Foi Assinado?')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vínculo de Aparelho/Linha',
                'verbose_name_plural': 'Vínculos de Aparelhos/Linhas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
