# Generated by Django 5.2 on 2025-09-07 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0001_initial'),
        ('departamento_pessoal', '0002_alter_funcionario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='funcionario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='departamento_pessoal.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculo',
            name='linha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='controle_de_telefone.linhatelefonica', verbose_name='Linha Telefônica'),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('marca', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='plano',
            unique_together={('operadora', 'nome')},
        ),
    ]
