# Generated by Django 5.0.14 on 2025-09-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0001_initial'),
        ('departamento_pessoal', '0004_funcionario_foto_3x4'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='assinatura_digital',
            field=models.TextField(blank=True, help_text='Armazena os dados da assinatura digital.', null=True),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='termo_assinado_upload',
            field=models.FileField(blank=True, help_text='Faça o upload do termo assinado aqui.', null=True, upload_to='termos_assinados/'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento_pessoal.funcionario'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='termo_responsabilidade',
            field=models.FileField(blank=True, help_text='PDF gerado automaticamente ao criar o vínculo.', null=True, upload_to='termos_responsabilidade/'),
        ),
    ]
