# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_de_telefone', '0001_initial'),
        ('departamento_pessoal', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aparelhos', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='linhatelefonica',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='controle_de_telefone.marca'),
        ),
        migrations.AddField(
            model_name='aparelho',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aparelhos', to='controle_de_telefone.modelo'),
        ),
        migrations.AddField(
            model_name='plano',
            name='operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='controle_de_telefone.operadora'),
        ),
        migrations.AddField(
            model_name='linhatelefonica',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='controle_de_telefone.plano'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='aparelho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='controle_de_telefone.aparelho', verbose_name='Aparelho'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento_pessoal.funcionario'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='linha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='controle_de_telefone.linhatelefonica', verbose_name='Linha Telefônica'),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('marca', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='plano',
            unique_together={('operadora', 'nome')},
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['funcionario', 'status'], name='controle_de_funcion_6312c1_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['aparelho', 'status'], name='controle_de_aparelh_9223b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['linha', 'status'], name='controle_de_linha_i_8a6f86_idx'),
        ),
    ]
