# Generated by Django 5.2 on 2026-02-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0002_initial'),
        ('departamento_pessoal', '0003_alter_documento_funcionario_alter_funcionario_funcao'),
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recarga', models.CharField(choices=[('credito', 'Crédito Avulso'), ('pacote_dados', 'Pacote de Dados'), ('pacote_voz', 'Pacote de Voz'), ('combo', 'Combo (Dados + Voz)')], default='credito', max_length=20, verbose_name='Tipo de Recarga')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da recarga em reais', max_digits=10, verbose_name='Valor (R$)')),
                ('franquia_dados_mb', models.PositiveIntegerField(blank=True, help_text='Quantidade de dados em MB (se aplicável)', null=True, verbose_name='Franquia de Dados (MB)')),
                ('minutos_voz', models.PositiveIntegerField(blank=True, help_text='Quantidade de minutos (se aplicável)', null=True, verbose_name='Minutos de Voz')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_recarga', models.DateField(help_text='Data em que a recarga foi/será realizada', verbose_name='Data da Recarga')),
                ('data_inicio', models.DateField(help_text='Data de início da validade dos créditos', verbose_name='Início da Vigência')),
                ('data_termino', models.DateField(help_text='Data de expiração dos créditos', verbose_name='Término da Vigência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendente', max_length=20, verbose_name='Status')),
                ('comprovante', models.FileField(blank=True, help_text='Comprovante da recarga (PDF ou imagem)', null=True, upload_to='recargas/comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('codigo_transacao', models.CharField(blank=True, help_text='Código/protocolo da operadora', max_length=100, null=True, verbose_name='Código da Transação')),
                ('observacao', models.TextField(blank=True, help_text='Informações adicionais sobre a recarga', verbose_name='Observações')),
                ('motivo', models.TextField(blank=True, help_text='Justificativa para a recarga', verbose_name='Motivo/Justificativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('historico', models.JSONField(blank=True, default=list, verbose_name='Histórico de Alterações')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas_credito', to='usuario.filial', verbose_name='Filial')),
                ('linha', models.ForeignKey(help_text='Linha que receberá a recarga', on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to='controle_de_telefone.linhatelefonica', verbose_name='Linha Telefônica')),
                ('responsavel', models.ForeignKey(help_text='Funcionário que autorizou a recarga', on_delete=django.db.models.deletion.PROTECT, related_name='recargas_autorizadas', to='departamento_pessoal.funcionario', verbose_name='Responsável/Solicitante')),
                ('usuario_credito', models.ForeignKey(help_text='Funcionário que utilizará os créditos', on_delete=django.db.models.deletion.PROTECT, related_name='recargas_utilizadas', to='departamento_pessoal.funcionario', verbose_name='Usuário dos Créditos')),
            ],
            options={
                'verbose_name': 'Recarga de Crédito',
                'verbose_name_plural': 'Recargas de Crédito',
                'ordering': ['-data_solicitacao'],
                'permissions': [('aprovar_recarga', 'Pode aprovar recarga de crédito'), ('cancelar_recarga', 'Pode cancelar recarga de crédito')],
                'indexes': [models.Index(fields=['filial', 'status'], name='controle_de_filial__0a5b4a_idx'), models.Index(fields=['linha'], name='controle_de_linha_i_625656_idx'), models.Index(fields=['data_recarga'], name='controle_de_data_re_3d0ce7_idx'), models.Index(fields=['usuario_credito'], name='controle_de_usuario_c82f11_idx')],
            },
        ),
    ]
