# Generated by Django 5.0.14 on 2025-09-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0002_vinculo_assinatura_digital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculo',
            name='termo_assinado_upload',
        ),
        migrations.RemoveField(
            model_name='vinculo',
            name='termo_responsabilidade',
        ),
        migrations.AddField(
            model_name='vinculo',
            name='termo_assinado',
            field=models.FileField(blank=True, help_text='Faça o upload do termo assinado aqui.', null=True, upload_to='termos_assinados/', verbose_name='Termo Assinado (Upload)'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='termo_gerado',
            field=models.FileField(blank=True, help_text='PDF gerado automaticamente ao criar o vínculo.', null=True, upload_to='termos_gerados/', verbose_name='Termo de Responsabilidade Gerado'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='assinatura_digital',
            field=models.TextField(blank=True, help_text='Armazena os dados da assinatura digital.', null=True, verbose_name='Assinatura Digital'),
        ),
    ]
