# Generated by Django 5.2 on 2025-09-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='data_entrega',
            field=models.DateField(blank=True, verbose_name='Data de Entrega'),
        ),
    ]
