# Generated by Django 5.2 on 2025-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0003_alter_vinculo_data_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculo',
            name='termo_assinado',
        ),
        migrations.AddField(
            model_name='vinculo',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='foi_assinado',
            field=models.BooleanField(default=False, verbose_name='Termo Foi Assinado?'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='termo_assinado_upload',
            field=models.FileField(blank=True, null=True, upload_to='termos_assinados/', verbose_name='Upload do Termo Assinado'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='assinatura_digital',
            field=models.FileField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
