# Generated by Django 5.2.13 on 2026-04-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0003_recargacredito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparelho',
            options={'ordering': ['modelo__marca__nome', 'modelo__nome'], 'permissions': [('view_all_aparelho', 'Pode ver todos os aparelhos da filial')], 'verbose_name': 'Aparelho Telefônico', 'verbose_name_plural': 'Aparelhos Telefônicos'},
        ),
        migrations.AlterModelOptions(
            name='linhatelefonica',
            options={'permissions': [('view_all_linhatelefonica', 'Pode ver todas as linhas da filial')]},
        ),
        migrations.AlterModelOptions(
            name='vinculo',
            options={'ordering': ['-criado_em'], 'permissions': [('view_all_vinculo', 'Pode ver todos os vínculos da filial'), ('aprovar_recarga', 'Pode aprovar recargas'), ('cancelar_recarga', 'Pode cancelar recargas')], 'verbose_name': 'Vínculo de Aparelho/Linha', 'verbose_name_plural': 'Vínculos de Aparelhos/Linhas'},
        ),
    ]
