# Generated by Django 5.2.13 on 2026-04-19 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0004_alter_aparelho_options_alter_linhatelefonica_options_and_more'),
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nome'], 'permissions': [('view_all_marca', 'Pode ver todas as marcas da filial')], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['marca__nome', 'nome'], 'permissions': [('view_all_modelo', 'Pode ver todos os modelos da filial')], 'verbose_name': 'Modelo de Aparelho', 'verbose_name_plural': 'Modelos de Aparelhos'},
        ),
        migrations.AlterModelOptions(
            name='operadora',
            options={'ordering': ['nome'], 'permissions': [('view_all_operadora', 'Pode ver todas as operadoras da filial')], 'verbose_name': 'Operadora', 'verbose_name_plural': 'Operadoras'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['operadora__nome', 'nome'], 'permissions': [('view_all_plano', 'Pode ver todos os planos da filial')], 'verbose_name': 'Plano de Telefonia', 'verbose_name_plural': 'Planos de Telefonia'},
        ),
        migrations.AlterModelOptions(
            name='recargacredito',
            options={'ordering': ['-data_solicitacao'], 'permissions': [('aprovar_recarga', 'Pode aprovar recarga de crédito'), ('cancelar_recarga', 'Pode cancelar recarga de crédito'), ('view_all_recargacredito', 'Pode ver todas as recargas da filial')], 'verbose_name': 'Recarga de Crédito', 'verbose_name_plural': 'Recargas de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='vinculo',
            options={'ordering': ['-criado_em'], 'permissions': [('view_all_vinculo', 'Pode ver todos os vínculos da filial')], 'verbose_name': 'Vínculo de Aparelho/Linha', 'verbose_name_plural': 'Vínculos de Aparelhos/Linhas'},
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plano',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marca',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='marcas', to='usuario.filial', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_aparelho', to='usuario.filial', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operadora',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operadoras', to='usuario.filial', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='usuario.filial', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('filial', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('filial', 'marca', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='operadora',
            unique_together={('filial', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='plano',
            unique_together={('filial', 'operadora', 'nome')},
        ),
    ]
