# Generated by Django 5.2 on 2025-09-12 22:30

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0004_remove_vinculo_termo_assinado_and_more'),
        ('departamento_pessoal', '0003_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculo',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Vínculo de Aparelho/Linha', 'verbose_name_plural': 'Vínculos de Aparelhos/Linhas'},
        ),
        migrations.AddField(
            model_name='aparelho',
            name='imei',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='termo_gerado',
            field=models.FileField(blank=True, null=True, upload_to='termos_gerados/', verbose_name='Termo de Responsabilidade Gerado'),
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['funcionario', 'status'], name='controle_de_funcion_6312c1_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['aparelho', 'status'], name='controle_de_aparelh_9223b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['linha', 'status'], name='controle_de_linha_i_8a6f86_idx'),
        ),
    ]
