# Generated by Django 5.2.13 on 2026-04-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0005_add_filial_cadastros_auxiliares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recargacredito',
            options={'ordering': ['-data_solicitacao'], 'permissions': [('aprovar_recarga', 'Pode aprovar recarga de crédito'), ('cancelar_recarga', 'Pode cancelar recarga de crédito'), ('view_all_recargacredito', 'Pode ver todas as recargas da filial'), ('realizar_recarga', 'Pode marcar recargas como realizadas')], 'verbose_name': 'Recarga de Crédito', 'verbose_name_plural': 'Recargas de Crédito'},
        ),
    ]
