# Generated by Django 5.2 on 2025-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0005_alter_vinculo_options_aparelho_imei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='acessorios',
            field=models.TextField(blank=True, null=True, verbose_name='Acessórios Incluídos'),
        ),
    ]
