# Generated by Django 5.2 on 2025-09-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0006_aparelho_acessorios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='encrypted_imei',
        ),
    ]
