# Generated by Django 5.2 on 2025-09-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0007_remove_aparelho_encrypted_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='tipo_de_aparelho',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('radio_ht', 'Rádio HT'), ('outro', 'Outro')], default='smartphone', max_length=30, verbose_name='Tipo de Aparelho'),
        ),
    ]
