# Generated by Django 5.2 on 2025-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_telefone', '0008_aparelho_tipo_de_aparelho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='tipo_de_aparelho',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('radio_ht', 'Rádio HT'), ('notebook', 'Notebook'), ('outro', 'Outro')], default='smartphone', max_length=30, verbose_name='Tipo de Aparelho'),
        ),
    ]
