# Generated by Django 5.2 on 2025-06-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False, verbose_name='Presença Confirmada')),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota da Avaliação')),
                ('certificado_emitido', models.BooleanField(default=False, verbose_name='Certificado Emitido')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Curso')),
                ('modalidade', models.CharField(choices=[('P', 'Presencial'), ('O', 'Online'), ('H', 'Híbrido')], max_length=1, verbose_name='Modalidade')),
                ('area', models.CharField(choices=[('SAU', 'Saúde'), ('SEG', 'Segurança'), ('ADM', 'Administrativo'), ('OPE', 'Operacional'), ('TEC', 'Técnico')], max_length=3, verbose_name='Área de Conhecimento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('certificado', models.BooleanField(default=True, verbose_name='Emite Certificado?')),
                ('validade_meses', models.PositiveIntegerField(verbose_name='Validade do Certificado (meses)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Cursos',
                'db_table': 'tipocurso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Treinamento')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('duracao', models.IntegerField(verbose_name='Duração (horas)')),
                ('atividade', models.CharField(blank=True, max_length=200, verbose_name='Atividade Relacionada')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('cm', models.CharField(blank=True, max_length=100, verbose_name='CM (Centro de Custo?)')),
                ('palestrante', models.CharField(max_length=100, verbose_name='Palestrante/Instrutor')),
                ('hxh', models.IntegerField(verbose_name='HxH (Horas Homem)')),
                ('status', models.CharField(choices=[('P', 'Planejado'), ('A', 'Em Andamento'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='P', max_length=1, verbose_name='Status')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total')),
                ('participantes_previstos', models.IntegerField(verbose_name='Nº de Participantes Previstos')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'db_table': 'Treinamento',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
