# Generated by Django 5.2 on 2025-06-23 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treinamentos.tipocurso', verbose_name='Tipo de Curso'),
        ),
        migrations.AddField(
            model_name='participante',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='treinamentos.treinamento', verbose_name='Treinamento'),
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('treinamento', 'funcionario')},
        ),
    ]
