# Generated by Django 5.2 on 2025-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='treinamentos_disponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Treinamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('validade_meses', models.PositiveIntegerField(verbose_name='Validade (meses)')),
                ('modalidade', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10, verbose_name='Modalidade')),
                ('tipo', models.CharField(choices=[('graduacao', 'Graduação'), ('tecnico', 'Técnico'), ('profissionalizante', 'Profissionalizante'), ('livre', 'Livre'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('fornecedor', models.CharField(blank=True, max_length=100, verbose_name='Fornecedor')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['nome'],
            },
        ),
    ]
