# Generated by Django 5.1.6 on 2025-04-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
    ]
