# Generated by Django 5.2 on 2025-06-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tipotreinamento',
            index=models.Index(fields=['nome'], name='idx_tipo_treinamento_nome'),
        ),
        migrations.AddIndex(
            model_name='tipotreinamento',
            index=models.Index(fields=['modalidade'], name='idx_tipo_treina_modalidade'),
        ),
        migrations.AddIndex(
            model_name='tipotreinamento',
            index=models.Index(fields=['area'], name='idx_tipo_treinamento_area'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='tipo_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos', to='treinamentos.tipotreinamento', verbose_name='Tipo de Treinamento'),
        ),
        migrations.AddField(
            model_name='treinamentocolaborador',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='treinamentos.colaborador'),
        ),
        migrations.AddField(
            model_name='treinamentocolaborador',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamentos.treinamento'),
        ),
        migrations.AddIndex(
            model_name='treinamento',
            index=models.Index(fields=['tipo_treinamento'], name='idx_treinamento_tipo'),
        ),
        migrations.AddIndex(
            model_name='treinamento',
            index=models.Index(fields=['data_inicio'], name='idx_treinamento_data'),
        ),
        migrations.AddIndex(
            model_name='treinamento',
            index=models.Index(fields=['status'], name='idx_treinamento_status'),
        ),
        migrations.AddConstraint(
            model_name='treinamento',
            constraint=models.CheckConstraint(condition=models.Q(('data_vencimento__gte', models.F('data_inicio'))), name='check_data_vencimento_maior_inicio'),
        ),
        migrations.AddConstraint(
            model_name='treinamento',
            constraint=models.CheckConstraint(condition=models.Q(('hxh__lte', models.F('duracao'))), name='check_hxh_menor_duracao'),
        ),
        migrations.AlterUniqueTogether(
            name='treinamentocolaborador',
            unique_together={('colaborador', 'treinamento')},
        ),
    ]
