# Generated by Django 5.2 on 2025-08-23 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipocursos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Registro'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('treinamento', 'funcionario'), name='inscricao_unica_por_aluno'),
        ),
        migrations.AlterModelTable(
            name='treinamento',
            table='treinamento',
        ),
    ]
