# Generated by Django 5.2.7 on 2025-10-02 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinamentos', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipocursos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treinamentos.tipocurso', verbose_name='Tipo de Curso'),
        ),
        migrations.AddField(
            model_name='participante',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='treinamentos.treinamento', verbose_name='Treinamento'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('treinamento', 'funcionario'), name='inscricao_unica_por_aluno'),
        ),
    ]
