# Generated by Django 5.2 on 2025-05-31 19:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0002_treinamentos_disponiveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='treinamentos_disponiveis',
            new_name='TreinamentoDisponivel',
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='duracao',
            field=models.PositiveIntegerField(blank=True, help_text='Duração total em horas', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração (horas)'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='hxh',
            field=models.IntegerField(default=0, help_text='Horas necessárias por participante', verbose_name='Horas por Participante'),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreinamentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('proximo', 'Próximo a vencer')], max_length=10)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='treinamentos.colaborador')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamentos.treinamento')),
            ],
            options={
                'unique_together': {('colaborador', 'treinamento')},
            },
        ),
    ]
