# Generated by Django 5.2 on 2025-06-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'permissions': [('registrar_presenca', 'Pode registrar presença de participantes'), ('emitir_certificado', 'Pode emitir certificado para participante'), ('avaliar_participante', 'Pode avaliar participante')], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='tipocurso',
            options={'ordering': ['nome'], 'permissions': [('ativar_tipocurso', 'Pode ativar/desativar tipo de curso'), ('relatorio_tipocurso', 'Pode gerar relatórios de tipos de curso')], 'verbose_name': 'Tipo de Curso', 'verbose_name_plural': 'Tipos de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='treinamento',
            options={'ordering': ['-data_inicio'], 'permissions': [('gerenciar_participantes', 'Pode gerenciar participantes do treinamento'), ('alterar_status', 'Pode alterar status do treinamento'), ('gerar_certificados', 'Pode gerar certificados de treinamento')], 'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
    ]
