# Generated by Django 5.2 on 2025-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0002_alter_participante_unique_together_tipocurso_filial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocurso',
            name='validade_meses',
            field=models.PositiveIntegerField(help_text='Insira 0 se o certificado não tiver validade.', verbose_name='Validade do Certificado (meses)'),
        ),
    ]
