# Generated by Django 5.2 on 2025-10-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treinamento',
            options={'ordering': ['-data_inicio'], 'permissions': [('gerenciar_participantes', 'Pode gerenciar participantes do treinamento'), ('alterar_status', 'Pode alterar status do treinamento'), ('gerar_certificados', 'Pode gerar certificados de treinamento'), ('ver_relatorios', 'Pode visualizar o dashboard e relatórios')], 'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
    ]
