# Generated by Django 5.2 on 2025-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0003_alter_treinamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocurso',
            name='validade_meses',
            field=models.PositiveIntegerField(default=0, help_text='Insira 0 se o certificado não tiver validade.', verbose_name='Validade do Certificado (meses)'),
        ),
    ]
