# Generated by Django 5.2 on 2025-06-30 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0003_alter_participante_options_alter_tipocurso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Nome do funcionário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='area',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('COM', 'Comportamental'), ('GRA', 'Graduação'), ('INT', 'Integração'), ('LID', 'Liderança'), ('MOT', 'Motivacional'), ('OPE', 'Operacional'), ('PRO', 'Profissionalizante'), ('SAU', 'Saúde'), ('SEG', 'Segurança'), ('TEC', 'Técnico')], max_length=3, verbose_name='Área de Conhecimento'),
        ),
    ]
