# Generated by Django 5.2 on 2025-08-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0003_alter_tipocurso_validade_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='hxh',
        ),
        migrations.AddField(
            model_name='treinamento',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, verbose_name='CM (Centro de Custo)'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='horas_homem',
            field=models.PositiveIntegerField(null=True, verbose_name='HxH (Horas Homem)'),
        ),
    ]
