# Generated by Django 5.2 on 2025-11-18 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0004_alter_tipocurso_validade_meses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GabaritoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Gabarito Padrão', max_length=100, verbose_name='Nome do Gabarito')),
                ('empresa_nome', models.CharField(default='CETEST MINAS ENGENHARIA E SERVIÇOS S/A', max_length=255, verbose_name='Nome da Empresa Certificadora')),
                ('texto_principal', models.TextField(default='Certificamos que <strong>{participante_nome}</strong>, portador(a) do documento {participante_documento}, participou do <strong>{nome_curso}</strong> ({conteudo_programatico}), promovido pela {empresa_nome}, {referencia_normativa}, realizado em {local} no período de {data_inicio} a {data_fim}, com carga horária total de <strong>{carga_horaria} ({carga_horaria_extenso}) horas</strong>.', help_text='Use os placeholders disponíveis: {participante_nome}, {participante_documento}, {empresa_nome}, {nome_curso}, {conteudo_programatico}, {referencia_normativa}, {data_inicio}, {data_fim}, {carga_horaria}, {carga_horaria_extenso}, {local}', verbose_name='Texto Principal do Certificado')),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='certificados/fundos/', verbose_name='Imagem de Fundo (Opcional)')),
                ('texto_verso', models.TextField(blank=True, default="<h3>CONTEÚDO PROGRAMÁTICO</h3><div class='grade-curricular'>{grade_curricular}</div><hr>Protocolo de Validação: <strong>{protocolo}</strong><br>Para verificar a autenticidade deste certificado, aponte a câmera do seu celular para o QR Code.", help_text='Texto padrão do verso. Use {grade_curricular}, {protocolo} e {qr_code_tag} (o QR Code será inserido aqui).', null=True, verbose_name='Texto do Verso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Gabarito de Certificado',
                'verbose_name_plural': 'Gabaritos de Certificado',
            },
        ),
        migrations.RemoveField(
            model_name='tipocurso',
            name='descricao',
        ),
        migrations.AddField(
            model_name='participante',
            name='protocolo_validacao',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ID único para validação do certificado (usado no QR Code)', null=True, verbose_name='Protocolo de Validação'),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='conteudo_programatico',
            field=models.TextField(blank=True, help_text="Texto que descreve o conteúdo, ex: 'Curso sobre Designado de CIPA...'", null=True, verbose_name='Conteúdo Programático'),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='descricao_no_certificado',
            field=models.TextField(blank=True, help_text="Texto que descreve o conteúdo, ex: 'Curso sobre Designado de CIPA...'", null=True, verbose_name='Descrição (para frente do certificado)'),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='grade_curricular',
            field=models.TextField(blank=True, help_text='Conteúdo programático detalhado que aparecerá no verso. Use quebras de linha para listar os tópicos.', null=True, verbose_name='Grade Curricular (para verso)'),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='referencia_normativa',
            field=models.CharField(blank=True, help_text="Ex: 'conforme NR-5 Portaria nº 08 de 23 de fevereiro de 1.999'", max_length=255, null=True, verbose_name='Referência Normativa'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='assinaturas_solicitadas',
            field=models.BooleanField(default=False, help_text='Marca se os links de assinatura já foram enviados.', verbose_name='Assinaturas Solicitadas'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='palestrante_cargo',
            field=models.CharField(blank=True, help_text="Ex: 'Técnica de Segurança do Trabalho'", max_length=100, null=True, verbose_name='Cargo do Palestrante'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='palestrante_registro',
            field=models.CharField(blank=True, help_text="Ex: 'Registro do MTE SP 0073739'", max_length=50, null=True, verbose_name='Registro Prof. do Palestrante'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acesso', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True, verbose_name='Token de Acesso')),
                ('assinatura_json', models.TextField(blank=True, null=True, verbose_name='Dados da Assinatura (JSON)')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('nome_assinante', models.CharField(blank=True, max_length=255)),
                ('documento_assinante', models.CharField(blank=True, max_length=50)),
                ('participante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='treinamentos.participante')),
                ('treinamento_responsavel', models.OneToOneField(blank=True, help_text='Assinatura do Responsável/Instrutor pelo treinamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_responsavel', to='treinamentos.treinamento')),
            ],
            options={
                'verbose_name': 'Assinatura de Certificado',
                'verbose_name_plural': 'Assinaturas de Certificado',
            },
        ),
    ]
