# Generated by Django 4.2.16 on 2026-03-07 20:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        ('departamento_pessoal', '0003_alter_documento_funcionario_alter_funcionario_funcao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treinamentos', '0006_popular_protocolos_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Instruções para o Aluno')),
                ('tempo_limite_min', models.PositiveIntegerField(default=60, help_text='0 = sem limite.', verbose_name='Tempo Limite (minutos)')),
                ('embaralhar_questoes', models.BooleanField(default=True, verbose_name='Embaralhar Questões')),
                ('embaralhar_alternativas', models.BooleanField(default=True, verbose_name='Embaralhar Alternativas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliação EAD',
                'verbose_name_plural': 'Avaliações EAD',
            },
        ),
        migrations.CreateModel(
            name='CursoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Curso')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, help_text='Resumo para cards e listagens.', max_length=300, verbose_name='Descrição Curta')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='treinamentos/ead/capas/', verbose_name='Imagem de Capa')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=20, verbose_name='Nível')),
                ('carga_horaria_total', models.DecimalField(decimal_places=1, help_text='Carga horária mínima exigida para certificação.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Carga Horária Total (horas)')),
                ('nota_minima', models.DecimalField(decimal_places=1, default=Decimal('7.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Nota Mínima para Aprovação')),
                ('max_tentativas_avaliacao', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máx. Tentativas na Avaliação')),
                ('percentual_minimo_assistido', models.PositiveIntegerField(default=75, help_text='Percentual mínimo de aulas concluídas para liberar a avaliação.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='% Mínimo de Conteúdo Assistido')),
                ('instrutor_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome do Instrutor')),
                ('instrutor_qualificacao', models.CharField(blank=True, max_length=300, verbose_name='Qualificação do Instrutor')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_ead_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_ead', to='usuario.filial', verbose_name='Filial')),
                ('tipo_curso', models.ForeignKey(help_text='Vincula ao tipo de curso existente (NR, área, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='cursos_ead', to='treinamentos.tipocurso', verbose_name='Tipo de Curso')),
            ],
            options={
                'verbose_name': 'Curso EAD',
                'verbose_name_plural': 'Cursos EAD',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], db_index=True, default='em_andamento', max_length=20, verbose_name='Status')),
                ('progresso_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Progresso (%)')),
                ('carga_horaria_cumprida_segundos', models.PositiveIntegerField(default=0, help_text='Total de segundos efetivamente gastos em aulas.', verbose_name='Carga Horária Cumprida (segundos)')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota Final')),
                ('tentativas_avaliacao', models.PositiveIntegerField(default=0, verbose_name='Tentativas Realizadas')),
                ('data_matricula', models.DateTimeField(auto_now_add=True, verbose_name='Data da Matrícula')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('prazo_limite', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Limite')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_ead', to='treinamentos.cursoead', verbose_name='Curso EAD')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_ead', to='usuario.filial', verbose_name='Filial')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_ead', to='departamento_pessoal.funcionario', verbose_name='Funcionário')),
                ('matriculado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Matriculado por')),
            ],
            options={
                'verbose_name': 'Matrícula EAD',
                'verbose_name_plural': 'Matrículas EAD',
                'ordering': ['-data_matricula'],
            },
        ),
        migrations.CreateModel(
            name='PlanoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo_conclusao_dias', models.PositiveIntegerField(default=30, help_text='Dias após matrícula para concluir todos os cursos.', verbose_name='Prazo para Conclusão (dias)')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cargos', models.ManyToManyField(blank=True, related_name='planos_estudo', to='departamento_pessoal.cargo', verbose_name='Cargos Aplicáveis')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Plano de Estudo',
                'verbose_name_plural': 'Planos de Estudo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('peso', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='Peso')),
                ('explicacao', models.TextField(blank=True, help_text='Exibida após o aluno responder (feedback pedagógico).', verbose_name='Explicação da Resposta Correta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_ead', to='treinamentos.avaliacaoead', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Questão EAD',
                'verbose_name_plural': 'Questões EAD',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TentativaAvaliacaoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentativa', models.PositiveIntegerField(default=1, verbose_name='Nº da Tentativa')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota Obtida')),
                ('aprovado', models.BooleanField(null=True, verbose_name='Aprovado')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_ead', to='treinamentos.avaliacaoead', verbose_name='Avaliação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_ead', to='treinamentos.matriculaead', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Tentativa de Avaliação EAD',
                'verbose_name_plural': 'Tentativas de Avaliação EAD',
                'ordering': ['-numero_tentativa'],
                'unique_together': {('matricula', 'avaliacao', 'numero_tentativa')},
            },
        ),
        migrations.CreateModel(
            name='PlanoEstudoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_cursos', to='treinamentos.cursoead')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_cursos', to='treinamentos.planoestudo')),
            ],
            options={
                'verbose_name': 'Curso do Plano',
                'verbose_name_plural': 'Cursos do Plano',
                'ordering': ['ordem'],
                'unique_together': {('plano', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='planoestudo',
            name='cursos',
            field=models.ManyToManyField(related_name='planos_estudo', through='treinamentos.PlanoEstudoCurso', to='treinamentos.cursoead', verbose_name='Cursos'),
        ),
        migrations.AddField(
            model_name='planoestudo',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='planos_estudo', to='departamento_pessoal.departamento', verbose_name='Departamentos Aplicáveis'),
        ),
        migrations.AddField(
            model_name='planoestudo',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_estudo', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.CreateModel(
            name='ModuloEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Módulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_ead', to='treinamentos.cursoead', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Módulo EAD',
                'verbose_name_plural': 'Módulos EAD',
                'ordering': ['ordem'],
                'unique_together': {('curso', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='matriculaead',
            name='plano_estudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_ead', to='treinamentos.planoestudo', verbose_name='Plano de Estudo (origem)'),
        ),
        migrations.CreateModel(
            name='CertificadoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Validação')),
                ('nome_funcionario', models.CharField(max_length=255, verbose_name='Nome do Funcionário')),
                ('cpf_funcionario', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('nome_curso', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('nome_tipo_curso', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Curso')),
                ('carga_horaria_exigida', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='CH Exigida (horas)')),
                ('carga_horaria_cumprida', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='CH Cumprida (horas)')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Nota Final')),
                ('nome_instrutor', models.CharField(blank=True, max_length=150, verbose_name='Instrutor')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='treinamentos/ead/certificados/', verbose_name='Arquivo PDF')),
                ('emitido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_ead', to='usuario.filial', verbose_name='Filial')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado_ead', to='treinamentos.matriculaead', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Certificado EAD',
                'verbose_name_plural': 'Certificados EAD',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='avaliacaoead',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_ead', to='treinamentos.cursoead', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='AulaEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Aula')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('tipo_conteudo', models.CharField(choices=[('video_upload', 'Vídeo (Upload)'), ('video_externo', 'Vídeo Externo (YouTube/Vimeo)'), ('texto', 'Texto/Artigo'), ('pdf', 'Documento PDF')], default='video_externo', max_length=20, verbose_name='Tipo de Conteúdo')),
                ('conteudo_texto', models.TextField(blank=True, verbose_name='Conteúdo em Texto/HTML')),
                ('arquivo_video', models.FileField(blank=True, help_text='Formatos aceitos: MP4, WebM, OGG. Máx recomendado: 500MB.', null=True, upload_to='treinamentos/ead/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='Arquivo de Vídeo')),
                ('url_video_externo', models.URLField(blank=True, help_text='Cole a URL do YouTube ou Vimeo.', verbose_name='URL do Vídeo Externo')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='treinamentos/ead/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Arquivo PDF')),
                ('duracao_estimada_min', models.PositiveIntegerField(default=10, help_text='Tempo estimado para completar esta aula.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração Estimada (minutos)')),
                ('obrigatoria', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_ead', to='treinamentos.moduloead', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Aula EAD',
                'verbose_name_plural': 'Aulas EAD',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AlternativaEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto da Alternativa')),
                ('correta', models.BooleanField(default=False, verbose_name='Correta')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas_ead', to='treinamentos.questaoead', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Alternativa EAD',
                'verbose_name_plural': 'Alternativas EAD',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAlunoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treinamentos.alternativaead', verbose_name='Alternativa Escolhida')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamentos.questaoead', verbose_name='Questão')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_ead', to='treinamentos.tentativaavaliacaoead', verbose_name='Tentativa')),
            ],
            options={
                'verbose_name': 'Resposta EAD',
                'verbose_name_plural': 'Respostas EAD',
                'unique_together': {('tentativa', 'questao')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoAulaEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('percentual_assistido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Assistido/Lido')),
                ('tempo_gasto_segundos', models.PositiveIntegerField(default=0, verbose_name='Tempo Gasto (segundos)')),
                ('video_posicao_segundos', models.PositiveIntegerField(default=0, help_text='Marca de onde o aluno parou no vídeo.', verbose_name='Posição do Vídeo (segundos)')),
                ('video_duracao_total', models.PositiveIntegerField(default=0, help_text='Preenchido automaticamente pelo player.', verbose_name='Duração Total do Vídeo (segundos)')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('ultimo_acesso', models.DateTimeField(auto_now=True, verbose_name='Último Acesso')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_ead', to='treinamentos.aulaead', verbose_name='Aula')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_ead', to='treinamentos.matriculaead', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Progresso da Aula EAD',
                'verbose_name_plural': 'Progressos das Aulas EAD',
                'ordering': ['aula__modulo__ordem', 'aula__ordem'],
                'unique_together': {('matricula', 'aula')},
            },
        ),
        migrations.AddIndex(
            model_name='matriculaead',
            index=models.Index(fields=['status', 'filial'], name='idx_matead_status_filial'),
        ),
        migrations.AddConstraint(
            model_name='matriculaead',
            constraint=models.UniqueConstraint(fields=('funcionario', 'curso'), name='matricula_ead_unica'),
        ),
        migrations.AddIndex(
            model_name='cursoead',
            index=models.Index(fields=['status', 'filial'], name='idx_ead_status_filial'),
        ),
        migrations.AlterUniqueTogether(
            name='aulaead',
            unique_together={('modulo', 'ordem')},
        ),
    ]
