# Generated by Django 5.2.13 on 2026-04-14 15:02

import core.upload
import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0007_avaliacaoead_cursoead_matriculaead_planoestudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='treinamento_responsavel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_responsavel', to='treinamentos.treinamento'),
        ),
        migrations.AlterField(
            model_name='aulaead',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='Somente PDF. Máx: 500MB.', null=True, upload_to=core.upload.UploadPath('treinamentos'), validators=[core.validators.SecureFileValidator(app_name='treinamentos')], verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='aulaead',
            name='arquivo_video',
            field=models.FileField(blank=True, help_text='Formatos aceitos: MP4, WebM, OGG. Máx: 500MB.', null=True, upload_to=core.upload.UploadPath('treinamentos'), validators=[core.validators.SecureFileValidator(app_name='treinamentos')], verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='aulaead',
            name='duracao_estimada_min',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração Estimada (minutos)'),
        ),
        migrations.AlterField(
            model_name='aulaead',
            name='url_video_externo',
            field=models.URLField(blank=True, verbose_name='URL do Vídeo Externo'),
        ),
        migrations.AlterField(
            model_name='avaliacaoead',
            name='tempo_limite_min',
            field=models.PositiveIntegerField(default=60, verbose_name='Tempo Limite (minutos)'),
        ),
        migrations.AlterField(
            model_name='certificadoead',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='PDF gerado automaticamente. Máx: 500MB.', null=True, upload_to=core.upload.UploadPath('treinamentos'), validators=[core.validators.SecureFileValidator(app_name='treinamentos')], verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='cursoead',
            name='carga_horaria_total',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Carga Horária Total (horas)'),
        ),
        migrations.AlterField(
            model_name='cursoead',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='cursoead',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='JPG, PNG ou WebP. Máx: 500MB.', null=True, upload_to=core.upload.UploadPath('treinamentos'), validators=[core.validators.SecureFileValidator(app_name='treinamentos')], verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='cursoead',
            name='percentual_minimo_assistido',
            field=models.PositiveIntegerField(default=75, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='% Mínimo de Conteúdo Assistido'),
        ),
        migrations.AlterField(
            model_name='cursoead',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_ead', to='treinamentos.tipocurso', verbose_name='Tipo de Curso'),
        ),
        migrations.AlterField(
            model_name='gabaritocertificado',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text='JPG, PNG ou WebP. Máx: 500MB.', null=True, upload_to=core.upload.UploadPath('treinamentos'), validators=[core.validators.SecureFileValidator(app_name='treinamentos')], verbose_name='Imagem de Fundo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='gabaritocertificado',
            name='texto_principal',
            field=models.TextField(default='Certificamos que <strong>{participante_nome}</strong>, portador(a) do documento {participante_documento}, participou do <strong>{nome_curso}</strong> ({conteudo_programatico}), promovido pela {empresa_nome}, {referencia_normativa}, realizado em {local} no período de {data_inicio} a {data_fim}, com carga horária total de <strong>{carga_horaria} ({carga_horaria_extenso}) horas</strong>.', verbose_name='Texto Principal do Certificado'),
        ),
        migrations.AlterField(
            model_name='gabaritocertificado',
            name='texto_verso',
            field=models.TextField(blank=True, default="<h3>CONTEÚDO PROGRAMÁTICO</h3><div class='grade-curricular'>{grade_curricular}</div><hr>Protocolo de Validação: <strong>{protocolo}</strong><br>Para verificar a autenticidade deste certificado, aponte a câmera do seu celular para o QR Code.", null=True, verbose_name='Texto do Verso'),
        ),
        migrations.AlterField(
            model_name='matriculaead',
            name='carga_horaria_cumprida_segundos',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga Horária Cumprida (segundos)'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='protocolo_validacao',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Protocolo de Validação'),
        ),
        migrations.AlterField(
            model_name='planoestudo',
            name='prazo_conclusao_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Prazo para Conclusão (dias)'),
        ),
        migrations.AlterField(
            model_name='progressoaulaead',
            name='video_duracao_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Duração Total do Vídeo (segundos)'),
        ),
        migrations.AlterField(
            model_name='progressoaulaead',
            name='video_posicao_segundos',
            field=models.PositiveIntegerField(default=0, verbose_name='Posição do Vídeo (segundos)'),
        ),
        migrations.AlterField(
            model_name='questaoead',
            name='explicacao',
            field=models.TextField(blank=True, verbose_name='Explicação da Resposta Correta'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='conteudo_programatico',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Programático'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='descricao_no_certificado',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (para frente do certificado)'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='grade_curricular',
            field=models.TextField(blank=True, null=True, verbose_name='Grade Curricular (para verso)'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='referencia_normativa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência Normativa'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='validade_meses',
            field=models.PositiveIntegerField(default=0, verbose_name='Validade do Certificado (meses)'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='assinaturas_solicitadas',
            field=models.BooleanField(default=False, verbose_name='Assinaturas Solicitadas'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='palestrante_cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Palestrante'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='palestrante_registro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Prof. do Palestrante'),
        ),
    ]
