# Generated by Django 5.2.13 on 2026-04-28 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0008_alter_assinatura_treinamento_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='protocolo_validacao',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Protocolo de Validação'),
        ),
    ]
