# Generated by Django 5.2.17 on 2026-10-05 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0009_alter_participante_protocolo_validacao'),
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='treinamento',
            constraint=models.UniqueConstraint(fields=('nome', 'filial'), name='uniq_tipocurso_nome_filial'),
        ),
    ]
