# Generated by Django 5.2.17 on 2026-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0010_treinamento_uniq_tipocurso_nome_filial'),
        ('usuario', '0003_padroniza_nomes_grupos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treinamento',
            name='uniq_tipocurso_nome_filial',
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Curso'),
        ),
        migrations.AddConstraint(
            model_name='tipocurso',
            constraint=models.UniqueConstraint(fields=('nome', 'filial'), name='uniq_tipocurso_nome_filial'),
        ),
    ]
