# Generated by Django 5.2.7 on 2025-10-02 21:41

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('contrato', models.CharField(default='0', max_length=4, verbose_name='Número do Contrato (CM)')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('unidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidade/Filial')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[core.validators.validate_cnpj], verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, help_text='Formato: (00) 00000-0000 ou (00) 0000-0000', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (00) 0000-0000 ou (00) 00000-0000.', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Informe um endereço de e-mail válido.')], verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('data_de_inicio', models.DateField(verbose_name='Data de Início')),
                ('estatus', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nome'],
            },
        ),
    ]
