# Generated by Django 5.1.6 on 2025-03-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_cliente',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cliente_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'logradouro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contrato', models.CharField(default='0000', max_length=4)),
                ('razao_social', models.CharField(max_length=100)),
                ('unidade', models.IntegerField(blank=True, null=True)),
                ('cnpj', models.CharField(default='00000000000000', max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('data_de_inicio', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cliente.logradouro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_cliente', to='cliente.cliente')),
            ],
            options={
                'db_table': 'cliente_cliente',
            },
        ),
    ]
