# Generated by Django 5.2 on 2025-08-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cliente', to='usuario.filial'),
        ),
    ]
