# Generated by Django 5.1.6 on 2025-03-15 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'logradouro',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrato',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_de_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='unidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cliente.logradouro'),
            preserve_default=False,
        ),
    ]
