# Generated by Django 5.2 on 2025-07-01 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='check_data_inicio_passado',
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('data_de_inicio__lte', datetime.date(2025, 7, 1))), name='check_data_inicio_passado'),
        ),
    ]
