# Generated by Django 5.2.7 on 2025-10-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('logradouro', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cliente', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='logradouro.logradouro', verbose_name='Endereço'),
        ),
    ]
