# Generated by Django 5.2 on 2025-09-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='logradouro.logradouro', verbose_name='Endereço'),
        ),
    ]
