# Generated by Django 5.2 on 2025-06-18 11:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='check_data_inicio_passado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail para contato', max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Informe um endereço de email válido')], verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='Número de inscrição estadual', max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='Número de inscrição municipal', max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre o cliente', null=True, verbose_name='Observações'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('data_de_inicio__lte', datetime.date(2025, 6, 18))), name='check_data_inicio_passado'),
        ),
    ]
