# Generated by Django 5.2 on 2025-06-18 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_check_data_inicio_passado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00 ou conter 14 dígitos', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$|^\\d{14}$')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contrato',
            field=models.CharField(default='0000', help_text='Código de 4 dígitos do contrato', max_length=4, verbose_name='Número do Contrato (CM)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (00) 00000-0000 ou conter 10/11 dígitos', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$|^\\d{10,11}$')], verbose_name='Telefone'),
        ),
    ]
