# Generated by Django 5.2 on 2025-05-11 16:38
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # Suas dependências aqui
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_encerramento',
            field=models.DateField(null=True, blank=True),
        ),
    ]