# Generated by Django 5.2 on 2025-09-14 19:35

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[core.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Informe um endereço de e-mail válido.')], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (00) 00000-0000 ou (00) 0000-0000', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (00) 0000-0000 ou (00) 00000-0000.', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
