# Generated by Django 5.1.6 on 2025-03-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_logradouro_alter_cliente_options_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_cliente', to='cliente.cliente')),
            ],
            options={
                'db_table': 'cliente_cliente',
            },
        ),
    ]
