# Generated by Django 5.2 on 2026-02-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='usuario.filial', verbose_name='Filial'),
            preserve_default=False,
        ),
    ]
