# Generated by Django 5.1.6 on 2025-03-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_clientecliente_logradouro_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientecliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logradouro',
            options={},
        ),
    ]
