# Generated by Django 5.2 on 2025-09-16 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_cnpj_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (00) 00000-0000 ou (00) 0000-0000', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (00) 0000-0000 ou (00) 00000-0000.', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
