# Generated by Django 5.2 on 2025-06-19 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_cnpj_alter_cliente_contrato_and_more'),
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='check_data_inicio_passado',
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('data_de_inicio__lte', datetime.date(2025, 6, 19))), name='check_data_inicio_passado'),
        ),
    ]
