# Generated by Django 4.2.16 on 2026-03-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0002_initial'),
        ('usuario', '0002_alter_filial_options'),
        ('cliente', '0003_alter_cliente_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', related_query_name='cliente', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', related_query_name='cliente', to='logradouro.logradouro', verbose_name='Endereço'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cnpj'], name='idx_cliente_cnpj'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['razao_social'], name='idx_cliente_razao_social'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['contrato'], name='idx_cliente_contrato'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['filial', 'estatus'], name='idx_cliente_filial_status'),
        ),
    ]
