# Generated by Django 5.1.6 on 2025-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_clientecliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_cliente',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cliente_cliente',
                'managed': False,
            },
        ),
    ]
