# Generated by Django 5.2.13 on 2026-04-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_filial_alter_cliente_logradouro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'permissions': [('view_all_cliente', 'Pode ver todos os clientes da filial')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
