# Generated by Django 5.1.6 on 2025-03-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrato',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
