"""
Django settings for gerenciandoTarefas 1.01 project por Emerson Goncalves.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

from celery.schedules import crontab

# Seu asgi.py ou wsgi.py
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'gerenciandoTarefas.settings')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURAÇÕES DE SEGURANÇA ---
# Lidas diretamente do seu arquivo .env
SECRET_KEY = config('SECRET_KEY')
FERNET_KEYS = config('FERNET_KEYS')
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

#ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

# Lista de domínios confiáveis para requisições POST
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',

    'https://www.cetestgerenciandotarefas.com.br',
    'https://cetestgerenciandotarefas.com.br',
]

# Application definition

INSTALLED_APPS = [

    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_components',
    'django_extensions',
    'django_bootstrap5',
    'django_htmx',
    'django_select2',

    # 2. Aplicativos de Terceiros
    'whitenoise.runserver_nostatic',
    'rest_framework',
    'widget_tweaks',
    'crispy_forms',
    'crispy_bootstrap5',
    'localflavor',
    'template_partials',
    'phonenumber_field',
    'notifications',
    'channels',

    # 3. Seus Aplicativos Locais (em ordem de dependência)
    'dashboard.apps.DashboardConfig',
    'usuario.apps.UsuarioConfig', 
    'home',
    'core',
    'logradouro',
    'cliente',
    'departamento_pessoal',
    'automovel.apps.AutomovelConfig',
    'seguranca_trabalho',
    'suprimentos',
    'tarefas.apps.TarefasConfig',
    'treinamentos.apps.TreinamentosConfig',
    'gestao_riscos',
    'ata_reuniao',
    'ferramentas',
    'controle_de_telefone',
    'chat',
    'arquivos',
    'documentos', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'gerenciandoTarefas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.filial_context',
                'usuario.context_processors.filial_context',
                'chat.context_processors.chat_global_data', 
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

WSGI_APPLICATION = 'gerenciandoTarefas.wsgi.application'
ASGI_APPLICATION = 'gerenciandoTarefas.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', cast=int),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# --- AUTENTICAÇÃO E VALIDAÇÃO ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'usuario.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Fuso horário do Brasil
TIME_ZONE = 'America/Sao_Paulo'

# Mapbox (opcional - para mapas mais avançados)
MAPBOX_ACCESS_TOKEN = 'your_mapbox_token_here'

# Configurações para arquivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Melhora o desempenho do WhiteNoise com compressão e cache
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Diretório público para imagens, etc.
MEDIA_URL = '/midia/'
MEDIA_ROOT = BASE_DIR / 'midia'

# Diretório PRIVADO para arquivos sensíveis
PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, 'private_media')

# Configuração para servir arquivos privados com django-sendfile2
SENDFILE_BACKEND = 'sendfile2.backends.simple'
SENDFILE_ROOT = PRIVATE_MEDIA_ROOT
SENDFILE_URL = '/private' # URL interna, não precisa ser servida publicamente

# Tamanho máximo de upload (5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração de E-mail
EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# Configurações DRF
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30
}

# LOGIN_URL, LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL
LOGIN_URL = 'usuario:login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'usuario:login'

# --- CORREÇÃO DO REDIRECIONAMENTO SSL/PROXY ---
# Esta linha informa ao Django para confiar no cabeçalho
# 'X-Forwarded-Proto' enviado pelo seu proxy (Nginx, Load Balancer, etc.)
# para determinar se a requisição original era HTTPS. Isso resolve o loop de redirecionamento.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configurações de Cookie de Segurança
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Configurações do Channel Layers
if DEBUG:
    # Em desenvolvimento, use o backend 'in-memory'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    # Em produção, use o Redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [('177.131.142.229', 6379)], 
            },
        },
    }

# Configurações de notificação
CHAT_CONFIG = {
    'DESKTOP_NOTIFICATIONS': True,
    'SOUND_NOTIFICATIONS': True,
    'AUTO_RECONNECT': True,
    'RECONNECT_INTERVAL': 3000,
}

# --- Configuração do Agendador (Celery Beat) ---

CELERY_BEAT_SCHEDULE = {
    # Dê um nome descritivo para a sua tarefa agendada
    'verificar-vencimentos-diariamente': {
        
        # 1. O caminho para a sua tarefa
        'task': 'documentos.verificar_vencimentos',
        
        # 2. A frequência (crontab)
        # Este exemplo roda todo dia às 3:00 da manhã
        'schedule': crontab(minute=0, hour=3),
        
        # 'args': (1, 2) # Se a sua tarefa precisasse de argumentos
    },
    
    # ... você pode adicionar outras tarefas agendadas aqui ...
}
