# Generated by Django 5.2.13 on 2026-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissão do Dashboard',
                'verbose_name_plural': 'Permissões do Dashboard',
                'permissions': [('view_dashboard_geral', 'Pode visualizar o Dashboard Geral'), ('view_dashboard_treinamentos', 'Pode visualizar o Dashboard de Treinamentos'), ('view_dashboard_tarefas', 'Pode visualizar o Dashboard de Tarefas'), ('view_dashboard_epi', 'Pode visualizar o Dashboard de EPI'), ('view_dashboard_documentos', 'Pode visualizar o Dashboard de Documentos'), ('view_dashboard_pgr', 'Pode visualizar o Dashboard de PGR')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
