# Generated by Django 5.2 on 2025-05-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('senha', models.CharField(max_length=6, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, verbose_name='Nome Fantasia')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos ao qual os usuários pertence.', related_name='ConjuntoUsuaario', related_query_name='user', to='auth.group', verbose_name='groupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='ConjuntoUsuario', related_query_name='user', to='auth.permission', verbose_name='Permissões do usúario')),
            ],
            options={
                'db_table': 'usuario_customuser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.permission')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuariocustomuser')),
            ],
            options={
                'db_table': 'customuserpermission',
                'managed': True,
                'unique_together': {('customuser', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='CustomUserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuariocustomuser')),
            ],
            options={
                'db_table': 'customusergroup',
                'managed': True,
                'unique_together': {('customuser', 'group')},
            },
        ),
    ]
