# Generated by Django 5.1.6 on 2025-04-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('senha', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario_customuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustomuserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_customuser_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustomuserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_customuser_user_permissions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
