# Generated by Django 5.2 on 2025-10-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['nome'], 'permissions': [('pode_ver_dashboard_geral', 'Pode ver o dashboard principal'), ('pode_acessar_relatorios_filial', 'Pode acessar relatórios da filial'), ('pode_editar_card_principal', 'Pode editar os cards principais')], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
    ]
