# Generated by Django 5.2 on 2025-10-09 17:41


from django.db import migrations

# Dicionário mapeando o 'codename' da permissão para o novo 'name' em português.
# Usar o codename é mais seguro pois ele não muda.
PERMISSIONS_TRANSLATIONS = {
    # auth app
    'add_logentry': 'Pode adicionar registro de log',
    'change_logentry': 'Pode alterar registro de log',
    'delete_logentry': 'Pode excluir registro de log',
    'view_logentry': 'Pode visualizar registro de log',
    'add_permission': 'Pode adicionar permissão',
    'change_permission': 'Pode alterar permissão',
    'delete_permission': 'Pode excluir permissão',
    'view_permission': 'Pode visualizar permissão',
    'add_group': 'Pode adicionar grupo',
    'change_group': 'Pode alterar grupo',
    'delete_group': 'Pode excluir grupo',
    'view_group': 'Pode visualizar grupo',
    # contenttypes app
    'add_contenttype': 'Pode adicionar tipo de conteúdo',
    'change_contenttype': 'Pode alterar tipo de conteúdo',
    'delete_contenttype': 'Pode excluir tipo de conteúdo',
    'view_contenttype': 'Pode visualizar tipo de conteúdo',
    # sessions app
    'add_session': 'Pode adicionar sessão',
    'change_session': 'Pode alterar sessão',
    'delete_session': 'Pode excluir sessão',
    'view_session': 'Pode visualizar sessão',
    # usuario app
    'add_filial': 'Pode adicionar Filial',
    'change_filial': 'Pode alterar Filial',
    'delete_filial': 'Pode excluir Filial',
    'view_filial': 'Pode visualizar Filial',
    'add_usuario': 'Pode adicionar usuário',
    'change_usuario': 'Pode alterar usuário',
    'delete_usuario': 'Pode excluir usuário',
    'view_usuario': 'Pode visualizar usuário',
    'add_groupcardpermissions': 'Pode adicionar Permissão de Cartão de Grupo',
    'change_groupcardpermissions': 'Pode alterar Permissão de Cartão de Grupo',
    'delete_groupcardpermissions': 'Pode excluir Permissão de Cartão de Grupo',
    'view_groupcardpermissions': 'Pode visualizar Permissão de Cartão de Grupo',
    # Outros apps (adicionei todos da sua lista)
    'add_logradouro': 'Pode adicionar Logradouro',
    'change_logradouro': 'Pode alterar Logradouro',
    'delete_logradouro': 'Pode excluir Logradouro',
    'view_logradouro': 'Pode visualizar Logradouro',
    'add_cliente': 'Pode adicionar Cliente',
    'change_cliente': 'Pode alterar Cliente',
    'delete_cliente': 'Pode excluir Cliente',
    'view_cliente': 'Pode visualizar Cliente',
    'add_cargo': 'Pode adicionar Cargo',
    'change_cargo': 'Pode alterar Cargo',
    'delete_cargo': 'Pode excluir Cargo',
    'view_cargo': 'Pode visualizar Cargo',
    'add_departamento': 'Pode adicionar Departamento',
    'change_departamento': 'Pode alterar Departamento',
    'delete_departamento': 'Pode excluir Departamento',
    'view_departamento': 'Pode visualizar Departamento',
    'add_documento': 'Pode adicionar Documento',
    'change_documento': 'Pode alterar Documento',
    'delete_documento': 'Pode excluir Documento',
    'view_documento': 'Pode visualizar Documento',
    'add_funcionario': 'Pode adicionar Funcionário',
    'change_funcionario': 'Pode alterar Funcionário',
    'delete_funcionario': 'Pode excluir Funcionário',
    'view_funcionario': 'Pode visualizar Funcionário',
    'add_carro': 'Pode adicionar Carro',
    'change_carro': 'Pode alterar Carro',
    'delete_carro': 'Pode excluir Carro',
    'view_carro': 'Pode visualizar Carro',
    'add_agendamento': 'Pode adicionar Agendamento',
    'change_agendamento': 'Pode alterar Agendamento',
    'delete_agendamento': 'Pode excluir Agendamento',
    'view_agendamento': 'Pode visualizar Agendamento',
    'add_entregaepi': 'Pode adicionar Entrega de EPI',
    'change_entregaepi': 'Pode alterar Entrega de EPI',
    'delete_entregaepi': 'Pode excluir Entrega de EPI',
    'view_entregaepi': 'Pode visualizar Entrega de EPI',
    'assinar_entregaepi': 'Pode assinar entrega de EPI',
    'add_equipamento': 'Pode adicionar Equipamento (EPI)',
    'change_equipamento': 'Pode alterar Equipamento (EPI)',
    'delete_equipamento': 'Pode excluir Equipamento (EPI)',
    'view_equipamento': 'Pode visualizar Equipamento (EPI)',
    'add_fichaepi': 'Pode adicionar Ficha de EPI',
    'change_fichaepi': 'Pode alterar Ficha de EPI',
    'delete_fichaepi': 'Pode excluir Ficha de EPI',
    'view_fichaepi': 'Pode visualizar Ficha de EPI',
    'add_funcao': 'Pode adicionar Função',
    'change_funcao': 'Pode alterar Função',
    'delete_funcao': 'Pode excluir Função',
    'view_funcao': 'Pode visualizar Função',
    'add_matrizepi': 'Pode adicionar Matriz de EPI por Função',
    'change_matrizepi': 'Pode alterar Matriz de EPI por Função',
    'delete_matrizepi': 'Pode excluir Matriz de EPI por Função',
    'view_matrizepi': 'Pode visualizar Matriz de EPI por Função',
    'add_tarefas': 'Pode adicionar Tarefa',
    'change_tarefas': 'Pode alterar Tarefa',
    'delete_tarefas': 'Pode excluir Tarefa',
    'view_tarefas': 'Pode visualizar Tarefa',
    'add_treinamento': 'Pode adicionar Treinamento',
    'change_treinamento': 'Pode alterar Treinamento',
    'delete_treinamento': 'Pode excluir Treinamento',
    'view_treinamento': 'Pode visualizar Treinamento',
    'gerenciar_participantes': 'Pode gerenciar participantes do treinamento',
    'alterar_status': 'Pode alterar status do treinamento',
    'gerar_certificados': 'Pode gerar certificados de treinamento',
    'add_inspecao': 'Pode adicionar Inspeção',
    'change_inspecao': 'Pode alterar Inspeção',
    'delete_inspecao': 'Pode excluir Inspeção',
    'view_inspecao': 'Pode visualizar Inspeção',
    'add_atareuniao': 'Pode adicionar Ata de Reunião',
    'change_atareuniao': 'Pode alterar Ata de Reunião',
    'delete_atareuniao': 'Pode excluir Ata de Reunião',
    'view_atareuniao': 'Pode visualizar Ata de Reunião',
    'add_ferramenta': 'Pode adicionar Ferramenta',
    'change_ferramenta': 'Pode alterar Ferramenta',
    'delete_ferramenta': 'Pode excluir Ferramenta',
    'view_ferramenta': 'Pode visualizar Ferramenta',
    'add_termoderesponsabilidade': 'Pode adicionar Termo de Responsabilidade',
    'change_termoderesponsabilidade': 'Pode alterar Termo de Responsabilidade',
    'delete_termoderesponsabilidade': 'Pode excluir Termo de Responsabilidade',
    'view_termoderesponsabilidade': 'Pode visualizar Termo de Responsabilidade',
    'add_aparelho': 'Pode adicionar Aparelho Telefônico',
    'change_aparelho': 'Pode alterar Aparelho Telefônico',
    'delete_aparelho': 'Pode excluir Aparelho Telefônico',
    'view_aparelho': 'Pode visualizar Aparelho Telefônico',
    'add_linhatelefonica': 'Pode adicionar linha telefonica',
    'change_linhatelefonica': 'Pode alterar linha telefonica',
    'delete_linhatelefonica': 'Pode excluir linha telefonica',
    'view_linhatelefonica': 'Pode visualizar linha telefonica',
    'add_plano': 'Pode adicionar Plano de Telefonia',
    'change_plano': 'Pode alterar Plano de Telefonia',
    'delete_plano': 'Pode excluir Plano de Telefonia',
    'view_plano': 'Pode visualizar Plano de Telefonia',
    'add_vinculo': 'Pode adicionar Vínculo de Aparelho/Linha',
    'change_vinculo': 'Pode alterar Vínculo de Aparelho/Linha',
    'delete_vinculo': 'Pode excluir Vínculo de Aparelho/Linha',
    'view_vinculo': 'Pode visualizar Vínculo de Aparelho/Linha',
    'add_cargofuncao': 'Pode adicionar Cargo e Função Associados',
    'change_cargofuncao': 'Pode alterar Cargo e Função Associados',
    'delete_cargofuncao': 'Pode excluir Cargo e Função Associados',
    'view_cargofuncao': 'Pode visualizar Cargo e Função Associados',
}


def translate_permissions(apps, schema_editor):
    """
    Atualiza o campo 'name' das permissões para português.
    """
    Permission = apps.get_model('auth', 'Permission')
    for codename, new_name in PERMISSIONS_TRANSLATIONS.items():
        try:
            # Encontra a permissão pelo codename e atualiza o nome
            perm = Permission.objects.get(codename=codename)
            perm.name = new_name
            perm.save(update_fields=['name'])
        except Permission.DoesNotExist:
            # Se a permissão não existir por algum motivo, apenas ignora e continua
            print(f"Aviso: Permissão com codename '{codename}' não encontrada. Pulando.")
            continue


class Migration(migrations.Migration):

    dependencies = [

        ('usuario', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
   
    ]

    operations = [
        migrations.RunPython(translate_permissions, migrations.RunPython.noop),
    ]