# Generated by Django 5.2 on 2025-08-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='filial',
        ),
        migrations.AddField(
            model_name='usuario',
            name='filiais_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Selecione as filiais que este usuário pode acessar.', related_name='usuarios_permitidos', to='usuario.filial', verbose_name='Filiais Permitidas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='filial_ativa',
            field=models.ForeignKey(blank=True, help_text='A filial que está atualmente selecionada para este usuário.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.filial', verbose_name='Filial Ativa'),
        ),
    ]
