# Generated by Django 5.1.6 on 2025-04-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_delete_customuser'),
    ]

    operations = [
    ]
