# Generated by Django 5.1.6 on 2025-04-13 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0002_usuario_usuariocustomuser_usuariocustomusergroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customusergroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customuserpermission',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='UsuarioCustomuserGroups',
        ),
        migrations.DeleteModel(
            name='UsuarioCustomuserUserPermissions',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuariocustomuser',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='customusergroup',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuariocustomuser'),
        ),
        migrations.AddField(
            model_name='customusergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuserpermission',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuariocustomuser'),
        ),
        migrations.AddField(
            model_name='customuserpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.permission'),
        ),
        migrations.AlterUniqueTogether(
            name='customusergroup',
            unique_together={('customuser', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='customuserpermission',
            unique_together={('customuser', 'permission')},
        ),
    ]
