# Generated by Django 5.1.6 on 2025-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0003_customusergroup_customuserpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos ao qual os usuários pertence.', related_name='ConjuntoUsuaario', related_query_name='user', to='auth.group', verbose_name='groupos'),
        ),
        migrations.AddField(
            model_name='usuariocustomuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='ConjuntoUsuario', related_query_name='user', to='auth.permission', verbose_name='Permissões do usúario'),
        ),
    ]
