# Generated by Django 5.1.6 on 2025-04-07 00:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_auto_20250405_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('modalidade', models.CharField(choices=[('I', 'Interno'), ('E', 'Externo')], max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('duracao', models.PositiveIntegerField(help_text='Duração em horas', validators=[django.core.validators.MinValueValidator(1)])),
                ('atividade', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('funcionario', models.CharField(help_text='Nome do funcionário responsável', max_length=100)),
                ('cm', models.CharField(help_text='Coordenador/Mentor', max_length=100, verbose_name='CM')),
                ('palestrante', models.CharField(max_length=100)),
                ('hxh', models.PositiveIntegerField(help_text='Horas por hora', verbose_name='HxH')),
                ('tipo_treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipotreinamento')),
            ],
            options={
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
