# Generated by Django 5.2 on 2025-09-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCardPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_visiveis', models.JSONField(default=list)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Permissão de Cartão de Grupo',
                'verbose_name_plural': 'Permissões de Cartões de Grupo',
            },
        ),
    ]
