# Generated by Django 5.2 on 2025-06-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0004_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoproxy',
            options={'verbose_name': 'Grupo de Permissões', 'verbose_name_plural': 'Grupos de Permissões'},
        ),
        migrations.AlterModelOptions(
            name='permissaoproxy',
            options={'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='endereço de e-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
