# Generated by Django 5.1.6 on 2025-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_initial'),
        ('usuario', '0004_usuariocustomuser_groups_and_more'),
    ]

    operations = [
    ]
