# Generated by Django 5.2 on 2025-06-11 14:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logradouro', '0002_alter_logradouro_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código CBO')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CBO',
                'verbose_name_plural': 'CBOs',
                'db_table': 'cbos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Departamento')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('tipo', models.CharField(choices=[('ADM', 'Administrativo'), ('OPR', 'Operacional'), ('COM', 'Comercial'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('PCM', 'Planejamento'), ('TST', 'Segurança do Trabalho'), ('DP', 'Departamento Pessoal')], default='ADM', max_length=3)),
                ('centro_custo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sigla', models.CharField(blank=True, max_length=10)),
                ('tipo', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('ME', 'MEI')], max_length=3)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('pis', models.CharField(blank=True, max_length=14, unique=True, verbose_name='PIS/PASEP')),
                ('rg', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='RG deve ter no mínimo 8 dígitos'), django.core.validators.RegexValidator(message='RG inválido. Formato esperado: 00.000.000-0 ou 00.000.000-X.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}-[\\dX]$|^\\d{9}$')], verbose_name='RG')),
                ('emissor', models.CharField(blank=True, max_length=6, verbose_name='Orgão Emissor')),
                ('uf', models.CharField(blank=True, choices=[('', 'Estado'), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MG'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2)),
                ('ctps', models.CharField(blank=True, max_length=11, null=True)),
                ('reservista', models.CharField(blank=True, max_length=12, verbose_name='Certificado de Reservista')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=15, verbose_name='Título de Eleitor')),
                ('anexo_cpf', models.FileField(blank=True, null=True, upload_to='documentos/cpf/')),
                ('anexo_ctps', models.FileField(blank=True, null=True, upload_to='documentos/ctps/')),
                ('anexo_pis', models.FileField(blank=True, null=True, upload_to='documentos/pis/')),
                ('anexo_rg', models.FileField(blank=True, null=True, upload_to='documentos/rg/')),
                ('centro_custo', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos Pessoais',
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Cargo')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='departamento_pessoal.cbos')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('estatus', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Afastado'), (3, 'Desligado'), (4, 'Férias')], default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('documentos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_documentos', to='departamento_pessoal.documentos')),
                ('logradouro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logradouro.logradouro')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionarios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_funcionario', to='departamento_pessoal.funcionarios'),
        ),
        migrations.CreateModel(
            name='Admissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'Registro CLT'), ('PJ', 'Pessoa Jurídica'), ('EST', 'Estagiário'), ('APR', 'Aprendiz')], default='CLT', max_length=3)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Horário de entrada')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Horário de saída')),
                ('dias_trabalhado', models.CharField(blank=True, max_length=27)),
                ('dias_semana', models.CharField(blank=True, max_length=1)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissoes', to='departamento_pessoal.cargos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissoes', to='departamento_pessoal.departamentos')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admissao', to='departamento_pessoal.funcionarios')),
            ],
            options={
                'verbose_name': 'Admissão',
                'verbose_name_plural': 'Admissões',
                'db_table': 'admissao',
                'ordering': ['-data_admissao'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='documentos',
            unique_together={('nome', 'sigla')},
        ),
    ]
