# Generated by Django 5.2 on 2025-06-27 12:28

import departamento_pessoal.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0001_initial'),
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissao',
            name='dias_trabalhado',
        ),
        migrations.RemoveField(
            model_name='admissao',
            name='documento_principal',
        ),
        migrations.AlterUniqueTogether(
            name='documentos',
            unique_together={('funcionario', 'tipo')},
        ),
        migrations.AddField(
            model_name='documentos',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='orgao_emissor_rg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Órgão Emissor do RG'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='uf_emissor_rg',
            field=models.CharField(blank=True, choices=[('', 'Estado'), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MG'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF Emissor do RG'),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='dias_semana',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[departamento_pessoal.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='ctps',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CTPS (Número/Série)'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='pis',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[departamento_pessoal.validators.validate_pis], verbose_name='PIS/PASEP'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CTPS', 'Carteira de Trabalho (CTPS)'), ('PIS', 'PIS/PASEP'), ('TIT', 'Título de Eleitor'), ('RES', 'Certificado de Reservista'), ('OUT', 'Outro')], max_length=4, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este email já está em uso.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='logradouro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logradouro.logradouro'),
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='anexo_cpf',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='anexo_ctps',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='anexo_pis',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='anexo_rg',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='emissor',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='uf',
        ),
    ]
