# Generated by Django 5.2 on 2025-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0001_initial'),
    ]

    operations = [

    ]
