# Generated by Django 5.2 on 2025-07-05 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
        migrations.AddField(
            model_name='documento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='departamento_pessoal.funcionario'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('funcionario', 'tipo')},
        ),
    ]
