# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_initial'),
        ('departamento_pessoal', '0001_initial'),
        ('seguranca_trabalho', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='documento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_filial', to='departamento_pessoal.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='departamento_pessoal.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_alocados', to='cliente.cliente', verbose_name='Cliente/Contrato'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='departamento_pessoal.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(blank=True, help_text='Função desempenhada pelo funcionário para fins de SST e Matriz de EPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='seguranca_trabalho.funcao', verbose_name='Função (SST)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
        migrations.AddField(
            model_name='documento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('funcionario', 'tipo_documento')},
        ),
    ]
