# Generated by Django 5.2 on 2025-08-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0001_initial'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamento', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='documento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='usuario.filial'),
        ),
    ]
