# Generated by Django 5.2 on 2025-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0002_alter_funcionario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CTPS', 'CTPS'), ('CNH', 'CNH'), ('PIS', 'PIS'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
