# Generated by Django 5.2 on 2025-05-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0002_alter_departamentos_options_alter_documentos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='documentos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento_pessoal.documentos', verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
