# Generated by Django 5.2 on 2025-08-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_filial'),
        ('departamento_pessoal', '0002_cargo_filial_departamento_filial_documento_filial_and_more'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cbo',
            field=models.CharField(blank=True, help_text='Classificação Brasileira de Ocupações', max_length=10, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='documentos_funcionarios/', verbose_name='Arquivo Anexado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_filial', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CTPS', 'CTPS - Carteira de Trabalho'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='departamento_pessoal.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_alocados', to='cliente.cliente', verbose_name='Cliente/Contrato de Alocação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='departamento_pessoal.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='usuario.filial', verbose_name='Filial de Lotação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=10, verbose_name='Status'),
        ),
    ]
