# Generated by Django 5.2 on 2026-02-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0002_initial'),
        ('seguranca_trabalho', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_dp', related_query_name='documento_dp', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(blank=True, help_text='Função desempenhada pelo funcionário para fins de SST e Matriz de EPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_dp', related_query_name='funcionario_dp', to='seguranca_trabalho.funcao', verbose_name='Função (SST)'),
        ),
    ]
