# Generated by Django 4.2.16 on 2026-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0003_alter_documento_funcionario_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='registro',
            field=models.PositiveIntegerField(default=0, verbose_name='Registro de Departamento'),
        ),
    ]
