# Generated by Django 5.2 on 2025-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0003_alter_funcionarios_documentos_and_more'),
    ]

    operations = [

    ]
