# Generated by Django 5.2 on 2025-09-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0003_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
    ]
