# Generated by Django 5.2 on 2025-08-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0003_alter_documento_options_alter_cargo_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto_3x4',
            field=models.ImageField(blank=True, help_text='Faça o upload de uma foto 3x4 do funcionário.', null=True, upload_to='fotos_3x4/', verbose_name='Foto 3x4'),
        ),
    ]
