# Generated by Django 4.2.29 on 2026-03-18 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_filial_options'),
        ('departamento_pessoal', '0004_departamento_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['funcionario__nome_completo', 'tipo_documento'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documento',
            name='aso_apto',
            field=models.BooleanField(default=True, help_text='Resultado: Apto ou Inapto', null=True, verbose_name='Apto?'),
        ),
        migrations.AddField(
            model_name='documento',
            name='aso_medico_crm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM do Médico'),
        ),
        migrations.AddField(
            model_name='documento',
            name='aso_medico_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Médico Responsável'),
        ),
        migrations.AddField(
            model_name='documento',
            name='aso_proximo_exame',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Exame'),
        ),
        migrations.AddField(
            model_name='documento',
            name='aso_tipo_exame',
            field=models.CharField(blank=True, choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('retorno', 'Retorno ao Trabalho'), ('mudanca', 'Mudança de Função'), ('demissional', 'Demissional')], max_length=20, null=True, verbose_name='Tipo de Exame ASO'),
        ),
        migrations.AddField(
            model_name='documento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='documento',
            name='certificado_curso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Curso'),
        ),
        migrations.AddField(
            model_name='documento',
            name='certificado_instituicao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de Ensino'),
        ),
        migrations.AddField(
            model_name='documento',
            name='certificado_nivel',
            field=models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Curso Técnico'), ('graduacao', 'Graduação'), ('pos', 'Pós-Graduação / MBA'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('curso_livre', 'Curso Livre / Extensão')], max_length=20, null=True, verbose_name='Nível/Grau'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cnh_categoria',
            field=models.CharField(blank=True, choices=[('A', 'A - Motos'), ('B', 'B - Carros'), ('AB', 'AB - Motos e Carros'), ('C', 'C - Caminhões'), ('D', 'D - Ônibus'), ('E', 'E - Carretas / Articulados'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=3, null=True, verbose_name='Categoria da CNH'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cnh_numero_registro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº de Registro CNH'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cnh_observacoes_detran',
            field=models.CharField(blank=True, help_text='Ex: Exerce Atividade Remunerada (EAR)', max_length=200, null=True, verbose_name='Observações DETRAN'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cnh_primeira_habilitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da 1ª Habilitação'),
        ),
        migrations.AddField(
            model_name='documento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 18, 0, 42, 26, 382262, tzinfo=datetime.timezone.utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='ctps_digital',
            field=models.BooleanField(default=False, help_text='Marque se a CTPS é digital (sem número físico)', verbose_name='CTPS Digital?'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ctps_serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Série da CTPS'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ctps_uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF da CTPS'),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Deixe em branco se não tem validade', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nr_carga_horaria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária (horas)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nr_instituicao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição / Empresa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nr_numero',
            field=models.CharField(blank=True, help_text='Ex: NR-10, NR-35, NR-33', max_length=10, null=True, verbose_name='Número da NR'),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='documento',
            name='orgao_expedidor',
            field=models.CharField(blank=True, help_text='Ex: SSP-MG, DETRAN-SP, CREA-MG', max_length=50, null=True, verbose_name='Órgão Expedidor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='outro_descricao',
            field=models.CharField(blank=True, help_text='Descreva o tipo de documento quando "Outro"', max_length=200, null=True, verbose_name='Descrição do Documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='passaporte_pais_emissao',
            field=models.CharField(blank=True, default='Brasil', max_length=100, null=True, verbose_name='País de Emissão'),
        ),
        migrations.AddField(
            model_name='documento',
            name='registro_especialidade',
            field=models.CharField(blank=True, help_text='Ex: Engenharia Mecânica e de Segurança do Trabalho', max_length=200, null=True, verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='documento',
            name='registro_orgao',
            field=models.CharField(blank=True, help_text='Ex: CREA, CRM, OAB, CRN, COREN', max_length=50, null=True, verbose_name='Órgão de Classe'),
        ),
        migrations.AddField(
            model_name='documento',
            name='reservista_categoria',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoria Reservista'),
        ),
        migrations.AddField(
            model_name='documento',
            name='reservista_regiao_militar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Região Militar'),
        ),
        migrations.AddField(
            model_name='documento',
            name='rg_naturalidade',
            field=models.CharField(blank=True, help_text='Ex: Belo Horizonte/MG', max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='documento',
            name='rg_nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='documento',
            name='rg_nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='documento',
            name='titulo_municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='documento',
            name='titulo_secao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Seção Eleitoral'),
        ),
        migrations.AddField(
            model_name='documento',
            name='titulo_zona',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona Eleitoral'),
        ),
        migrations.AddField(
            model_name='documento',
            name='uf_expedidor',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF do Expedidor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='anexo',
            field=models.FileField(blank=True, help_text='PDF ou imagem (máx. 10MB)', null=True, upload_to='documentos_funcionarios/%Y/%m/', verbose_name='Arquivo Anexado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_dp_filial', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.CharField(blank=True, help_text='Número principal do documento', max_length=50, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG / Carteira de Identidade'), ('CNH', 'CNH - Carteira de Habilitação'), ('CTPS', 'CTPS - Carteira de Trabalho'), ('PIS', 'PIS / PASEP / NIT'), ('TITULO', 'Título de Eleitor'), ('RESERVISTA', 'Certificado de Reservista'), ('CERTIDAO_NASC', 'Certidão de Nascimento'), ('CERTIDAO_CAS', 'Certidão de Casamento'), ('PASSAPORTE', 'Passaporte'), ('RNE', 'RNE / CRNM (Estrangeiro)'), ('REGISTRO_CLASSE', 'Registro de Classe (CREA, CRM, OAB, etc.)'), ('CERTIFICADO', 'Certificado / Diploma'), ('ASO', 'ASO - Atestado de Saúde Ocupacional'), ('NR', 'Certificado de NR (NR-10, NR-35, etc.)'), ('COMPROVANTE_END', 'Comprovante de Endereço'), ('COMP_ESCOLAR', 'Comprovante de Escolaridade'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('funcionario', 'tipo_documento', 'numero')},
        ),
        migrations.AlterModelTable(
            name='documento',
            table='departamento_pessoal_documento',
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
