# Generated by Django 5.2 on 2025-05-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0004_alter_departamentos_options_alter_documentos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='admissao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='departamento_pessoal.admissao', verbose_name='Dados de Admissão'),
        ),
    ]
