# Generated by Django 5.2 on 2025-09-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0004_alter_documento_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='departamento_pessoal.funcionario', verbose_name='Funcionário'),
        ),
    ]
