# Generated by Django 5.2.13 on 2026-04-13 12:34

import core.upload
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0005_reestruturar_documento_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='anexo',
            field=models.FileField(blank=True, help_text='PDF ou imagem (máx. 10 MB).', null=True, upload_to=core.upload.UploadPath('departamento_pessoal'), validators=[core.validators.SecureFileValidator(app_name='departamento_pessoal')], verbose_name='Arquivo Anexado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto_3x4',
            field=models.ImageField(blank=True, help_text='Imagem JPG, PNG ou WebP (máx. 4 MB).', null=True, upload_to=core.upload.UploadPath('departamento_pessoal_foto'), validators=[core.validators.SecureImageValidator(app_name='departamento_pessoal_foto')], verbose_name='Foto 3x4'),
        ),
    ]
