# Generated by Django 5.2 on 2025-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0005_alter_funcionarios_admissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['nome'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name': 'Documento Pessoal', 'verbose_name_plural': 'Documentos Pessoais'},
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('OPR', 'Operacional'), ('COM', 'Comercial'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('PCM', 'Planejamento'), ('TST', 'Segurança do Trabalho'), ('DP', 'Departamento Pessoal')], default='ADM', max_length=3, verbose_name='Tipo de Departamento'),
        ),
        migrations.AddIndex(
            model_name='departamentos',
            index=models.Index(fields=['nome'], name='idx_departamento_nome'),
        ),
        migrations.AddIndex(
            model_name='departamentos',
            index=models.Index(fields=['sigla'], name='idx_departamento_sigla'),
        ),
        migrations.AddIndex(
            model_name='departamentos',
            index=models.Index(fields=['tipo'], name='idx_departamento_tipo'),
        ),
        migrations.AddConstraint(
            model_name='departamentos',
            constraint=models.UniqueConstraint(fields=('nome', 'sigla'), name='unique_departamento_nome_sigla'),
        ),
        migrations.AlterModelTable(
            name='departamentos',
            table='departamentos',
        ),
        migrations.AlterModelTable(
            name='documentos',
            table='documentos',
        ),
    ]
