# Generated by Django 5.2 on 2025-09-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0005_alter_documento_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tipo',
            new_name='tipo_documento',
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('funcionario', 'tipo_documento')},
        ),
    ]
