# Generated by Django 5.2.13 on 2026-04-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0006_alter_documento_anexo_alter_funcionario_foto_3x4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome_completo'], 'permissions': [('view_all_departamento_pessoal', 'Pode ver todos os dados do DP (global)')], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
