# Generated by Django 5.2 on 2025-09-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0007_filial_alter_documento_filial'),
        ('seguranca_trabalho', '0010_remove_equipamento_fornecedor_padrao_and_more'),
        ('usuario', '0004_groupcardpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(blank=True, help_text='Função desempenhada pelo funcionário para fins de SST e Matriz de EPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='seguranca_trabalho.funcao', verbose_name='Função (SST)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
