# Generated by Django 4.2.28 on 2026-04-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0008_alter_funcionario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome_completo'], 'permissions': [('view_all_departamento_pessoal', 'Pode ver todos os dados do DP (global)'), ('view_salario', 'Pode ver salario')], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
