# Generated by Django 5.1.15 on 2026-09-03 15:06

import core.validators
import django.db.models.deletion
import django_cryptography.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_options'),
        ('departamento_pessoal', '0009_alter_funcionario_options'),
        ('seguranca_trabalho', '0010_movimentacaoestoque_pedido_compra_origem'),
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documento',
            name='numero_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Número principal do documento', max_length=50, null=True, verbose_name='Número do Documento')),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('funcionario', 'tipo_documento', 'numero_hash')},
        ),
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG / Carteira de Identidade'), ('CNH', 'CNH - Carteira de Habilitação'), ('CTPS', 'CTPS - Carteira de Trabalho'), ('PIS', 'PIS / PASEP / NIT'), ('TITULO', 'Título de Eleitor'), ('RESERVISTA', 'Certificado de Reservista'), ('CERTIDAO_NASC', 'Certidão de Nascimento'), ('CERTIDAO_CAS', 'Certidão de Casamento'), ('PASSAPORTE', 'Passaporte'), ('RNE', 'RNE / CRNM (Estrangeiro)'), ('REGISTRO_CLASSE', 'Registro de Classe (CREA, CRM, OAB, etc.)'), ('CERTIFICADO', 'Certificado / Diploma'), ('ASO', 'ASO - Atestado de Saúde Ocupacional'), ('NR', 'Certificado de NR (NR-10, NR-35, etc.)'), ('COMPROVANTE_END', 'Comprovante de Endereço'), ('COMP_ESCOLAR', 'Comprovante de Escolaridade'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Número principal do documento', max_length=50, null=True, verbose_name='Número do Documento'))),
                ('numero_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(blank=True, help_text='Deixe em branco se não tem validade', null=True, verbose_name='Data de Validade')),
                ('orgao_expedidor', models.CharField(blank=True, help_text='Ex: SSP-MG, DETRAN-SP, CREA-MG', max_length=50, null=True, verbose_name='Órgão Expedidor')),
                ('uf_expedidor', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF do Expedidor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('anexo', models.TextField(blank=True, help_text='PDF ou imagem (máx. 10 MB).', max_length=100, null=True, validators=[core.validators.SecureFileValidator(app_name='departamento_pessoal')], verbose_name='Arquivo Anexado')),
                ('rg_nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('rg_nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                ('rg_naturalidade', models.CharField(blank=True, help_text='Ex: Belo Horizonte/MG', max_length=100, null=True, verbose_name='Naturalidade')),
                ('cnh_categoria', models.CharField(blank=True, choices=[('A', 'A - Motos'), ('B', 'B - Carros'), ('AB', 'AB - Motos e Carros'), ('C', 'C - Caminhões'), ('D', 'D - Ônibus'), ('E', 'E - Carretas / Articulados'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=3, null=True, verbose_name='Categoria da CNH')),
                ('cnh_numero_registro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº de Registro CNH')),
                ('cnh_primeira_habilitacao', models.DateField(blank=True, null=True, verbose_name='Data da 1ª Habilitação')),
                ('cnh_observacoes_detran', models.CharField(blank=True, help_text='Ex: Exerce Atividade Remunerada (EAR)', max_length=200, null=True, verbose_name='Observações DETRAN')),
                ('ctps_serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Série da CTPS')),
                ('ctps_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF da CTPS')),
                ('ctps_digital', models.BooleanField(default=False, help_text='Marque se a CTPS é digital (sem número físico)', verbose_name='CTPS Digital?')),
                ('titulo_zona', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona Eleitoral')),
                ('titulo_secao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seção Eleitoral')),
                ('titulo_municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('reservista_categoria', models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoria Reservista')),
                ('reservista_regiao_militar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Região Militar')),
                ('registro_orgao', models.CharField(blank=True, help_text='Ex: CREA, CRM, OAB, CRN, COREN', max_length=50, null=True, verbose_name='Órgão de Classe')),
                ('registro_especialidade', models.CharField(blank=True, help_text='Ex: Engenharia Mecânica e de Segurança do Trabalho', max_length=200, null=True, verbose_name='Especialidade')),
                ('aso_tipo_exame', models.CharField(blank=True, choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('retorno', 'Retorno ao Trabalho'), ('mudanca', 'Mudança de Função'), ('demissional', 'Demissional')], max_length=20, null=True, verbose_name='Tipo de Exame ASO')),
                ('aso_apto', models.BooleanField(default=True, help_text='Resultado: Apto ou Inapto', null=True, verbose_name='Apto?')),
                ('aso_medico_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Médico Responsável')),
                ('aso_medico_crm', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM do Médico')),
                ('aso_proximo_exame', models.DateField(blank=True, null=True, verbose_name='Próximo Exame')),
                ('nr_numero', models.CharField(blank=True, help_text='Ex: NR-10, NR-35, NR-33', max_length=10, null=True, verbose_name='Número da NR')),
                ('nr_carga_horaria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária (horas)')),
                ('nr_instituicao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição / Empresa')),
                ('certificado_nivel', models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Curso Técnico'), ('graduacao', 'Graduação'), ('pos', 'Pós-Graduação / MBA'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('curso_livre', 'Curso Livre / Extensão')], max_length=20, null=True, verbose_name='Nível/Grau')),
                ('certificado_curso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Curso')),
                ('certificado_instituicao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de Ensino')),
                ('passaporte_pais_emissao', models.CharField(blank=True, default='Brasil', max_length=100, null=True, verbose_name='País de Emissão')),
                ('outro_descricao', models.CharField(blank=True, help_text='Descreva o tipo de documento quando "Outro"', max_length=200, null=True, verbose_name='Descrição do Documento')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('filial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.filial', verbose_name='Filial')),
                ('funcionario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='documento_dp', to='departamento_pessoal.funcionario', verbose_name='Funcionário')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Documento',
                'verbose_name_plural': 'historical Documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFuncionario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo')),
                ('email_pessoal', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email Pessoal')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('matricula', models.CharField(db_index=True, max_length=20, verbose_name='Matrícula')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salário Base')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('foto_3x4', models.TextField(blank=True, help_text='Imagem JPG, PNG ou WebP (máx. 4 MB).', max_length=100, null=True, validators=[core.validators.SecureImageValidator(app_name='departamento_pessoal_foto')], verbose_name='Foto 3x4')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamento_pessoal.cargo', verbose_name='Cargo')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.cliente', verbose_name='Cliente/Contrato')),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamento_pessoal.departamento', verbose_name='Departamento')),
                ('filial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.filial', verbose_name='Filial')),
                ('funcao', models.ForeignKey(blank=True, db_constraint=False, help_text='Função desempenhada pelo funcionário para fins de SST e Matriz de EPI.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='funcionario_dp', to='seguranca_trabalho.funcao', verbose_name='Função (SST)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'historical Funcionário',
                'verbose_name_plural': 'historical Funcionários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
