# Generated by Django 5.1.15 on 2026-09-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0010_alter_documento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome_completo'], 'permissions': [('view_all_departamento_pessoal', 'Pode ver todos os dados do DP (global)'), ('view_salario', 'Pode ver salario'), ('view_documento_completo', 'Pode ver número completo de documentos sensíveis')], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
