# Generated by Django 5.1.6 on 2025-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('estados', models.CharField(choices=[('AC', 'Acre'), 
                                                      ('AL', 'Alagoas'), 
                                                      ('AP', 'Amapá'), 
                                                      ('AM', 'Amazonas'), 
                                                      ('BA', 'Bahia'), 
                                                      ('CE', 'Ceará'), 
                                                      ('DF', 'Distrito Federal'), 
                                                      ('ES', 'Espírito Santo'), 
                                                      ('GO', 'Goiás'), 
                                                      ('MA', 'Maranhão'),
                                                      ('MT', 'Mato Grosso'), 
                                                      ('MS', 'Mato Grosso do Sul'), 
                                                      ('MG', 'Minas Gerais'), 
                                                      ('PA', 'Pará'), 
                                                      ('PB', 'Paraíba'), 
                                                      ('PR', 'Paraná'), 
                                                      ('PE', 'Pernambuco'), 
                                                      ('PI', 'Piauí'), 
                                                      ('RJ', 'Rio de Janeiro'), 
                                                      ('RN', 'Rio Grande do Norte'), 
                                                      ('RS', 'Rio Grande do Sul'), 
                                                      ('RO', 'Rondônia'), 
                                                      ('RR', 'Roraima'), 
                                                      ('SC', 'Santa Catarina'), 
                                                      ('SP', 'São Paulo'), 
                                                      ('SE', 'Sergipe'), 
                                                      ('TO', 'Tocantins')
                ], max_length=2)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
