# Generated by Django 5.1.6 on 2025-03-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_logradouro_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logradouro',
            table=None,
        ),
    ]
