# Generated by Django 5.1.6 on 2025-04-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_logradouro_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logradouro',
            table='logradouro',
        ),
    ]
