# Generated by Django 5.1.6 on 2025-04-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_logradouro_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logradouro',
            table=None,
        ),
    ]
