# Generated by Django 5.1.6 on 2025-04-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_logradouro_table'),
    ]

    operations = [
    ]
