# Generated by Django 5.2 on 2026-02-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_filial'),
        ('pgr_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgrdocumento',
            name='escopo',
            field=models.TextField(blank=True, null=True, verbose_name='Escopo'),
        ),
        migrations.AddField(
            model_name='pgrdocumento',
            name='metodologia_avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Metodologia de Avaliação'),
        ),
        migrations.AddField(
            model_name='pgrdocumento',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo do PGR'),
        ),
        migrations.AlterField(
            model_name='ambientetrabalho',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes_trabalho_pgr', related_query_name='ambiente_trabalho_pgr', to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pgrdocumento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_pgr', related_query_name='documento_pgr', to='cliente.cliente', verbose_name='Empresa Cliente'),
        ),
    ]
