# Generated by Django 5.2 on 2026-02-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_filial'),
        ('pgr_gestao', '0002_pgrdocumento_escopo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGRSecaoTextoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('documento_base', '2. Documento Base'), ('documento_base_metas', '2. Documento Base - Metas'), ('documento_base_objetivo', '2. Documento Base - Objetivo Geral'), ('definicoes', '3. Definições'), ('estrutura_pgr', '4. Estrutura do PGR'), ('estrutura_requisitos', '4. Estrutura - Requisitos Legais'), ('estrutura_estrategia', '4. Estrutura - Estratégia e Metodologia'), ('estrutura_registro', '4. Estrutura - Forma de Registro'), ('estrutura_periodicidade', '4. Estrutura - Periodicidade'), ('estrutura_implantacao', '4. Estrutura - Implantação Cronograma'), ('estrutura_eficacia', '4. Estrutura - Análise da Eficácia'), ('responsabilidades', '5. Definição das Responsabilidades'), ('resp_organizacao', '5. Responsabilidades - Da Organização'), ('resp_informacao', '5. Responsabilidades - Da Informação'), ('resp_procedimentos', '5. Responsabilidades - Procedimentos'), ('resp_seguranca', '5. Responsabilidades - Da Segurança do Trabalho'), ('resp_cipa', '5. Responsabilidades - CIPA/Designado'), ('resp_medicina', '5. Responsabilidades - Da Medicina do Trabalho'), ('resp_supervisao', '5. Responsabilidades - Da Supervisão'), ('resp_empregados', '5. Responsabilidades - Dos Empregados'), ('diretrizes', '6. Diretrizes'), ('desenvolvimento', '7. Desenvolvimento do PGR'), ('metodologia_avaliacao', '8. Metodologia de Avaliação'), ('metodo_ruido', '8. Metodologia - Agente Físico Ruído'), ('metodo_calor', '8. Metodologia - Agente Físico Calor'), ('metodo_quimico', '8. Metodologia - Agentes Químicos'), ('metodo_biologico', '8. Metodologia - Agentes Biológicos'), ('metodo_ergonomico', '8. Metodologia - Agentes Ergonômicos'), ('metodo_mecanico', '8. Metodologia - Agentes Mecânicos'), ('inventario_riscos_intro', '9. Inventário de Riscos - Introdução'), ('plano_acao', '10. Plano de Ação'), ('medidas_protecao', '11. Medidas de Proteção'), ('medidas_epc', '11. Medidas - Proteção Coletiva'), ('medidas_administrativas', '11. Medidas - Administrativas'), ('medidas_epi', '11. Medidas - EPI'), ('medidas_uso_epi', '11. Medidas - Uso, Guarda e Conservação EPI'), ('divulgacao', '13. Divulgação do Programa'), ('recomendacoes', '14. Recomendações Gerais'), ('legislacao', '15. Legislação Complementar'), ('custom', 'Seção Personalizada')], max_length=50, unique=True, verbose_name='Seção')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Seção')),
                ('conteudo_padrao', models.TextField(help_text='Texto padrão da seção. Use {empresa} para substituir pelo nome da empresa.', verbose_name='Conteúdo Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texto Padrão de Seção',
                'verbose_name_plural': 'Textos Padrão de Seções',
                'db_table': 'pgr_secao_texto_padrao',
                'ordering': ['secao'],
            },
        ),
        migrations.AlterField(
            model_name='ambientetrabalho',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes_trabalho_pgr', related_query_name='ambiente_trabalho_pgr', to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='gesgrupoexposicao',
            name='ambiente_trabalho',
            field=models.ForeignKey(blank=True, default='ambiente_trabalho', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_exposicao', to='pgr_gestao.ambientetrabalho', verbose_name='Ambiente de Trabalho'),
        ),
        migrations.AlterField(
            model_name='pgrdocumento',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_pgr', related_query_name='documento_pgr', to='cliente.cliente', verbose_name='Empresa Cliente'),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='ambiente_trabalho',
            field=models.ForeignKey(blank=True, default='ambiente_trabalho', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riscos', to='pgr_gestao.localprestacaoservico', verbose_name='Ambiente de Trabalho'),
        ),
        migrations.CreateModel(
            name='PGRSecaoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('documento_base', '2. Documento Base'), ('documento_base_metas', '2. Documento Base - Metas'), ('documento_base_objetivo', '2. Documento Base - Objetivo Geral'), ('definicoes', '3. Definições'), ('estrutura_pgr', '4. Estrutura do PGR'), ('estrutura_requisitos', '4. Estrutura - Requisitos Legais'), ('estrutura_estrategia', '4. Estrutura - Estratégia e Metodologia'), ('estrutura_registro', '4. Estrutura - Forma de Registro'), ('estrutura_periodicidade', '4. Estrutura - Periodicidade'), ('estrutura_implantacao', '4. Estrutura - Implantação Cronograma'), ('estrutura_eficacia', '4. Estrutura - Análise da Eficácia'), ('responsabilidades', '5. Definição das Responsabilidades'), ('resp_organizacao', '5. Responsabilidades - Da Organização'), ('resp_informacao', '5. Responsabilidades - Da Informação'), ('resp_procedimentos', '5. Responsabilidades - Procedimentos'), ('resp_seguranca', '5. Responsabilidades - Da Segurança do Trabalho'), ('resp_cipa', '5. Responsabilidades - CIPA/Designado'), ('resp_medicina', '5. Responsabilidades - Da Medicina do Trabalho'), ('resp_supervisao', '5. Responsabilidades - Da Supervisão'), ('resp_empregados', '5. Responsabilidades - Dos Empregados'), ('diretrizes', '6. Diretrizes'), ('desenvolvimento', '7. Desenvolvimento do PGR'), ('metodologia_avaliacao', '8. Metodologia de Avaliação'), ('metodo_ruido', '8. Metodologia - Agente Físico Ruído'), ('metodo_calor', '8. Metodologia - Agente Físico Calor'), ('metodo_quimico', '8. Metodologia - Agentes Químicos'), ('metodo_biologico', '8. Metodologia - Agentes Biológicos'), ('metodo_ergonomico', '8. Metodologia - Agentes Ergonômicos'), ('metodo_mecanico', '8. Metodologia - Agentes Mecânicos'), ('inventario_riscos_intro', '9. Inventário de Riscos - Introdução'), ('plano_acao', '10. Plano de Ação'), ('medidas_protecao', '11. Medidas de Proteção'), ('medidas_epc', '11. Medidas - Proteção Coletiva'), ('medidas_administrativas', '11. Medidas - Administrativas'), ('medidas_epi', '11. Medidas - EPI'), ('medidas_uso_epi', '11. Medidas - Uso, Guarda e Conservação EPI'), ('divulgacao', '13. Divulgação do Programa'), ('recomendacoes', '14. Recomendações Gerais'), ('legislacao', '15. Legislação Complementar'), ('custom', 'Seção Personalizada')], max_length=50, verbose_name='Seção')),
                ('titulo_customizado', models.CharField(blank=True, help_text='Deixe em branco para usar o título padrão da seção', max_length=255, null=True, verbose_name='Título Customizado')),
                ('conteudo', models.TextField(blank=True, help_text='Texto da seção. Deixe em branco para usar o texto padrão.', null=True, verbose_name='Conteúdo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem em que a seção aparece no PDF', verbose_name='Ordem de Exibição')),
                ('incluir_no_pdf', models.BooleanField(default=True, help_text='Desmarque para ocultar esta seção do PDF', verbose_name='Incluir no PDF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pgr_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes_texto', to='pgr_gestao.pgrdocumento', verbose_name='Documento PGR')),
            ],
            options={
                'verbose_name': 'Seção de Texto do PGR',
                'verbose_name_plural': 'Seções de Texto do PGR',
                'db_table': 'pgr_secao_texto',
                'ordering': ['pgr_documento', 'ordem', 'secao'],
                'unique_together': {('pgr_documento', 'secao')},
            },
        ),
    ]
