# Generated by Django 5.2 on 2026-02-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgr_gestao', '0003_pgrsecaotextopadrao_alter_ambientetrabalho_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesgrupoexposicao',
            name='ambiente_trabalho',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_exposicao', to='pgr_gestao.ambientetrabalho', verbose_name='Ambiente de Trabalho'),
        ),
        migrations.AlterField(
            model_name='gesgrupoexposicao',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para inativar este GES no PGR. GES inativo não aparece no relatório PDF.', verbose_name='GES Ativo'),
        ),
    ]
