# Generated by Django 5.2 on 2026-02-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_riscos', '0004_tiporisco'),
        ('pgr_gestao', '0004_alter_gesgrupoexposicao_ambiente_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riscoidentificado',
            name='tipo_risco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riscos_pgr', to='gestao_riscos.tiporisco', verbose_name='Tipo de Risco'),
        ),
    ]
