# Generated by Django 5.2 on 2026-02-19 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgr_gestao', '0005_alter_riscoidentificado_tipo_risco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(upload_to='pgr/planos_acao/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('plano_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='pgr_gestao.planoacaopgr', verbose_name='Plano de Ação')),
            ],
            options={
                'verbose_name': 'Anexo do Plano de Ação',
                'verbose_name_plural': 'Anexos dos Planos de Ação',
                'db_table': 'pgr_anexo_plano_acao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
