# Generated by Django 5.2 on 2026-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgr_gestao', '0006_anexoplanoacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoquantitativa',
            name='unidade_medida',
            field=models.CharField(choices=[('dB', 'dB (Decibéis)'), ('dB(A)', 'dB(A) (Decibéis ponderados em A)'), ('ppm', 'ppm (Partes por Milhão)'), ('mg/m³', 'mg/m³ (Miligrama por Metro Cúbico)'), ('f/cm³', 'f/cm³ (Fibras por Centímetro Cúbico)'), ('mW/cm²', 'mW/cm² (Miliwatt por Centímetro Quadrado)'), ('lux', 'Lux (Iluminância)'), ('ºC', '°C (Graus Celsius)'), ('IBUTG', 'IBUTG (Índice de Bulbo Úmido)'), ('m/s²', 'm/s² (Aceleração - Vibração)'), ('%', '% (Percentual)'), ('Bq', 'Bq (Becquerel - Radiação)'), ('mSv', 'mSv (Milisievert - Radiação)'), ('UR', 'UR (Umidade Relativa %)'), ('m/s', 'm/s (Metros por Segundo - Velocidade do Ar)'), ('outro', 'Outro')], max_length=50, verbose_name='Unidade de Medida'),
        ),
    ]
