# Generated by Django 5.2 on 2026-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgr_gestao', '0008_pgrrevisao_ativo_pgrrevisao_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentoplanoacao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Acompanhamento'),
        ),
        migrations.AlterField(
            model_name='acompanhamentoplanoacao',
            name='evidencias',
            field=models.TextField(blank=True, null=True, verbose_name='Evidências/Comprovações'),
        ),
        migrations.AlterField(
            model_name='gesgrupoexposicao',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='medidacontrole',
            name='eficacia_esperada',
            field=models.CharField(blank=True, max_length=100, verbose_name='Eficácia Esperada'),
        ),
        migrations.AlterField(
            model_name='medidacontrole',
            name='prioridade',
            field=models.PositiveIntegerField(default=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='pgrrevisao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='pgrrevisao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='pgrsecaotexto',
            name='incluir_no_pdf',
            field=models.BooleanField(default=True, verbose_name='Incluir no PDF'),
        ),
        migrations.AlterField(
            model_name='pgrsecaotexto',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='pgrsecaotextopadrao',
            name='conteudo_padrao',
            field=models.TextField(help_text='Texto padrão. Use {empresa} para substituir pelo nome da empresa.', verbose_name='Conteúdo Padrão'),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='classificacao_risco',
            field=models.CharField(choices=[('negligenciavel', 'Negligenciável'), ('marginal', 'Marginal'), ('moderado', 'Moderado'), ('muito_grave', 'Muito Grave'), ('critico', 'Crítico')], max_length=20, verbose_name='Classificação do Risco'),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='severidade_s',
            field=models.CharField(choices=[('A', 'A - Negligenciável'), ('B', 'B - Marginal'), ('C', 'C - Moderado'), ('D', 'D - Muito Grave'), ('E', 'E - Crítico')], max_length=1, verbose_name='Severidade (S)'),
        ),
    ]
