# Generated by Django 4.2.16 on 2026-03-01 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgr_gestao', '0009_alter_acompanhamentoplanoacao_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anexo', models.CharField(choices=[('analise_ruido', 'Análise Quantitativa de Ruído'), ('analise_calor', 'Análise Quantitativa de Calor'), ('analise_quimica', 'Análise Quantitativa de Agentes Químicos'), ('analise_vibração', 'Análise Quantitativa de Vibração'), ('analise_iluminacao', 'Análise de Iluminância'), ('analise_biologica', 'Análise de Agentes Biológicos'), ('laudo_insalubridade', 'Laudo de Insalubridade'), ('laudo_periculosidade', 'Laudo de Periculosidade'), ('laudo_ergonomico', 'Laudo Ergonômico'), ('aet', 'Análise Ergonômica do Trabalho (AET)'), ('ppra', 'PPRA – Programa de Prevenção de Riscos Ambientais'), ('pcmso', 'PCMSO – Programa de Controle Médico'), ('ltcat', 'LTCAT – Laudo Técnico das Condições do Ambiente'), ('certificado_calibracao', 'Certificado de Calibração de Equipamentos'), ('art', 'ART – Anotação de Responsabilidade Técnica'), ('mapa_risco', 'Mapa de Risco'), ('planta_baixa', 'Planta Baixa / Layout'), ('fotografias', 'Registro Fotográfico'), ('treinamento', 'Certificado / Registro de Treinamento'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de Anexo')),
                ('numero_romano', models.CharField(blank=True, help_text='Ex: I, II, III, IV, V...', max_length=10, verbose_name='Número do Anexo')),
                ('titulo', models.CharField(help_text='Ex: ANÁLISE QUANTITATIVA DE RUÍDO', max_length=300, verbose_name='Título do Anexo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou observações sobre este anexo', verbose_name='Descrição')),
                ('arquivo', models.FileField(help_text='PDF, DOC, DOCX, XLS, XLSX, JPG, PNG (máx. 50MB)', upload_to='pgr/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('nome_arquivo_original', models.CharField(blank=True, max_length=500, verbose_name='Nome Original do Arquivo')),
                ('tamanho_arquivo', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('incluir_no_pdf', models.BooleanField(default=True, help_text='Se marcado, aparecerá listado nos anexos do relatório PDF', verbose_name='Incluir como Anexo no PDF do PGR')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem dos anexos no relatório', verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('pgr_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_pgr', to='pgr_gestao.pgrdocumento', verbose_name='Documento PGR')),
            ],
            options={
                'verbose_name': 'Anexo do PGR',
                'verbose_name_plural': 'Anexos do PGR',
                'db_table': 'pgr_anexo_pgr',
                'ordering': ['ordem', 'numero_romano', 'criado_em'],
                'unique_together': {('pgr_documento', 'numero_romano')},
            },
        ),
    ]
