# Generated by Django 5.2.13 on 2026-04-14 17:34

import core.mixins
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgr_gestao', '0010_anexopgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexopgr',
            name='mime_type',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='acompanhamentoplanoacao',
            name='arquivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to=core.mixins.UploadPath('pgr_acompanhamentos'), validators=[core.validators.SecureFileValidator(app_name='pgr_acompanhamentos')], verbose_name='Arquivo de Evidência'),
        ),
        migrations.AlterField(
            model_name='anexopgr',
            name='arquivo',
            field=models.FileField(help_text='PDF, DOC, DOCX, XLS, XLSX, JPG, PNG (máx. 50MB)', upload_to=core.mixins.UploadPath('pgr_anexos'), validators=[core.validators.SecureFileValidator(app_name='pgr_anexos')], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexopgr',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='anexopgr',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='anexopgr',
            name='tipo_anexo',
            field=models.CharField(choices=[('analise_ruido', 'Análise Quantitativa de Ruído'), ('analise_calor', 'Análise Quantitativa de Calor'), ('analise_quimica', 'Análise Quantitativa de Agentes Químicos'), ('analise_vibracao', 'Análise Quantitativa de Vibração'), ('analise_iluminacao', 'Análise de Iluminância'), ('analise_biologica', 'Análise de Agentes Biológicos'), ('laudo_insalubridade', 'Laudo de Insalubridade'), ('laudo_periculosidade', 'Laudo de Periculosidade'), ('laudo_ergonomico', 'Laudo Ergonômico'), ('aet', 'Análise Ergonômica do Trabalho (AET)'), ('ppra', 'PPRA – Programa de Prevenção de Riscos Ambientais'), ('pcmso', 'PCMSO – Programa de Controle Médico'), ('ltcat', 'LTCAT – Laudo Técnico das Condições do Ambiente'), ('certificado_calibracao', 'Certificado de Calibração de Equipamentos'), ('art', 'ART – Anotação de Responsabilidade Técnica'), ('mapa_risco', 'Mapa de Risco'), ('planta_baixa', 'Planta Baixa / Layout'), ('fotografias', 'Registro Fotográfico'), ('treinamento', 'Certificado / Registro de Treinamento'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de Anexo'),
        ),
        migrations.AlterField(
            model_name='anexoplanoacao',
            name='arquivo',
            field=models.FileField(upload_to=core.mixins.UploadPath('pgr_planos_acao_anexos'), validators=[core.validators.SecureFileValidator(app_name='pgr_planos_acao_anexos')], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='avaliacaoquantitativa',
            name='laudo_tecnico',
            field=models.FileField(blank=True, null=True, upload_to=core.mixins.UploadPath('pgr_laudos'), validators=[core.validators.SecureFileValidator(app_name='pgr_laudos')], verbose_name='Laudo Técnico'),
        ),
        migrations.AlterField(
            model_name='planoacaopgr',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=core.mixins.UploadPath('pgr_evidencias'), validators=[core.validators.SecureFileValidator(app_name='pgr_evidencias')], verbose_name='Evidência de Conclusão'),
        ),
    ]
