# Generated by Django 4.2.16 on 2026-03-15 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0002_initial'),
        ('cliente', '0003_alter_cliente_filial'),
        ('ltcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localprestacaoservicoltcat',
            options={'ordering': ['nome_local'], 'verbose_name': 'Local de Prestação de Serviço LTCAT', 'verbose_name_plural': 'Locais de Prestação de Serviço LTCAT'},
        ),
        migrations.RemoveField(
            model_name='ltcatdocumento',
            name='local_prestacao',
        ),
        migrations.AddField(
            model_name='localprestacaoservicoltcat',
            name='logradouro',
            field=models.ForeignKey(blank=True, help_text='Selecione o endereço cadastrado no sistema de logradouros', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_prestacao_ltcat', to='logradouro.logradouro', verbose_name='Endereço (Logradouro)'),
        ),
        migrations.AddField(
            model_name='localprestacaoservicoltcat',
            name='nome_local',
            field=models.CharField(default=datetime.datetime(2026, 3, 15, 16, 50, 54, 45805, tzinfo=datetime.timezone.utc), help_text='Ex: Unidade Operacional Camaçari, Sede Administrativa, etc.', max_length=300, verbose_name='Nome / Identificação do Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltcatdocumento',
            name='empresa_contratada',
            field=models.ForeignKey(blank=True, help_text='Empresa que elabora o LTCAT (ex: CETEST)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_ltcat_contratada', to='ltcat.empresaltcat', verbose_name='Empresa Contratada (CETEST)'),
        ),
        migrations.AlterField(
            model_name='localprestacaoservicoltcat',
            name='razao_social',
            field=models.CharField(blank=True, max_length=300, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='ltcatdocumento',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_ltcat', related_query_name='documento_ltcat', to='cliente.cliente', verbose_name='Empresa Contratante (Cliente)'),
        ),
        migrations.CreateModel(
            name='DocumentoLocalPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False, help_text='Marque se este é o local principal de prestação', verbose_name='Local Principal?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('local_prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_vinculos', to='ltcat.localprestacaoservicoltcat', verbose_name='Local de Prestação')),
                ('ltcat_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_locais', to='ltcat.ltcatdocumento', verbose_name='Documento LTCAT')),
            ],
            options={
                'verbose_name': 'Local de Prestação do Documento',
                'verbose_name_plural': 'Locais de Prestação do Documento',
                'db_table': 'ltcat_documento_local_prestacao',
                'ordering': ['-principal', 'ordem', 'local_prestacao__nome_local'],
                'unique_together': {('ltcat_documento', 'local_prestacao')},
            },
        ),
        migrations.AddField(
            model_name='ltcatdocumento',
            name='locais_prestacao',
            field=models.ManyToManyField(blank=True, through='ltcat.DocumentoLocalPrestacao', to='ltcat.localprestacaoservicoltcat', verbose_name='Locais de Prestação'),
        ),
    ]
