# Generated by Django 4.2.16 on 2026-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltcat', '0002_alter_localprestacaoservicoltcat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalresponsavelltcat',
            name='assinatura_imagem',
            field=models.ImageField(blank=True, help_text='Imagem da assinatura digital do profissional', null=True, upload_to='assinaturas_ltcat/', verbose_name='Assinatura Digital'),
        ),
    ]
