# Generated by Django 5.2.13 on 2026-04-12 19:51

import core.mixins
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltcat', '0003_add_assinatura_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoltcat',
            name='mime_type',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='anexoltcat',
            name='arquivo',
            field=models.FileField(help_text='PDF, DOCX, XLSX, JPG, PNG, WEBP (máx. 50MB)', upload_to=core.mixins.UploadPath('ltcat_anexos'), validators=[core.validators.SecureFileValidator(app_name='ltcat_anexos')], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='profissionalresponsavelltcat',
            name='assinatura_imagem',
            field=models.ImageField(blank=True, help_text='Imagem da assinatura digital (JPG, PNG, WEBP — máx. 2MB)', null=True, upload_to=core.mixins.UploadPath('ltcat_assinatura'), validators=[core.validators.SecureImageValidator(app_name='ltcat_assinatura')], verbose_name='Assinatura Digital'),
        ),
    ]
