# Generated by Django 5.1.6 on 2025-04-13 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(help_text='Nome da rua, avenida, etc.', max_length=150, verbose_name='Endereço')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Número não pode ser menor que 1')], verbose_name='Número')),
                ('cep', models.CharField(help_text='Apenas números (8 dígitos)', max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 dígitos', regex='^\\d{8}$')], verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=60, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado')),
                ('pais', models.CharField(default='Brasil', max_length=30, verbose_name='País')),
                ('ponto_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referência')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'db_table': 'logradouro',
                'ordering': ['estado', 'cidade', 'bairro', 'endereco'],
                'indexes': [models.Index(fields=['estado', 'cidade'], name='idx_estado_cidade'), models.Index(fields=['cep'], name='idx_logradouro_cep')],
                'constraints': [models.UniqueConstraint(fields=('endereco', 'numero', 'complemento', 'cep'), name='unique_endereco_completo')],
            },
        ),
    ]
