# Generated by Django 5.2 on 2025-05-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logradouro',
            table='logradouro',
        ),
    ]
