# Generated by Django 5.2 on 2025-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='estado',
            field=models.CharField(choices=[('', 'Estado'), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MG'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='SP', max_length=2, verbose_name='Estado'),
        ),
    ]
