# Generated by Django 5.2 on 2025-08-06 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0001_initial'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logradouro',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logradouros', to='usuario.filial', verbose_name='Filial'),
        ),
    ]
