# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logradouro', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logradouro',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logradouros', to='usuario.filial', verbose_name='Filial'),
        ),
        migrations.AddIndex(
            model_name='logradouro',
            index=models.Index(fields=['estado', 'cidade'], name='idx_estado_cidade'),
        ),
        migrations.AddIndex(
            model_name='logradouro',
            index=models.Index(fields=['cep'], name='idx_logradouro_cep'),
        ),
        migrations.AddConstraint(
            model_name='logradouro',
            constraint=models.UniqueConstraint(fields=('endereco', 'numero', 'complemento', 'cep'), name='unique_endereco_completo'),
        ),
    ]
