# Generated by Django 5.2 on 2025-10-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
    ]
