# Generated by Django 4.2.16 on 2026-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logradouro',
            name='unique_endereco_completo',
        ),
        migrations.AddField(
            model_name='logradouro',
            name='tipo_logradouro',
            field=models.CharField(choices=[('RUA', 'Rua'), ('AV', 'Avenida'), ('AL', 'Alameda'), ('BC', 'Beco'), ('EST', 'Estrada'), ('LAR', 'Largo'), ('PC', 'Praça'), ('ROD', 'Rodovia'), ('TRV', 'Travessa'), ('VL', 'Vila'), ('VD', 'Viaduto'), ('LIN', 'Linha'), ('ACE', 'Acesso'), ('CND', 'Condomínio'), ('LOT', 'Loteamento'), ('SIT', 'Sítio'), ('FAZ', 'Fazenda'), ('CHA', 'Chácara'), ('OUT', 'Outros')], default='RUA', help_text='Rua, Avenida, Praça, etc.', max_length=3, verbose_name='Tipo de Logradouro'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='endereco',
            field=models.CharField(help_text='Nome do logradouro (sem o tipo). Ex: das Flores, Paulista', max_length=150, verbose_name='Endereço'),
        ),
        migrations.AddConstraint(
            model_name='logradouro',
            constraint=models.UniqueConstraint(fields=('tipo_logradouro', 'endereco', 'numero', 'complemento', 'cep'), name='unique_endereco_completo'),
        ),
    ]
