# Generated by Django 4.2.28 on 2026-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0003_remove_logradouro_unique_endereco_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='tipo_logradouro',
            field=models.CharField(choices=[('RUA', 'RUA'), ('AV', 'AVENIDA'), ('AL', 'ALAMEDA'), ('BC', 'BECO'), ('EST', 'ESTRADA'), ('LAR', 'LARGO'), ('PRA', 'PRAÇA'), ('ROD', 'RODOVIA'), ('TRV', 'TRAVESSA'), ('VL', 'VILA'), ('VD', 'VIADUTO'), ('LIN', 'LINHA'), ('ACE', 'ACESSO'), ('CND', 'CONDOMÍNIO'), ('LOT', 'LOTEAMENTO'), ('SIT', 'SÍTIO'), ('FAZ', 'FAZENDA'), ('CHA', 'CHÁCARA'), ('OUT', 'OUTROS')], default='RUA', help_text='Rua, Avenida, Praça, etc.', max_length=3, verbose_name='Tipo de Logradouro'),
        ),
    ]
