
# Lista de estados (DEFINA ISSO ANTES DOS MODELOS)
ESTADOS_BRASIL = [
    ('', 'Estado'),
    ('AC', 'AC'),
    ('AL', 'AL'),
    ('AP', 'AP'),
    ('AM', 'AM'),
    ('BA', 'BA'),
    ('CE', 'CE'),
    ('DF', 'DF'),
    ('ES', 'ES'),
    ('GO', 'GO'),
    ('MA', 'MA'),
    ('MT', 'MG'),
    ('MS', 'MS'),
    ('MG', 'MG'),
    ('PA', 'PA'),
    ('PB', 'PB'),
    ('PR', 'PR'),
    ('PE', 'PE'),
    ('PI', 'PI'),
    ('RJ', 'RJ'),
    ('RN', 'RN'),
    ('RS', 'RS'),
    ('RO', 'RO'),
    ('RR', 'RR'),
    ('SC', 'SC'),
    ('SP', 'SP'),
    ('SE', 'SE'),
    ('TO', 'TO'),
]

TIPOS_LOGRADOURO = [
    ('RUA', 'RUA'),
    ('AV', 'AVENIDA'),
    ('AL', 'ALAMEDA'),
    ('BC', 'BECO'),
    ('EST', 'ESTRADA'),
    ('LAR', 'LARGO'),
    ('PRA', 'PRAÇA'),
    ('ROD', 'RODOVIA'), 
    ('TRV', 'TRAVESSA'),
    ('VL', 'VILA'),
    ('VD', 'VIADUTO'),
    ('LIN', 'LINHA'),
    ('ACE', 'ACESSO'),
    ('CND', 'CONDOMÍNIO'),
    ('LOT', 'LOTEAMENTO'),
    ('SIT', 'SÍTIO'),
    ('FAZ', 'FAZENDA'),
    ('CHA', 'CHÁCARA'),
    ('OUT', 'OUTROS'),
]