# Generated by Django 5.2 on 2025-09-08 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0001_initial'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data Agendada')),
                ('data_realizacao', models.DateField(blank=True, null=True, verbose_name='Data de Realização')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-data_agendada'],
            },
        ),
        migrations.CreateModel(
            name='CartaoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(default='(11) 3045-9400', max_length=20, verbose_name='Telefone de Contato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_tag', to='usuario.filial')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_tag', to='departamento_pessoal.funcionario', verbose_name='Funcionário Proprietário')),
            ],
            options={
                'verbose_name': 'Cartão de Bloqueio (Tag)',
                'verbose_name_plural': 'Cartões de Bloqueio (Tags)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Título do Incidente')),
                ('detalhes', models.TextField(verbose_name='Detalhes da Ocorrência')),
                ('setor', models.CharField(choices=[('OPERAÇAO', 'Operação'), ('LOGISTICA', 'Logística'), ('MANUTENCAO', 'Manutenção'), ('ADMINISTRACAO', 'Administração')], max_length=20, verbose_name='Setor')),
                ('tipo_incidente', models.CharField(choices=[('QUASE_ACIDENTE', 'Quase Acidente'), ('COM_AFASTAMENTO', 'Com Afastamento'), ('SEM_AFASTAMENTO', 'Sem Afastamento')], max_length=20, verbose_name='Tipo')),
                ('data_ocorrencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Ocorrência')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='usuario.filial')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-data_ocorrencia'],
            },
        ),
    ]
