# Generated by Django 5.2 on 2025-07-02 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Título do Incidente')),
                ('detalhes', models.TextField(verbose_name='Detalhes da Ocorrência')),
                ('setor', models.CharField(choices=[('PRODUCAO_A', 'Produção A'), ('PRODUCAO_B', 'Produção B'), ('LOGISTICA', 'Logística'), ('MANUTENCAO', 'Manutenção'), ('ADM', 'Administrativo'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Setor')),
                ('tipo_incidente', models.CharField(choices=[('QUASE_ACIDENTE', 'Quase Acidente'), ('COM_AFASTAMENTO', 'Com Afastamento'), ('SEM_AFASTAMENTO', 'Sem Afastamento'), ('AMBIENTAL', 'Incidente Ambiental')], max_length=20, verbose_name='Tipo')),
                ('data_ocorrencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Ocorrência')),
                ('causa_provavel', models.CharField(blank=True, choices=[('FALHA_EPI', 'Falha de EPI'), ('ATO_INSEGURO', 'Ato Inseguro do Colaborador'), ('CONDICAO_INSEGURA', 'Condição Insegura do Ambiente'), ('FALHA_EPC', 'Falha de Equipamento Coletivo'), ('FALTA_TREINAMENTO', 'Falta de Treinamento'), ('OUTRA', 'Outra')], max_length=30, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data Agendada')),
                ('data_realizacao', models.DateField(blank=True, null=True, verbose_name='Data de Realização')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='seguranca_trabalho.equipamento')),
                ('inspetor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-data_agendada'],
            },
        ),
    ]
