# Generated by Django 5.2 on 2025-08-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filial_delete_ferramenta'),
        ('gestao_riscos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='causa_provavel',
        ),
        migrations.AddField(
            model_name='incidente',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='core.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='setor',
            field=models.CharField(choices=[('PRODUCAO_A', 'Produção A'), ('LOGISTICA', 'Logística'), ('MANUTENCAO', 'Manutenção')], max_length=20, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.CharField(choices=[('QUASE_ACIDENTE', 'Quase Acidente'), ('COM_AFASTAMENTO', 'Com Afastamento')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
    ]
