# Generated by Django 5.2 on 2025-09-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_riscos', '0001_initial'),
        ('seguranca_trabalho', '0001_initial'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='inspetor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
