# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0002_initial'),
        ('gestao_riscos', '0001_initial'),
        ('seguranca_trabalho', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaotag',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_tag', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='cartaotag',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_tag', to='departamento_pessoal.funcionario', verbose_name='Funcionário Proprietário'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='inspetor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
