# Generated by Django 5.2 on 2025-08-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_riscos', '0002_remove_incidente_causa_provavel_incidente_filial_and_more'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='usuario.filial'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='setor',
            field=models.CharField(choices=[('OPERAÇAO', 'Operação'), ('LOGISTICA', 'Logística'), ('MANUTENCAO', 'Manutenção'), ('ADMINISTRACAO', 'Administração')], max_length=20, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.CharField(choices=[('QUASE_ACIDENTE', 'Quase Acidente'), ('COM_AFASTAMENTO', 'Com Afastamento'), ('SEM_AFASTAMENTO', 'Sem Afastamento')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='usuario.filial'),
        ),
    ]
