# Generated by Django 5.2 on 2025-09-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0002_alter_funcionario_cliente'),
        ('gestao_riscos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaotag',
            name='cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_tag', to='departamento_pessoal.cargo', verbose_name='Cargo'),
        ),
    ]
