# Generated by Django 5.2 on 2025-11-16 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_riscos', '0002_initial'),
        ('seguranca_trabalho', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecao',
            name='inspetor',
        ),
        migrations.AddField(
            model_name='inspecao',
            name='entrega_epi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='seguranca_trabalho.entregaepi', verbose_name='Item de EPI Específico'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes', to='seguranca_trabalho.equipamento'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_APROVACAO', 'Pendente de Aprovação'), ('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
