# Generated by Django 5.2 on 2025-08-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0003_alter_documento_options_alter_cargo_ativo_and_more'),
        ('gestao_riscos', '0003_alter_incidente_filial_alter_incidente_setor_and_more'),
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='CartaoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(default='(11) 3045-9400', max_length=20, verbose_name='Telefone de Contato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_tag', to='usuario.filial')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_tag', to='departamento_pessoal.funcionario', verbose_name='Funcionário Proprietário')),
            ],
            options={
                'verbose_name': 'Cartão de Bloqueio (Tag)',
                'verbose_name_plural': 'Cartões de Bloqueio (Tags)',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
