# Generated by Django 5.2 on 2026-02-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_riscos', '0003_remove_inspecao_inspetor_inspecao_entrega_epi_and_more'),
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('fisico', 'Físico'), ('quimico', 'Químico'), ('biologico', 'Biológico'), ('ergonomico', 'Ergonômico'), ('acidente', 'Acidente/Mecânico')], max_length=20, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Risco')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_cor', models.CharField(default='#808080', help_text='Cor no formato hexadecimal (#RRGGBB)', max_length=7, verbose_name='Código da Cor')),
                ('nr_referencia', models.CharField(blank=True, help_text='Ex: NR-15, NR-17', max_length=50, verbose_name='NR de Referência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_risco', to='usuario.filial')),
            ],
            options={
                'verbose_name': 'Tipo de Risco',
                'verbose_name_plural': 'Tipos de Riscos',
                'db_table': 'gestao_tipo_risco',
                'ordering': ['categoria', 'nome'],
                'unique_together': {('categoria', 'nome', 'filial')},
            },
        ),
    ]
