# Generated by Django 4.2.16 on 2026-03-25 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0005_reestruturar_documento_completo'),
        ('gestao_riscos', '0005_add_tipo_ocorrencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidente',
            options={'ordering': ['-data_ocorrencia'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='tipo_incidente',
        ),
        migrations.AddField(
            model_name='incidente',
            name='acao_imediata',
            field=models.TextField(blank=True, help_text='Descreva o que foi feito logo após a ocorrência', verbose_name='Ação Imediata Tomada'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='cat_emitida',
            field=models.BooleanField(default=False, help_text='Comunicação de Acidente de Trabalho', verbose_name='CAT Emitida?'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidente',
            name='dias_afastamento',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias de Afastamento'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='funcionario_envolvido',
            field=models.ForeignKey(blank=True, help_text='Obrigatório para acidentes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='departamento_pessoal.funcionario', verbose_name='Funcionário Envolvido'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='gravidade',
            field=models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('GRAVISSIMA', 'Gravíssima')], default='LEVE', max_length=15, verbose_name='Gravidade'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='local_especifico',
            field=models.CharField(blank=True, help_text='Ex: Linha de produção 3, Pátio de carga, Escritório 2º andar', max_length=255, verbose_name='Local Específico'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='numero_cat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº da CAT'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='parte_corpo_atingida',
            field=models.CharField(blank=True, help_text='Ex: Mão direita, Coluna lombar, Olho esquerdo', max_length=255, verbose_name='Parte do Corpo Atingida'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Título da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='setor',
            field=models.CharField(choices=[('OPERACAO', 'Operação'), ('LOGISTICA', 'Logística'), ('MANUTENCAO', 'Manutenção'), ('ADMINISTRACAO', 'Administração')], max_length=20, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo_ocorrencia',
            field=models.CharField(choices=[('QUASE_ACIDENTE', 'Quase Acidente (Incidente)'), ('CONDICAO_INSEGURA', 'Condição Insegura'), ('ACIDENTE_SEM_AFASTAMENTO', 'Acidente sem Afastamento'), ('ACIDENTE_COM_AFASTAMENTO', 'Acidente com Afastamento'), ('ACIDENTE_TRAJETO', 'Acidente de Trajeto'), ('ACIDENTE_FATAL', 'Acidente Fatal')], default='Quase Acidente', max_length=30, verbose_name='Tipo de Ocorrência'),
        ),
    ]
