# Generated by Django 4.2.16 on 2026-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_riscos', '0007_incidente_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='classificacao',
            field=models.CharField(choices=[('', '── Selecione ──'), ('Incidentes', (('QUASE_ACIDENTE', 'Quase Acidente (Incidente)'), ('CONDICAO_INSEGURA', 'Condição Insegura'))), ('Acidentes', (('ACIDENTE_SEM_AFASTAMENTO', 'Acidente sem Afastamento'), ('ACIDENTE_COM_AFASTAMENTO', 'Acidente com Afastamento'), ('ACIDENTE_TRAJETO', 'Acidente de Trajeto'), ('ACIDENTE_FATAL', 'Acidente Fatal')))], default='Quase Acidente', max_length=30, verbose_name='Classificacao'),
        ),
    ]
