# Generated by Django 5.2.16 on 2026-09-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_riscos', '0008_alter_incidente_classificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaotag',
            options={'ordering': ['-data_criacao'], 'permissions': [('view_all_cartaotag', 'Pode visualizar todos os cartões de bloqueio da filial')], 'verbose_name': 'Cartão de Bloqueio (Tag)', 'verbose_name_plural': 'Cartões de Bloqueio (Tags)'},
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={'ordering': ['-data_ocorrencia'], 'permissions': [('view_all_incidente', 'Pode visualizar todas as ocorrências da filial')], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.AlterModelOptions(
            name='inspecao',
            options={'ordering': ['-data_agendada'], 'permissions': [('view_all_inspecao', 'Pode visualizar todas as inspeções da filial')], 'verbose_name': 'Inspeção', 'verbose_name_plural': 'Inspeções'},
        ),
    ]
