# Generated by Django 5.2.16 on 2026-09-25 16:28

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0013_alter_funcionario_options'),
        ('suprimentos', '0031_alter_parceiro_contato_alter_parceiro_telefone'),
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalaFerramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Mala/Kit')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação')),
                ('localizacao_padrao', models.CharField(max_length=100, verbose_name='Localização Padrão')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso')], db_index=True, default='disponivel', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Itens')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/malas/', verbose_name='QR Code da Mala')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malas_ferramentas', to='usuario.filial')),
            ],
            options={
                'verbose_name': 'Mala de Ferramentas',
                'verbose_name_plural': 'Malas de Ferramentas',
                'ordering': ['nome'],
                'permissions': [('retirar_mala', 'Pode realizar retirada de mala'), ('devolver_mala', 'Pode realizar devolução de mala')],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ferramenta')),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº de Patrimônio')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação (Série/QR)')),
                ('fabricante_marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabricante/Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
                ('tamanho_polegadas', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho/Polegada')),
                ('numero_laudo_tecnico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Laudo Técnico')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('localizacao_padrao', models.CharField(help_text='Ex: Armário A, Gaveta 3', max_length=100, verbose_name='Localização Padrão')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartada', 'Descartada')], db_index=True, default='disponivel', max_length=20, verbose_name='Status Interno')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('data_descarte', models.DateField(blank=True, null=True, verbose_name='Data de Descarte')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/ferramentas/', verbose_name='QR Code')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='usuario.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramentas_fornecidas', to='suprimentos.parceiro', verbose_name='Fornecedor Principal')),
                ('mala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='ferramentas.malaferramentas', verbose_name='Mala de Ferramentas')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['nome'],
                'permissions': [('retirar_ferramenta', 'Pode realizar retirada de ferramenta'), ('devolver_ferramenta', 'Pode realizar devolução de ferramenta')],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('criacao', 'Criação do Registro'), ('alteracao', 'Alteração de Dados'), ('retirada', 'Retirada'), ('devolucao', 'Devolução'), ('manutencao_inicio', 'Início da Manutenção'), ('manutencao_fim', 'Fim da Manutenção'), ('descarte', 'Descarte/Inativação')], db_index=True, max_length=20)),
                ('descricao', models.CharField(help_text='Detalhes do evento.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e Hora')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividades_ferramentas', to='usuario.filial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.ferramenta')),
                ('mala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.malaferramentas')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_uso', models.CharField(choices=[('volante', 'Volante/Diária'), ('permanente', 'Permanente')], default='volante', max_length=30, verbose_name='Tipo de Uso')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_devolucao_prevista', models.DateTimeField(verbose_name='Devolução Prevista')),
                ('condicoes_retirada', models.TextField(help_text='Descreva o estado do item.', verbose_name='Condições na Retirada')),
                ('data_devolucao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Devolução')),
                ('condicoes_devolucao', models.TextField(blank=True, null=True, verbose_name='Condições na Devolução')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.ferramenta')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='usuario.filial')),
                ('mala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.malaferramentas')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('retirado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_retiradas', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_retirada'],
                'permissions': [('add_retirada', 'Pode registrar retirada (movimentação)'), ('add_devolucao', 'Pode registrar devolução (movimentação)')],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_imagem', models.ImageField(blank=True, null=True, upload_to=core.models.caminho_assinatura)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('retirada', 'Retirada'), ('devolucao', 'Devolução')], max_length=10)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='ferramentas.movimentacao')),
            ],
            options={
                'verbose_name': 'Assinatura de Movimentação',
                'verbose_name_plural': 'Assinaturas de Movimentação',
            },
        ),
        migrations.CreateModel(
            name='TermoDeResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_imagem', models.ImageField(blank=True, null=True, upload_to=core.models.caminho_assinatura)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('tipo_uso', models.CharField(choices=[('FER', 'Ferramental'), ('MAL', 'Mala')], max_length=30, verbose_name='Tipo de Uso')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('estornado', 'Estornado')], db_index=True, default='ativo', max_length=20)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_responsabilidade', to='usuario.filial')),
                ('movimentado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Movimentado por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_responsabilidade', to='departamento_pessoal.funcionario', verbose_name='Responsável')),
                ('separado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_separados', to='departamento_pessoal.funcionario', verbose_name='Separado por (Coordenador)')),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade',
                'verbose_name_plural': 'Termos de Responsabilidade',
                'ordering': ['-data_emissao'],
                'permissions': [('download_termo_pdf', 'Pode baixar PDF do termo'), ('reverter_termo', 'Pode estornar/reverter termo')],
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='termo_responsabilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_geradas', to='ferramentas.termoderesponsabilidade', verbose_name='Termo Associado'),
        ),
        migrations.CreateModel(
            name='ItemTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('item', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.ferramenta', verbose_name='Ferramenta')),
                ('mala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.malaferramentas', verbose_name='Mala')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ferramentas.termoderesponsabilidade', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Item do Termo',
                'verbose_name_plural': 'Itens do Termo',
            },
        ),
        migrations.AddIndex(
            model_name='ferramenta',
            index=models.Index(fields=['status', 'filial'], name='idx_ferramenta_status_filial'),
        ),
        migrations.AddIndex(
            model_name='ferramenta',
            index=models.Index(fields=['codigo_identificacao'], name='idx_ferramenta_codigo'),
        ),
        migrations.AddConstraint(
            model_name='assinaturamovimentacao',
            constraint=models.UniqueConstraint(fields=('movimentacao', 'tipo'), name='uniq_assinatura_por_tipo_movimentacao'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['data_devolucao', 'ferramenta'], name='idx_mov_dev_ferramenta'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['data_devolucao', 'mala'], name='idx_mov_dev_mala'),
        ),
    ]
