# Generated by Django 5.2 on 2025-10-14 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('criacao', 'Criação do Registro'), ('alteracao', 'Alteração de Dados'), ('retirada', 'Retirada de Ferramenta/Mala'), ('devolucao', 'Devolução de Ferramenta/Mala'), ('manutencao_inicio', 'Início da Manutenção'), ('manutencao_fim', 'Fim da Manutenção')], max_length=20)),
                ('descricao', models.CharField(help_text='Detalhes do evento.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ferramenta')),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº de Patrimônio')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação (Série/QR)')),
                ('fabricante_marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabricante/Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
                ('tamanho_polegadas', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho/Polegada')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade (QTDA)')),
                ('numero_laudo_tecnico', models.CharField(blank=True, max_length=20, null=True)),
                ('localizacao_padrao', models.CharField(help_text='Ex: Armário A, Gaveta 3', max_length=100, verbose_name='Localização Padrão')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartada', 'Descartada')], default='disponivel', max_length=20, verbose_name='Status Interno')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('data_descarte', models.DateField(blank=True, null=True, verbose_name='Data de Descarte')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/ferramentas/', verbose_name='QR Code')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade (QTDA)')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade (UN)')),
                ('item', models.CharField(max_length=255, verbose_name='Item (Descrição)')),
            ],
            options={
                'verbose_name': 'Item do Termo',
                'verbose_name_plural': 'Itens do Termo',
            },
        ),
        migrations.CreateModel(
            name='MalaFerramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Mala/Kit')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação')),
                ('localizacao_padrao', models.CharField(max_length=100, verbose_name='Localização Padrão')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso')], default='disponivel', max_length=20)),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade (QTDA)')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/malas/', verbose_name='QR Code da Mala')),
            ],
            options={
                'verbose_name': 'Mala de Ferramentas',
                'verbose_name_plural': 'Malas de Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_uso', models.CharField(choices=[('volante', 'VolanteDiária'), ('permanete', 'Permanente')], default='volante', max_length=30, verbose_name='Tipo de Uso')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateTimeField(verbose_name='Devolução Prevista')),
                ('condicoes_retirada', models.TextField(help_text='Descreva o estado do item (arranhões, funcionamento, etc.)', verbose_name='Condições na Retirada')),
                ('assinatura_retirada', models.ImageField(upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura de Retirada')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('condicoes_devolucao', models.TextField(blank=True, null=True, verbose_name='Condições na Devolução')),
                ('assinatura_devolucao', models.ImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura de Devolução')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.CreateModel(
            name='TermoDeResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento (Assinatura)')),
                ('tipo_uso', models.CharField(choices=[('FER', 'Ferramental'), ('MAL', 'Mala')], max_length=30, verbose_name='Tipo de Uso (Ferramental/Mala)')),
                ('assinatura_data', models.TextField(blank=True, null=True, verbose_name='Dados da Assinatura (Base64)')),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade',
                'verbose_name_plural': 'Termos de Responsabilidade',
            },
        ),
    ]
