# Generated by Django 5.2.17 on 2026-10-04 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0013_alter_funcionario_options'),
        ('ferramentas', '00XX_patch_constraints_movimentacao'),
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemtermo',
            name='item_termo_ferramenta_xor_mala',
        ),
        migrations.RemoveConstraint(
            model_name='movimentacao',
            name='mov_ferramenta_xor_mala',
        ),
        migrations.RemoveConstraint(
            model_name='movimentacao',
            name='uniq_ferramenta_mov_ativa',
        ),
        migrations.RemoveConstraint(
            model_name='movimentacao',
            name='uniq_mala_mov_ativa',
        ),
        migrations.AddConstraint(
            model_name='itemtermo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ferramenta__isnull', False), ('mala__isnull', True)), models.Q(('ferramenta__isnull', True), ('mala__isnull', False)), models.Q(('ferramenta__isnull', True), ('mala__isnull', True)), _connector='OR'), name='itemtermo_ferramenta_xor_mala'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ferramenta__isnull', False), ('mala__isnull', True)), models.Q(('ferramenta__isnull', True), ('mala__isnull', False)), _connector='OR'), name='movimentacao_ferramenta_xor_mala'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.UniqueConstraint(condition=models.Q(('data_devolucao__isnull', True)), fields=('ferramenta',), name='movimentacao_uniq_ferramenta_ativa'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.UniqueConstraint(condition=models.Q(('data_devolucao__isnull', True)), fields=('mala',), name='movimentacao_uniq_mala_ativa'),
        ),
    ]
