# Generated by Django 5.2 on 2025-09-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_remove_usuario_filial_usuario_filiais_permitidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ferramenta')),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº de Patrimônio')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação (Série/QR)')),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacao_padrao', models.CharField(help_text='Ex: Armário A, Gaveta 3', max_length=100, verbose_name='Localização Padrão')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartada', 'Descartada')], default='disponivel', max_length=20)),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='usuario.filial')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('criacao', 'Criação do Registro'), ('alteracao', 'Alteração de Dados'), ('retirada', 'Retirada de Ferramenta'), ('devolucao', 'Devolução de Ferramenta'), ('manutencao_inicio', 'Início da Manutenção'), ('manutencao_fim', 'Fim da Manutenção')], max_length=20)),
                ('descricao', models.CharField(help_text='Detalhes do evento.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='usuario.filial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.ferramenta')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateTimeField(verbose_name='Devolução Prevista')),
                ('condicoes_retirada', models.TextField(help_text='Descreva o estado da ferramenta (arranhões, funcionamento, etc.)', verbose_name='Condições na Retirada')),
                ('assinatura_retirada', models.ImageField(upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura de Retirada')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('condicoes_devolucao', models.TextField(blank=True, null=True, verbose_name='Condições na Devolução')),
                ('assinatura_devolucao', models.ImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m/', verbose_name='Assinatura de Devolução')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.ferramenta')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao', to='usuario.filial')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('retirado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_retiradas', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por (Responsável)')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_retirada'],
            },
        ),
    ]
