# Generated by Django 5.2 on 2025-08-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponivel'), ('EM_USO', 'Em Uso'), ('EM_MANUTENCAO', 'Em Manutencao')], default='DISPONIVEL', max_length=20),
        ),
    ]
