# Generated by Django 5.2 on 2025-09-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_initial'),
        ('usuario', '0004_groupcardpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.ferramenta'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('criacao', 'Criação do Registro'), ('alteracao', 'Alteração de Dados'), ('retirada', 'Retirada de Ferramenta/Mala'), ('devolucao', 'Devolução de Ferramenta/Mala'), ('manutencao_inicio', 'Início da Manutenção'), ('manutencao_fim', 'Fim da Manutenção')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/ferramentas/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='condicoes_retirada',
            field=models.TextField(help_text='Descreva o estado do item (arranhões, funcionamento, etc.)', verbose_name='Condições na Retirada'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.ferramenta'),
        ),
        migrations.CreateModel(
            name='MalaFerramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Mala/Kit')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação')),
                ('localizacao_padrao', models.CharField(max_length=100, verbose_name='Localização Padrão')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso')], default='disponivel', max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/malas/', verbose_name='QR Code da Mala')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malas_ferramentas', to='usuario.filial')),
            ],
            options={
                'verbose_name': 'Mala de Ferramentas',
                'verbose_name_plural': 'Malas de Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.malaferramentas'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='ferramentas.malaferramentas', verbose_name='Mala/Kit'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.malaferramentas'),
        ),
    ]
