# Generated by Django 5.2.17 on 2026-10-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_remove_itemtermo_item_termo_ferramenta_xor_mala_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimentacao',
            name='movimentacao_uniq_ferramenta_ativa',
        ),
        migrations.RemoveConstraint(
            model_name='movimentacao',
            name='movimentacao_uniq_mala_ativa',
        ),
    ]
