# Generated by Django 5.2 on 2025-10-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_pessoal', '0002_initial'),
        ('ferramentas', '0001_initial'),
        ('suprimentos', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramentas_fornecidas', to='suprimentos.parceiro', verbose_name='Fornecedor Principal'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.ferramenta'),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.ferramenta', verbose_name='Ferramenta Associada'),
        ),
        migrations.AddField(
            model_name='malaferramentas',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malas_ferramentas', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.malaferramentas', verbose_name='Mala Associada'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='ferramentas.malaferramentas', verbose_name='Mala de Ferramentas'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.malaferramentas'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.ferramenta'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ferramentas.malaferramentas'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='retirado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_retiradas', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por (Responsável)'),
        ),
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_responsabilidade', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='movimentado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Movimentado por'),
        ),
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_responsabilidade', to='departamento_pessoal.funcionario', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='separado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_separados', to='departamento_pessoal.funcionario', verbose_name='Separado por (Coordenador)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='termo_responsabilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_geradas', to='ferramentas.termoderesponsabilidade', verbose_name='Termo de Responsabilidade Associado'),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ferramentas.termoderesponsabilidade', verbose_name='Termo'),
        ),
    ]
