# Generated by Django 5.2.16 on 2026-09-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_initial'),
        ('suprimentos', '0032_material_ferramenta_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='pedido_compra_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.pedidocompra'),
        ),
    ]
