# Generated by Django 5.2 on 2026-02-26 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_initial'),
        ('suprimentos', '0002_initial'),
        ('usuario', '0002_alter_filial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termoderesponsabilidade',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Termo de Responsabilidade', 'verbose_name_plural': 'Termos de Responsabilidade'},
        ),
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('estornado', 'Estornado')], db_index=True, default='ativo', max_length=20, verbose_name='Status do Termo'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividades_ferramentas', to='usuario.filial'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('criacao', 'Criação do Registro'), ('alteracao', 'Alteração de Dados'), ('retirada', 'Retirada'), ('devolucao', 'Devolução'), ('manutencao_inicio', 'Início da Manutenção'), ('manutencao_fim', 'Fim da Manutenção'), ('descarte', 'Descarte/Inativação')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='numero_laudo_tecnico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Laudo Técnico'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartada', 'Descartada')], db_index=True, default='disponivel', max_length=20, verbose_name='Status Interno'),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.ferramenta', verbose_name='Ferramenta'),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Descrição do Item'),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.malaferramentas', verbose_name='Mala'),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='unidade',
            field=models.CharField(max_length=10, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='malaferramentas',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de Itens'),
        ),
        migrations.AlterField(
            model_name='malaferramentas',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso')], db_index=True, default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='condicoes_retirada',
            field=models.TextField(help_text='Descreva o estado do item.', verbose_name='Condições na Retirada'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_retirada',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='usuario.filial'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='retirado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_retiradas', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='termo_responsabilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_geradas', to='ferramentas.termoderesponsabilidade', verbose_name='Termo Associado'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_uso',
            field=models.CharField(choices=[('volante', 'Volante/Diária'), ('permanente', 'Permanente')], default='volante', max_length=30, verbose_name='Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='termoderesponsabilidade',
            name='assinatura_data',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura (Base64)'),
        ),
        migrations.AlterField(
            model_name='termoderesponsabilidade',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='termoderesponsabilidade',
            name='tipo_uso',
            field=models.CharField(choices=[('FER', 'Ferramental'), ('MAL', 'Mala')], max_length=30, verbose_name='Tipo de Uso'),
        ),
        migrations.AddIndex(
            model_name='ferramenta',
            index=models.Index(fields=['status', 'filial'], name='idx_ferramenta_status_filial'),
        ),
        migrations.AddIndex(
            model_name='ferramenta',
            index=models.Index(fields=['codigo_identificacao'], name='idx_ferramenta_codigo'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['data_devolucao', 'ferramenta'], name='idx_mov_dev_ferramenta'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['data_devolucao', 'mala'], name='idx_mov_dev_mala'),
        ),
    ]
