# Generated by Django 5.2.16 on 2026-09-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento_pessoal', '0013_alter_funcionario_options'),
        ('ferramentas', '0002_ferramenta_pedido_compra_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtermo',
            name='data_separacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Separação'),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='separado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_separados', to='departamento_pessoal.funcionario', verbose_name='Separado por'),
        ),
    ]
