# Generated by Django 5.2 on 2025-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_alter_atividade_ferramenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='data_descarte',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Descarte'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='fabricante_marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabricante/Marca'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='numero_laudo_tecnico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='tamanho_polegadas',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho/Polegada'),
        ),
    ]
