# Generated by Django 5.2 on 2025-08-02 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_ferramenta_qr_code_alter_ferramenta_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartada', 'Descartada')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('criacao', 'Criação do Registro'), ('alteracao', 'Alteração de Dados'), ('retirada', 'Retirada de Ferramenta'), ('devolucao', 'Devolução de Ferramenta'), ('manutencao_inicio', 'Início da Manutenção'), ('manutencao_fim', 'Fim da Manutenção')], max_length=20)),
                ('descricao', models.CharField(help_text='Detalhes do evento.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ferramentas.ferramenta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
    ]
