# Generated by Django 5.2.17 on 2026-10-04 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_remove_movimentacao_movimentacao_uniq_ferramenta_ativa_and_more'),
        ('usuario', '0003_padroniza_nomes_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimentacao',
            name='movimentacao_ferramenta_xor_mala',
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ferramenta__isnull', False), ('mala__isnull', True)), models.Q(('ferramenta__isnull', True), ('mala__isnull', False)), _connector='OR'), name='mov_ferramenta_xor_mala'),
        ),
    ]
