# Generated by Django 4.2.28 on 2026-05-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0014_remove_pedido_descricao_material_and_more'),
        ('ferramentas', '0003_alter_termoderesponsabilidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='pedido_compra_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.pedidocompra'),
        ),
    ]
