# Generated by Django 5.2 on 2025-09-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_remove_ferramenta_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='tipo_uso',
            field=models.CharField(choices=[('volante', 'VolanteDiária'), ('permanete', 'Permanente')], default='volante', max_length=30, verbose_name='Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='mala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='ferramentas.malaferramentas', verbose_name='Mala de Ferramentas'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartada', 'Descartada')], default='disponivel', max_length=20, verbose_name='Status Interno'),
        ),
    ]
