# Generated by Django 5.2.16 on 2026-09-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_itemtermo_data_separacao_itemtermo_separado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termoderesponsabilidade',
            options={'ordering': ['-data_emissao'], 'permissions': [('reverter_termo', 'Pode estornar termo de responsabilidade'), ('download_termo_pdf', 'Pode baixar PDF do termo'), ('enviar_link_assinatura', 'Pode enviar link de assinatura remota'), ('view_ip_completo', 'Pode ver IP completo de assinatura (auditoria)')], 'verbose_name': 'Termo de Responsabilidade', 'verbose_name_plural': 'Termos de Responsabilidade'},
        ),
    ]
