# Generated by Django 5.2 on 2025-08-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_alter_ferramenta_status_and_more'),
        ('usuario', '0002_filial_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='usuario.filial'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao', to='usuario.filial'),
        ),
    ]
