# Generated by Django 5.2 on 2025-09-26 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_telefone'),
        ('departamento_pessoal', '0007_filial_alter_documento_filial'),
        ('ferramentas', '0004_movimentacao_tipo_uso_alter_ferramenta_mala_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoDeResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_uso', models.CharField(choices=[('FER', 'Ferramental'), ('MAL', 'Mala')], max_length=30, verbose_name='Tipo de Uso (Ferramental/Mala)')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação (Movimentação)')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento (Assinatura)')),
                ('assinatura_data', models.TextField(blank=True, null=True, verbose_name='Dados da Assinatura (Base64/JSON)')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_associados', to='cliente.cliente', verbose_name='Contrato Associado')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_coordenados', to='departamento_pessoal.funcionario', verbose_name='Coordenador')),
                ('movimentado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Movimentado por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_responsavel', to='departamento_pessoal.funcionario', verbose_name='Responsável pelo Uso')),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade',
                'verbose_name_plural': 'Termos de Responsabilidade',
            },
        ),
        migrations.CreateModel(
            name='ItemTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade (QTDA)')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade (UNI)')),
                ('item', models.CharField(max_length=255, verbose_name='Item (Descrição)')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.ferramenta', verbose_name='Ferramenta Associada')),
                ('mala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.malaferramentas', verbose_name='Mala Associada')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ferramentas.termoderesponsabilidade', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Item do Termo',
                'verbose_name_plural': 'Itens do Termo',
            },
        ),
    ]
