# Generated by Django 5.1.15 on 2026-09-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0004_ferramenta_pedido_compra_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ['nome'], 'permissions': [('retirar_ferramenta', 'Pode realizar retirada de ferramenta'), ('devolver_ferramenta', 'Pode realizar devolução de ferramenta')], 'verbose_name': 'Ferramenta', 'verbose_name_plural': 'Ferramentas'},
        ),
        migrations.AlterModelOptions(
            name='malaferramentas',
            options={'ordering': ['nome'], 'permissions': [('retirar_mala', 'Pode realizar retirada de mala'), ('devolver_mala', 'Pode realizar devolução de mala')], 'verbose_name': 'Mala de Ferramentas', 'verbose_name_plural': 'Malas de Ferramentas'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_retirada'], 'permissions': [('add_retirada', 'Pode registrar retirada (movimentação)'), ('add_devolucao', 'Pode registrar devolução (movimentação)')], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
