# Generated by Django 5.1.15 on 2026-09-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0005_alter_ferramenta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termoderesponsabilidade',
            options={'ordering': ['-data_emissao'], 'permissions': [('download_termo_pdf', 'Pode baixar PDF do termo'), ('reverter_termo', 'Pode estornar/reverter termo')], 'verbose_name': 'Termo de Responsabilidade', 'verbose_name_plural': 'Termos de Responsabilidade'},
        ),
    ]
