# Generated by Django 5.2 on 2025-09-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0005_termoderesponsabilidade_itemtermo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade (QTDA)'),
        ),
    ]
