# Generated by Django 5.2.16 on 2026-09-30 17:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0005_remove_token_assinatura_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='pdf_arquivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='termos/pdf/', verbose_name='PDF do Termo (Cloudinary)'),
        ),
    ]
