# Generated by Django 5.1.15 on 2026-09-07 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0006_alter_termoderesponsabilidade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoderesponsabilidade',
            name='token_assinatura',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Assinatura Remota'),
        ),
    ]
