# Generated by Django 5.2.17 on 2026-10-03 17:34

import ferramentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0006_termoderesponsabilidade_pdf_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoderesponsabilidade',
            name='pdf_arquivo',
            field=models.FileField(blank=True, null=True, storage=ferramentas.models.raw_storage, upload_to='termos/pdf/', verbose_name='PDF do Termo'),
        ),
    ]
