# Generated by Django 5.2 on 2025-09-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0006_ferramenta_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='malaferramentas',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade (QTDA)'),
        ),
    ]
