# Generated by Django 5.2 on 2025-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0007_malaferramentas_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malaferramentas',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade (QTDA)'),
        ),
    ]
