# Generated by Django 5.2 on 2025-09-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0008_alter_malaferramentas_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='termo_responsabilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_geradas', to='ferramentas.termoderesponsabilidade', verbose_name='Termo de Responsabilidade Associado'),
        ),
    ]
