# Generated by Django 4.2.16 on 2026-03-04 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AddField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('tarefa', 'Tarefas'), ('pgr', 'PGR'), ('chat', 'Chat'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='icone',
            field=models.CharField(default='bi-bell', help_text='Classe do Bootstrap Icons (ex: bi-check-circle)', max_length=50, verbose_name='Ícone Bootstrap'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('tarefa_atrasada', 'Tarefa Atrasada'), ('tarefa_lembrete', 'Lembrete de Tarefa'), ('tarefa_prazo_proximo', 'Prazo Próximo'), ('tarefa_status', 'Mudança de Status'), ('pgr_vencimento', 'PGR Próximo ao Vencimento'), ('pgr_criado', 'Novo PGR Criado'), ('pgr_risco_critico', 'Risco Crítico Identificado'), ('pgr_plano_atrasado', 'Plano de Ação Atrasado'), ('chat_mensagem', 'Nova Mensagem'), ('sistema', 'Notificação do Sistema')], db_index=True, default='sistema', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(default=1, max_length=120, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='url_destino',
            field=models.CharField(blank=True, help_text='URL relativa do Django (ex: /tarefas/42/)', max_length=500, null=True, verbose_name='URL de Destino'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'lida'], name='notificatio_usuario_7d1f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'categoria', 'lida'], name='notificatio_usuario_4d1f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['-data_criacao'], name='notificatio_data_cr_bd2a9c_idx'),
        ),
    ]
