# Generated by Django 4.2.16 on 2026-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificacao_options_notificacao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('tarefa', 'Tarefas'), ('pgr', 'PGR'), ('chat', 'Chat'), ('sistema', 'Sistema'), ('suprimentos', 'Suprimentos')], db_index=True, default='sistema', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('tarefa_atrasada', 'Tarefa Atrasada'), ('tarefa_lembrete', 'Lembrete de Tarefa'), ('tarefa_prazo_proximo', 'Prazo Próximo'), ('tarefa_status', 'Mudança de Status'), ('pgr_vencimento', 'PGR Próximo ao Vencimento'), ('pgr_criado', 'Novo PGR Criado'), ('pgr_risco_critico', 'Risco Crítico Identificado'), ('pgr_plano_atrasado', 'Plano de Ação Atrasado'), ('chat_mensagem', 'Nova Mensagem'), ('sistema', 'Notificação do Sistema'), ('pedido_pendente', 'Pedido Aguardando Aprovação'), ('pedido_aprovado', 'Pedido Aprovado'), ('pedido_reprovado', 'Pedido Reprovado'), ('pedido_entregue', 'Pedido Entregue'), ('pedido_recebido', 'Pedido Recebido'), ('pedido_verba_excedida', 'Pedido Excede Verba')], db_index=True, default='sistema', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(default='', max_length=120, verbose_name='Título'),
        ),
    ]
