# Generated by Django 4.2.16 on 2026-03-13 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificacao_categoria_alter_notificacao_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 13, 14, 17, 33, 787293, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacao',
            name='enviada_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('tarefa_atrasada', 'Tarefa Atrasada'), ('tarefa_lembrete', 'Lembrete de Tarefa'), ('tarefa_prazo_proximo', 'Prazo Próximo'), ('tarefa_status', 'Mudança de Status'), ('tarefa_criada', 'Tarefa Criada'), ('tarefa_atribuida', 'Tarefa Atribuída'), ('tarefa_comentario', 'Novo Comentário'), ('tarefa_concluida', 'Tarefa Concluída'), ('pgr_vencimento', 'PGR Próximo ao Vencimento'), ('pgr_criado', 'Novo PGR Criado'), ('pgr_risco_critico', 'Risco Crítico Identificado'), ('pgr_plano_atrasado', 'Plano de Ação Atrasado'), ('chat_mensagem', 'Nova Mensagem'), ('sistema', 'Notificação do Sistema'), ('pedido_pendente', 'Pedido Aguardando Aprovação'), ('pedido_aprovado', 'Pedido Aprovado'), ('pedido_reprovado', 'Pedido Reprovado'), ('pedido_entregue', 'Pedido Entregue'), ('pedido_recebido', 'Pedido Recebido'), ('pedido_verba_excedida', 'Pedido Excede Verba')], db_index=True, default='sistema', max_length=30, verbose_name='Tipo'),
        ),
    ]
