# Generated by Django 4.2.28 on 2026-05-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificacao_criada_em_notificacao_enviada_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='criada_em',
        ),
    ]
