# Generated by Django 5.2.17 on 2026-10-07 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notificacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificacao',
            name='notificatio_usuario_7d1f7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='notificatio_usuario_4d1f8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='notificatio_data_cr_bd2a9c_idx',
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'categoria', 'lida', '-data_criacao'], name='notif_user_lida_dt_idx'),
        ),
    ]
