# Generated by Django 5.2 on 2025-11-18 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('ALVARA', 'Alvará'), ('CERTIDAO', 'Certidão'), ('FATURA', 'Fatura/Nota Fiscal'), ('RELATORIO', 'Relatório'), ('ART', 'ART'), ('PGR', 'PGR'), ('LAUDO', 'Laudo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('data_inicio', models.DateField(verbose_name='Data de Emissão/Início')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10)),
                ('dias_aviso', models.PositiveIntegerField(default=30, verbose_name='Avisar dias antes')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
