# Generated by Django 5.2 on 2025-11-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0001_initial'),
        ('usuario', '0002_alter_filial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('ALVARA', 'Alvará'), ('CERTIDAO', 'Certidão'), ('FATURA', 'Fatura/Nota Fiscal'), ('RELATORIO', 'Relatório'), ('ART', 'ART'), ('PGR', 'PGR'), ('LAUDO', 'Laudo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10)),
                ('dias_aviso', models.PositiveIntegerField(default=30, help_text='Dias de antecedência para notificar vencimento.', verbose_name='Avisar dias antes')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_filial', to='usuario.filial')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
