# Generated by Django 5.2 on 2025-11-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0002_arquivo_delete_documento'),
        ('cliente', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='cliente.cliente', verbose_name='Cliente Relacionado'),
        ),
    ]
